### ISSUE TITLE
Provide serialization for ann module

### ISSUE THREAD

**Issue by stereomatchingkiss** [mlpack/mlpack#495] opened 2015-12-13 20:29 UTC
As one of the users, I would like to have serialization on ann module, when I try to provide one, I find out some issues hard to solve

FFN accept the reference of the outputLayer, but this make it very hard to serialize, could I make it take the copy or rvalue of the outputLayer?

    template<typename Network, typename OutputLayer>
    FFN(Network &&network, OutputLayer &&outputLayer,
        PerformanceFunction performanceFunction = PerformanceFunction()) : 
        network(std::forward<Network>(network)),
        outputLayer(std::forward<outputLayer>(outputLayer)),
        performanceFunction(std::move(performanceFunction))
    //......

If the users need to access the output layer, we could add a public api for them to access it. Any suggestions?

**Comment by rcurtin** [comment] 2015-12-14 01:58
There are a couple options here.  I ran into this problem when adding serialization support to trees.  First, you can either replace the references with pointers and then add a default constructor that initializes all the pointers to NULL, or, I think you can add `boost::serialization::access` as a friend class, and add a private constructor to build from the archive.

The basic problem, as I encountered it (and maybe this is a little bit different) is that a lot of the mlpack code was built with the assumption that the data matrices and other relevant information (like metrics or whatever) were owned by a higher level of the code.  This makes sense when the highest-level code is "load matrix, run method, save results", but as soon as loading and saving models needs to be supported, the problem gets a lot harder, and it needs to be possible for the method to own everything.

Here's an example of what I had to do to the NeighborSearch class to get serialization working, since it internally held a reference to the data matrices:
https://github.com/mlpack/mlpack/commit/60c81702c432014544351948c091d03deeef6985

I think rvalue references like you mentioned provide a reasonable solution here.  In most places I've done something like provide a const reference constructor that copies the given data, and a move constructor that allows the object to take ownership of what's passed (and therefore avoid the copy).  In this case it seems like making `FFN::outputLayer` into `OutputLayerType` instead of `OutputLayerType&` (just like `FFN::layerTypes` is of type `LayerTypes`), like you've suggested, might be the easiest solution.  @zoq's opinion will probably be more pertinent and useful here, but I thought I'd share my experiences from my (almost finished!) refactoring of all the mlpack methods. :)

**Comment by stereomatchingkiss** [comment] 2015-12-20 02:40
>Here's an example of what I had to do to the NeighborSearch class to get serialization working

I saw the example, one of the possible solution to make serialization easier, I would try to solve this problem after pull request 451 get done.

**Comment by rcurtin** [comment] 2016-02-01 15:30
This is now a duplicate of #513, so I'll go ahead and close this one. :)

**Closed by rcurtin** 2016-02-01 15:30 UTC
