### ISSUE TITLE
Example with random forest segfaults in R

### ISSUE THREAD

**Issue by david-cortes** [mlpack/mlpack#3052] opened 2021-09-09 05:28 UTC
Trying the Python example from the user guide in R leads to a segmentation fault. Here's a short reproducer with random data:
```r
set.seed(1)
group1 <- data.frame(x = rnorm(1000, -1, .4),
					 y = rnorm(1000, -1, .2))
group2 <- data.frame(x = rnorm(1000, +1, .2),
					 y = rnorm(1000, +1, .4))
X = rbind(group1, group2)
X = rbind(X, c(-1, 1))

library(mlpack)
m = random_forest(training = as.matrix(X),
                  labels = as.matrix(as.integer(X[,1])),
                  print_training_accuracy = TRUE,
                  num_trees = 10,
                  minimum_leaf_size = 3,
                  verbose = TRUE)
```
```
Attaching package: ‘mlpack’

The following object is masked from ‘package:stats’:

    kmeans

The following object is masked from ‘package:base’:

    det

[INFO ] Training random forest with 10 trees...

 *** caught segfault ***
address 0xfffffffffffffff0, cause 'memory not mapped'

Traceback:
 1: random_forest_mlpackMain()
 2: random_forest(training = as.matrix(X), labels = as.matrix(as.integer(X[,     1])), print_training_accuracy = TRUE, num_trees = 10, minimum_leaf_size = 3,     verbose = TRUE)
An irrecoverable exception occurred. R is aborting now ...

 *** caught segfault ***
address 0xfffffffffffffff8, cause 'memory not mapped'

 *** caught segfault ***
address 0xfffffffffffffff8, cause 'memory not mapped'

 *** caught segfault ***
address 0xfffffffffffffff0, cause 'memory not mapped'

 *** caught segfault ***
address 0xfffffffffffffff8, cause 'memory not mapped'

Traceback:
 1: random_forest_mlpackMain()
 2: random_forest(training = as.matrix(X), labels = as.matrix(as.integer(X[,     1])), print_training_accuracy = TRUE, num_trees = 10, minimum_leaf_size = 3,     verbose = TRUE)

 *** caught segfault ***
address 0xfffffffffffffff8, cause 'memory not mapped'

 *** caught segfault ***
address 0xfffffffffffffff8, cause 'memory not mapped'

Traceback:
 1: random_forest_mlpackMain()
 2: random_forest(training = as.matrix(X), labels = as.matrix(as.integer(X[,     1])), print_training_accuracy = TRUE, num_trees = 10, minimum_leaf_size = 3, An irrecoverable exception occurred. R is aborting now ...

 *** caught segfault ***
address 0xfffffffffffffff8, cause 'memory not mapped'

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: random_forest_mlpackMain()
 2: 
 *** caught segfault ***

Traceback:

Traceback:
 1: random_forest_mlpackMain()
 2:  1: 
Traceback:
random_forest(training = as.matrix(X), labels = as.matrix(as.integer(X[,     verbose = TRUE)
Traceback:
address 0xfffffffffffffff0, cause 'memory not mapped'
random_forest(training = as.matrix(X), labels = as.matrix(as.integer(X[,     1])), print_training_accuracy = TRUE, num_trees = 10, minimum_leaf_size = 3,     verbose = TRUE)
An irrecoverable exception occurred. R is aborting now ...

An irrecoverable exception occurred. R is aborting now ...
random_forest_mlpackMain()
 2: random_forest(training = as.matrix(X), labels = as.matrix(as.integer(X[,     1])), print_training_accuracy = TRUE, num_trees = 10, minimum_leaf_size = 3,     verbose = TRUE)    1])), print_training_accuracy = TRUE, num_trees = 10, minimum_leaf_size = 3,     verbose = TRUE)
Traceback:
 1: random_forest_mlpackMain()

An irrecoverable exception occurred. R is aborting now ...

An irrecoverable exception occurred. R is aborting now ...
 2: random_forest(training = as.matrix(X), labels = as.matrix(as.integer(X[,     1])), print_training_accuracy = TRUE, num_trees = 10, minimum_leaf_size = 3,     verbose = TRUE)
An irrecoverable exception occurred. R is aborting now ...
 1: random_forest_mlpackMain()
 2: random_forest(training = as.matrix(X), labels = as.matrix(as.integer(X[,     1])), print_training_accuracy = TRUE, num_trees = 10, minimum_leaf_size = 3,     verbose = TRUE)
 1: random_forest_mlpackMain()
 2: random_forest(training = as.matrix(X), labels = as.matrix(as.integer(X[,     1])), print_training_accuracy = TRUE, num_trees = 10, minimum_leaf_size = 3,     verbose = TRUE)
An irrecoverable exception occurred. R is aborting now ...

Traceback:
An irrecoverable exception occurred. R is aborting now ...
 1: random_forest_mlpackMain()
 2: random_forest(training = as.matrix(X), labels = as.matrix(as.integer(X[,     ])), print_training_accuracy = TRUE, num_trees = 10, minimum_leaf_size = 3,     verbose = TRUE)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault
```

Version 3.4.2.1, installed from CRAN in linux, compiled with gcc10 with options `-O3` and `-march=native`.

**Comment by coatless** [comment] 2021-09-15 17:49
Duplicate of #3021. We have a fix in PR https://github.com/mlpack/mlpack/pull/3034

**Closed** 2021-09-15 18:21 UTC
Labels: t: bug report, s: unanswered
