### ISSUE TITLE
pip installation not working on macOS + instructions a bit unclear

### ISSUE THREAD

**Issue by janek** [mlpack/mlpack#1795] opened 2019-03-19 10:48 UTC
#### Problem location
http://www.mlpack.org/docs/mlpack-3.0.4/doxygen/python_quickstart.html

#### Description of problem
>Installing the mlpack bindings for Python is straightforward. It's easy to use conda or pip to do this:
>`pip install mlpack/mlpack3`

I'm not familiar with the `path-like/syntax` for pip packages, so I wasn't sure if it's a mistake or just a way of expressing that it should be either mlpack or mlpack3.

Anyway, I tried all three possibilities. Two of them do nothing and `pip install mlpack` actually installs something called mlpack 0.1.4 that looks like a very early version of this library. It contains only linear regression and logistic regression.

<img width="865" alt="Screenshot 2019-03-19 at 11 25 50" src="https://user-images.githubusercontent.com/2146927/54600344-d98e8500-4a3c-11e9-9816-a3bd3a495e93.png">
 

If that is indeed a super old version of this library, it should definitely be removed, that's very confusing.

It would be wonderful if mlpack was possible to easily install with `pip`. So far I've spend an hour trying to install it (in any way, including source) - and I've been unsuccessful. I will try to open more issues for the docs later.

Thank you for your work, hope this can get fixed.

**Comment by KimSangYeon-DGU** [comment] 2019-03-21 13:52
Hi @janek, Why don't you use `pip install mlpack3`?

**Comment by janek** [comment] 2019-03-21 14:57
hey, thanks for writing. I have tried it, and it doesn't work (the error message is in the screnshot).

I collected some info in the IRC chat, and if I understand correctly `pip install mlpack3` is actually the correct command. It just doesn't work at the moment on macOS at the moment. 

So what I would strongly suggest to do immediately is to change `pip install mlpack/mlpack3` to `pip install mlpack3` to avoid the confusion that I went through.

And of course, whenever possible, fix the pip installation for mac - but I understand that might be a larger issue/take longer.

**Comment by KimSangYeon-DGU** [comment] 2019-03-21 15:18
I see, can you tried it in Python 3.6? It seems to be related to #1640.

**Comment by KimSangYeon-DGU** [comment] 2019-03-21 15:25
I see, can you tried it in Python 3.6? It seems to be related to #1670. Sorry, if it doesn't work in macOS.

**Comment by rcurtin** [comment] 2019-03-21 15:29
Yeah, we only provide `manylinux` packages which work on Linux, but not OS X.  So it won't work there.  In any case though, @janek is right that the documentation is wrong and should be changed.

**Comment by janek** [comment] 2019-03-21 16:36
Understandable. Thanks for responding and for your approach!

**Comment by rcurtin** [comment] 2019-06-30 16:47
Hey @janek, it took a while to get everything set up.  But now, we have the mlpack/mlpack-wheels repository, which we can use with Travis to build pip packages for mlpack for both OS X and manylinux.  Take a look, now mlpack 3.1.1 is uploaded and available: https://pypi.org/project/mlpack3/

It's very easy to trigger these builds and make it part of the release pipeline, so you can expect these to remain up-to-date.  In addition, it's possible to use the mlpack-wheels repository to provide Windows packages.  But for now we are still debugging the Windows Python bindings in #1872, so once we get that working then we can automate the release of Windows packages via PyPI.

Anyway, thanks for the report!  I'll go ahead and close this now because I believe the issue is fixed.  Let me know if there are any problems.

**Closed by rcurtin** 2019-06-30 16:47 UTC
Labels: c: documentation, t: bug report

**Comment by janek** [comment] 2019-07-01 11:04
Looks good! Thanks a lot @rcurtin!
