### ISSUE TITLE
Python binding warnings are inaccurate or misleading

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1118] opened 2017-09-13 14:46 UTC
The warnings in bindings to other languages are generally written for command-line programs; example:

```
>>> o = logistic_regression(training=x, labels=y, lambda_=0.5)
[WARN ] --output_file ignored because --test_file is not specified.
[WARN ] --output_probabilities_file ignored because --test_file is not specified.
```

but neither of those warnings make very much sense.  We need a way to write generic error or warning messages that can be automatically reformatted for the language at hand.

**Comment by craterkamath** [comment] 2017-09-23 14:26
Hey!! I would like to work on this issue. Can this be assigned to me? I am new to mlpack and might need a little bit if help to get started

**Comment by zoq** [comment] 2017-09-24 10:29
Hello, @craterkamath your help is greatly appreciated, so feel free to work on the issue and let us know if you need any help.

Btw. Github doesn't support assigning issues to outside contributors, but anyone interested in this issue should read the conversation and see that the issue is taken up.

**Comment by rcurtin** [comment] 2017-09-24 10:40
Actually sorry I have been working on this one. I should have assigned it to myself.

**Closed** 2017-12-09 08:52 UTC
Labels: P: minor, T: defect
