### ISSUE TITLE
hdf5.h file not found

### ISSUE THREAD

**Issue by MichaelChai** [mlpack/mlpack#1069] opened 2017-07-21 07:33 UTC
When I enter make, the following error occurs:

In file included from /usr/local/include/armadillo:83:
/usr/local/include/armadillo_bits/include_hdf5.hpp:26:14: fatal error: 
      '/usr/local/Cellar/hdf5/1.10.1/include/hdf5.h' file not found
    #include ARMA_INCFILE_WRAP(ARMA_HDF5_HEADER)
             ^
/usr/local/include/armadillo_bits/compiler_setup.hpp:66:30: note: expanded from
      macro 'ARMA_INCFILE_WRAP'
#define ARMA_INCFILE_WRAP(x) <x>

This is the same when I enter make install.

mlpack 2.2.3, cmake version 3.8.2.
My system is macOS 10.12.5.

**Comment by zoq** [comment] 2017-07-21 09:50
Hello, have you install armadillo using brew with hdf5 support?

``brew install armadillo --with-hdf5``

**Comment by MichaelChai** [comment] 2017-07-21 09:54
I installed the hdf5 version is 1.10.1_1, make the default path is 1.10.1, how can we downgrade?

**Comment by zoq** [comment] 2017-07-21 10:00
I'm not sure what you mean by " 1.10.1_1, make the default path is 1.10.1", did you install armadillo via brew and later on updated hdf5?

**Comment by MichaelChai** [comment] 2017-07-21 10:05
Yes, the latest version of hdf5 is 1.10.1_1, my file path is /usr/local/Cellar/hdf5/1.10.1_1/include/hdf5.h, but make the path is / usr / local / Cellar / hdf5 /1.10.1/include/hdf5.h

**Comment by zoq** [comment] 2017-07-21 10:08
Could you reinstall the armadillo package? ``brew reinstall ...``

**Comment by MichaelChai** [comment] 2017-07-21 10:13
Reinstall the hdf5 version is also 1.10.1_1, when I enter cd mlpack-2.2.3 / build, and then make install, search path and the path of my folder is inconsistent.

**Comment by zoq** [comment] 2017-07-21 10:25
Can you remove the mlpack build folder and rerun ``cmake`` and post the output here?

**Comment by MichaelChai** [comment] 2017-07-21 10:31
bogon:~ ElinCredit$ cd /Users/ElinCredit/Downloads/mlpack-2.2.3 
bogon:mlpack-2.2.3 ElinCredit$ mkdir build
bogon:mlpack-2.2.3 ElinCredit$ cd build
bogon:build ElinCredit$ cmake ../
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Armadillo: /usr/local/lib/libarmadillo.dylib (found suitable version "7.950.1", minimum required is "4.200.0") 
-- Armadillo libraries: /usr/local/lib/libarmadillo.dylib
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   program_options
--   unit_test_framework
--   serialization
-- Try OpenMP C flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- Found Git: /usr/bin/git (found version "2.11.0 (Apple Git-81)") 
-- Regenerating arma_config.hpp.
CMake Warning (dev) at src/mlpack/methods/neighbor_search/CMakeLists.txt:37 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_knn".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/mlpack/methods/neighbor_search/CMakeLists.txt:45 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_kfn".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/mlpack/methods/rann/CMakeLists.txt:42 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_krann".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Warning at CMakeLists.txt:442 (message):
  txt2man not found; man pages will not be generated.


-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   mlpack

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/ElinCredit/Downloads/mlpack-2.2.3/build
bogon:build ElinCredit$ make
Scanning dependencies of target mlpack_arma_config
[  0%] Updating arma_config.hpp (if necessary)
-- Regenerating arma_config.hpp.
[  0%] Built target mlpack_arma_config
Scanning dependencies of target mlpack_headers
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
Scanning dependencies of target mlpack
[  0%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/load_csv.cpp.o
In file included from /Users/ElinCredit/Downloads/mlpack-2.2.3/src/mlpack/core/data/load_csv.cpp:12:
In file included from /Users/ElinCredit/Downloads/mlpack-2.2.3/src/mlpack/core/data/load_csv.hpp:18:
In file included from /Users/ElinCredit/Downloads/mlpack-2.2.3/src/mlpack/../mlpack/core.hpp:218:
In file included from /Users/ElinCredit/Downloads/mlpack-2.2.3/src/mlpack/../mlpack/prereqs.hpp:79:
In file included from /Users/ElinCredit/Downloads/mlpack-2.2.3/src/mlpack/../mlpack/core/arma_extend/arma_extend.hpp:52:
In file included from /usr/local/include/armadillo:83:
/usr/local/include/armadillo_bits/include_hdf5.hpp:26:14: fatal error: 
      '/usr/local/Cellar/hdf5/1.10.1/include/hdf5.h' file not found
    #include ARMA_INCFILE_WRAP(ARMA_HDF5_HEADER)
             ^
/usr/local/include/armadillo_bits/compiler_setup.hpp:66:30: note: expanded from
      macro 'ARMA_INCFILE_WRAP'
#define ARMA_INCFILE_WRAP(x) <x>
                             ^
1 error generated.
make[2]: *** [src/mlpack/CMakeFiles/mlpack.dir/core/data/load_csv.cpp.o] Error 1
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] Error 2
make: *** [all] Error 2

**Comment by zoq** [comment] 2017-07-21 11:05
Strange, not sure why armadillo isn't picking up the correct version; I guess what we could do here is to remove every hdf5 package which is a armadillo dependency:

on my system ``ls /usr/local/Cellar/hdf5/`` returns ``1.10.1_1 1.8.16_1 1.8.17 1.8.18``

so, I did ``brew remove hdf5`` or ``brew uninstall --ignore-dependencies hdf5`` to uninstall the packages, afterwards I reinstalled armadillo.

**Comment by zoq** [comment] 2017-07-21 11:05
ah, I need to install hdf5 first.

**Comment by zoq** [comment] 2017-07-21 11:11
or, wait, I think I can reproduce your problem...

**Comment by MichaelChai** [comment] 2017-07-21 11:13
I tried `brew uninstall hdf5`, suggesting that `error`, so now you can use it?

**Comment by zoq** [comment] 2017-07-21 11:29
It looks like since hdf5 was migrate from homebrew/science/ to brew core you will run into some problems, I'll have to take a closer look into the issue, for now I just created a symlink:

``ln -s /usr/local/Cellar/hdf5/1.10.1_1 /usr/local/Cellar/hdf5/1.10.1`` to get it working.

**Comment by MichaelChai** [comment] 2017-07-21 11:32
OK, thank you !

**Comment by rcurtin** [comment] 2017-08-15 20:06
I think this issue is solved, so I'll close it.  If that's not correct, let me know, we can reopen it. :)

**Closed by rcurtin** 2017-08-15 20:06 UTC

**Comment by seewishnew** [comment] 2019-03-21 01:44
Hey guys, I was facing a similar issue just today on my MBP. This was my problem: 
```
dyld: Library not loaded: @rpath/libhdf5.101.dylib
  Referenced from: /usr/local/lib/libarmadillo.9.dylib
  Reason: image not found
Abort trap: 6
```
This came up when I was trying to use mlpack's executable files. At first, I did not realize that this message was also being spat out while I was executing make in the build directory (this is for the latest git master branch version of mlpack). 

I tried the following hack out, and it seems to have resolved the issue: 
```
sudo ln -s /usr/local/lib/libhdf5.103.dylib /usr/local/lib/libhdf5.101.dylib
```

I just wanted to mention this somewhere so that someone else facing this might find this hacky solution. I also want to note that the following: 
>ln -s /usr/local/Cellar/hdf5/1.10.1_1 /usr/local/Cellar/hdf5/1.10.1 

does not fix this issue. 

I have a question: is there any way to fix this instead of sym-linking the newer version of hdf5 to an older version?

**Comment by rcurtin** [comment] 2019-03-21 01:48
Hey @seewishnew, probably best to open a new issue for this one, but I'm willing to bet that the system HDF5 version got updated but the version of Armadillo did not.  I suspect reinstalling (or rebuilding) Armadillo could fix the issue.  Anyway, if that doesn't work, feel free to open another issue for it. :+1:

**Comment by seewishnew** [comment] 2019-03-21 02:02
I did try uninstalling and then reinstalling armadillo using brew multiple times. I am using armadillo version 9.200.7_1 right now btw. But that still caused the issue. 

Also, 
> brew install armadillo --with-hdf5 

does not work. It produces an error that says that there is no option ```--with-hdf5``` 

I'll open a new issue for this one then @rcurtin .

**Comment by karlzhang-hhg** [comment] 2019-03-21 20:56
Hi,

I also have this problem as following.

dyld: Library not loaded: @rpath/libhdf5.101.dylib
  Referenced from: /usr/local/lib/libarmadillo.9.dylib
  Reason: Incompatible library version: libarmadillo.9.dylib requires version 103.0.0 or later, but libhdf5.101.dylib provides version 102.0.0

And the following command doesn't work for me either.

**Comment by karlzhang-hhg** [comment] 2019-03-21 20:56
brew install armadillo --with-hdf5

I am using IOS.

**Comment by rcurtin** [comment] 2019-03-21 20:58
This is starting to sound like a Homebrew packaging issue; has anyone checked with the Armadillo maintainers there?

**Comment by karlzhang-hhg** [comment] 2019-03-21 21:05
> Hey guys, I was facing a similar issue just today on my MBP. This was my problem:
> 
> ```
> dyld: Library not loaded: @rpath/libhdf5.101.dylib
>   Referenced from: /usr/local/lib/libarmadillo.9.dylib
>   Reason: image not found
> Abort trap: 6
> ```
> This came up when I was trying to use mlpack's executable files. At first, I did not realize that this message was also being spat out while I was executing make in the build directory (this is for the latest git master branch version of mlpack).
> 
> I tried the following hack out, and it seems to have resolved the issue:
> 
> ```
> sudo ln -s /usr/local/lib/libhdf5.103.dylib /usr/local/lib/libhdf5.101.dylib
> ```
> I just wanted to mention this somewhere so that someone else facing this might find this hacky solution.
> 
> I also want to note that the following:
> 
> > ln -s /usr/local/Cellar/hdf5/1.10.1_1 /usr/local/Cellar/hdf5/1.10.1
> 
> does not fix this issue.
> 
> I have a question: is there any way to fix this instead of sym-linking the newer version of hdf5 to an older version?

Thanks your hacky way works for me!
