### ISSUE TITLE
Visual C++ Compile error

### ISSUE THREAD

**Issue by theSundayProgrammer** [mlpack/mlpack#483] opened 2015-11-23 00:28 UTC
Method: RSModel::BuildModel
Error:   .\src\mlpack\methods\range_search\rs_model.cpp(72): error C2899: typename can
not be used outside a template declaration

The fix, I think, would be to remove said keyword

**Comment by rcurtin** [comment] 2015-11-23 13:27
Hi there,

I don't have a setup to reproduce this.  If you'd like this fixed, could you please test that fix and provide a pull request?  Once you do that, I can test the fix on Linux (with gcc and clang) and then we can merge it in.

Thanks!

**Comment by theSundayProgrammer** [comment] 2015-11-24 00:11
I have implemented it and put it in my own fork https://github.com/theSundayProgrammer/mlpack.git and it works.

The change is simple: just remove the keyword 'typename' from rs_model.cpp.

**Comment by rcurtin** [comment] 2015-11-24 16:41
Yep, I merged in your commit.  Thanks!  Do you mind if I add your name/email to the list of contributors?

Also, it looks like your git configuration is a little off; your commits have the email 'joe.mariadassou@gmail.cvom' (I amended this in each of the commits I cherry-picked from your fork to be 'gmail.com').

**Closed by rcurtin** 2015-11-24 16:41 UTC
Labels: T: defect

**Comment by theSundayProgrammer** [comment] 2015-11-24 18:42
I will honoured to be in the list of contributors.
II am not sure why github uses the wrong email address. My Profile is
correct.

On Wed, Nov 25, 2015 at 3:41 AM, Ryan Curtin <notifications@github.com>
wrote:

> Closed #483 <https://github.com/mlpack/mlpack/issues/483>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mlpack/mlpack/issues/483#event-473506686>.
>



-- 
Joseph Chakravarti Mariadassou
http://thesundayprogrammer.com

**Comment by rcurtin** [comment] 2015-11-24 18:54
Sure, added in 4f97fdf.

Your Github profile is just fine -- I think the issue is with your git configuration on the system you are using to develop.
