### ISSUE TITLE
mlpack_test failing due to Ann_layer_test.cpp failure

### ISSUE THREAD

**Issue by jeffin143** [mlpack/mlpack#1803] opened 2019-03-21 12:51 UTC
#### Mlpack_test failing due to ann_layer_test.cpp failure GradientTransposedConvolutionLayerTest is failing due to some reason

Commenting out ann_layer_test.cpp from cmake and building it again works fine 

Do take travis cl log once for last five pr,all build are failing 

error
bin/mlpack_test: symbol lookup error: bin/mlpack_test: undefined symbol: _ZN6mlpack9BacktraceC1Ei

#### Your environment

 * operating system: ubuntu 18.04
 
#### Steps to reproduce
make mlpack_test doesn't build completely

**Comment by ShikharJ** [comment] 2019-03-21 13:16
Did you happen to run a `make clean` and then run `make`? I'm unable to reproduce this error, and I don't think the nightly builds are failing either. Please provide a link to the Travis logs where the failure is occuring?

**Comment by jeffin143** [comment] 2019-03-21 14:17
@ShikharJ  

https://travis-ci.org/mlpack/mlpack/jobs/509277029

https://travis-ci.org/mlpack/mlpack/jobs/509334075

**Comment by KimSangYeon-DGU** [comment] 2019-03-21 14:47
@jeffin143, This issue ralated to #1777. Actually, we have kept tack of where the source of the issue is. And the current  `GradientTransposedConvolutionLayerTest` is measure to decrease the error rate.

@ShikharJ, Should we increase the number of trials, until we find the source of the problem?

**Comment by jeffin143** [comment] 2019-03-21 15:09
@KimSangYeon-DGU yeah, i am also in search to find the source of problem.

**Comment by ShikharJ** [comment] 2019-03-21 16:45
@KimSangYeon-DGU I don't see how that would help. Five trials is more than enough in my opinion. The error seems to be limited to Mac OS builds, which have had a problem with these tests since the time we started building on OSX.

**Comment by ShikharJ** [comment] 2019-03-21 16:48
Closing this for now, this needs to be handled in #1661.

**Closed by ShikharJ** 2019-03-21 16:48 UTC
Labels: t: bug report
