### ISSUE TITLE
How to process Categorical Features (Encode with OneHot Encoding) in Hoeffding Tree Example?

### ISSUE THREAD

**Issue by DylanWangWQF** [mlpack/mlpack#3041] opened 2021-08-24 00:49 UTC
Hi, Team!
I have some synthetic datasets. That is, all features are categorical and encoded under one-hot encoding.
In this case, how can I process such a dataset (not arff) using the Hoeffding Tree Algorithm?

Dataset example (50000 samples with 31 features, each feature has two categorical values, like _Sunny_ and _Rainy_):
```
1 0 0 1 0 1 1 0 0 1 1 0 1 0 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 1 0
1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 0 1 0 1 0 1 1 0 1
1 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 1
0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 0 0 1 1 0 0 1 0 1 1 0 0 1 1 0 0
1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 1
1 0 0 1 0 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 1 0 1 0 0 1 0
0 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 0 1 1 0 0 1 1 0 1 0 1 0 0 1 0
1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 1 0 1 1
1 0 1 0 0 1 0 1 0 1 1 0 1 0 0 1 1 0 0 1 0 1 0 1 0 1 0 1 0 1 1
0 1 0 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 1 0 1 0 1 0
1 0 0 1 1 0 1 0 0 1 1 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 1 0
1 0 1 0 0 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 1 0 0
......
```

We can only take `.arff` as training dataset?
```
$ mlpack_hoeffding_tree --training_file dataset.arff --confidence 0.99
  --output_model_file tree.bin
```
@rcurtin  Could you give me some suggestions? Thanks in advance

**Comment by DylanWangWQF** [comment] 2021-08-24 04:19
We can only take `.arff` as training dataset?
```
$ mlpack_hoeffding_tree --training_file dataset.arff --confidence 0.99
  --output_model_file tree.bin
```

**Comment by DylanWangWQF** [comment] 2021-08-24 07:32
@rcurtin  Could you give me some suggestions? Thanks in advance

**Comment by heisenbuug** [comment] 2021-08-24 09:29
I think you can load `csv` as well. Take a look at [2-d categorical matrix file](https://www.mlpack.org/doc/stable/cli_documentation.html#overview) in `data_format` section.

**Comment by DylanWangWQF** [comment] 2021-08-24 10:26
@heisenbuug  Many thanks for your help!
As mentioned in [2-d categorical matrix file](https://www.mlpack.org/doc/stable/cli_documentation.html#data-formats), _When using this format, there is no need for one-hot encoding of categorical data._

But my synthetic dataset is already processed with one-hot encoding, so I have to transform it into other formats, like strings?

**Comment by heisenbuug** [comment] 2021-08-24 12:50
I think you can.
So basically mlpack uses `DatasetMapper` class to map the strings to numbers.

```
1,2,3,T
4,5,6,F
7,8,9,T
```
Something like this will be converted to 
```
1,2,3,0
4,5,6,1
7,8,9,0
```
```
T mapped to 0
F mapped to 1
This info is stored in a `DatasetMapper` object.
```
And in my understanding, your data is something like this only, right?
Basically, all columns were `categorial`, so they got converted to `0 or 1` respectively?

If that's the case then I think you can use this data directly.

**Comment by DylanWangWQF** [comment] 2021-08-24 13:06
@heisenbuug 
> Can you send me the link to the original dataset?

Sure, e.g., this is one of my datasets, 10000 data samples, 7 features. All features are `categorial`and each feature has 2 values, and we have two classes.
In this case, the generated data would be 
```
att1  attr2   att3   att4   att5   att6   att7   label
0 1      1 0       0 1     1 0     0 1     1 0     1 0       0
```
[10000_7.txt](https://github.com/mlpack/mlpack/files/7039315/10000_7.txt)
To upload here, I change `.dat` into `.txt`.

In fact, this is an example in the case of each feature has two values, it can be 3 or more, like this (one-hot encoding):
```
att1     att2
001      010
```

In case it's necessary, this is the python scripts for generating datasets:
```
#!/usr/bin/env python3

import os
from skmultiflow.data.random_tree_generator import RandomTreeGenerator

num_sample = 10000
seed = 42
delim = ' '
output_filename = f'{seed}.dat'

# Setting up the stream
# max_tree_depth=6, min_leaf_depth=2
stream = RandomTreeGenerator(
            tree_random_state=seed,
            n_classes=2,
            n_cat_features=7,
            n_num_features=0,
            n_categories_per_cat_feature=2,
            max_tree_depth=6,
            min_leaf_depth=2,
            fraction_leaves_per_level=0.15)

print(f'generating {output_filename}...')

with open(output_filename, 'w') as out:
    for _ in range(num_sample):
        X, y = stream.next_sample()

        out.write(delim.join(str(int(v)) for v in X[0]))
        out.write(f'{delim}{int(y[0])}')
        out.write('\n')
```

**Comment by heisenbuug** [comment] 2021-08-24 13:19
For a quick solution, I would suggest converting it to `csv` where it will have values like true/false so that
`DatasetMapper` can handle it. But this will only work when you have strings.

If you have integers as categories then you need to tell the `DatasetMapper` object specifically which columns are categorical?

Just to be clear, the txt file you sent is already one-hot encoded, right?

**Comment by DylanWangWQF** [comment] 2021-08-24 13:24
> For a quick solution, I would suggest converting it to csv where it will have values like true/false so that
DatasetMapper can handle it. But this will only work when you have strings.

> Just to be clear, the txt file you sent is already one-hot encoded, right?

The data generated by the python scripts are already one-hot encoded (So I don't have strings). 
So If I convert it to CSV, I have to replace the one-hot encoded bits with strings. Maybe it's trivial.

**Comment by DylanWangWQF** [comment] 2021-08-24 13:27
The script directly outputs the one-hot encoded bits (no matter `categorical` values are integers or strings).

**Comment by heisenbuug** [comment] 2021-08-24 13:29
Okay, I see...
This is how one-hot encoding works in mlpack.
```
Given a set of labels of a particular datatype, convert them to binary
vector. The categorical values be mapped to integer values.
Then, each integer value is represented as a binary vector that is
all zero values except the index of the integer, which is marked
with a 1.
```

So I think you need to convert the data to this form to make it work.
You can use [this](https://scikit-multiflow.readthedocs.io/en/stable/api/generated/skmultiflow.transform.OneHotToCategorical.html) to convert them back?

**Comment by DylanWangWQF** [comment] 2021-08-24 13:39
Yes, it should work, I will have a try.

**Comment by heisenbuug** [comment] 2021-08-24 13:43
Yup after that I think it should work, as it will assign strings.

You can use [this](https://github.com/mlpack/examples/blob/62526e824cf446f4c8bcebb4e4b6d8550b7e83bb/avocado_price_prediction_with_linear_regression/avocado_price_prediction_with_lr_cpp.ipynb) link for reference.

See *cell [10]* specifically for setting type to categorical.

**Comment by DylanWangWQF** [comment] 2021-08-24 13:49
Wow, this is useful, many thanks for your help!

**Comment by heisenbuug** [comment] 2021-08-24 14:22
Yup, I hope your issue is resolved.

**Comment by DylanWangWQF** [comment] 2021-08-24 23:02
Hi @heisenbuug 
I have another question.
In [mlpack/src/mlpack/methods/hoeffding_trees/categorical_split_info.hpp](https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/hoeffding_trees/categorical_split_info.hpp). we have this definition:
```
  template<typename eT>
  static size_t CalculateDirection(const eT& value)
  {
    // We have a child for each categorical value, and value should be in the
    // range [0, categories).
    return size_t(value);
  }
```
In  [mlpack/src/mlpack/methods/hoeffding_trees/hoeffding_categorical_split_impl.hpp](https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/hoeffding_trees/hoeffding_categorical_split_impl.hpp):
```
void HoeffdingCategoricalSplit<FitnessFunction>::Train(eT value, const size_t label)
```
Then in [mlpack/src/mlpack/methods/hoeffding_trees/hoeffding_tree_impl.hpp](https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/hoeffding_trees/hoeffding_tree_impl.hpp), we invoke the functions in two places:
```
//! Train on one point.
Train(const VecType& point, const size_t label)
{
     categoricalSplits[categoricalIndex++].Train(point[i], label);
}

size_t direction = CalculateDirection(point);
children[direction]->Train(point, label);

```

**My question**: What's the type of `VecType& point` and `eT& value`?
```
//! The type of vector we are using.
  typedef typename MatType::vec_type   VecType;
```
Why can we pass the parameters like: `Train(point, label)` , `Train(point[i], label);` and `CalculateDirection(point)`?
For example,  `CalculateDirection(point)` ----> Definition: `static size_t CalculateDirection(const eT& value)`.
Since there are many `template<typename XXXX>`, I didn't find details in the documentation.

**Comment by heisenbuug** [comment] 2021-08-25 04:42
You don't need to specify template parameters explicitly.
The compiler does template parameter deduction itself.

`VecType& point` here VecType can be anything that represents a 1-D array, it can be an `arma::rowvec` or `arma::colvec` mostly.
Same with `eT`(element type).

If you say pass `Train(2, ...)` then `eT` is deduced as `int`
If you pass `Train(2.4, ...)` then `eT` is `double`

It should be a 1-D  array so you can try printing its first element like this `std::cout << rowvec(index)`

**Comment by DylanWangWQF** [comment] 2021-08-25 04:46
OK, I'm modifying the code to do something, I  cannot use `arma` in the program due to some reasons. So I replaced them.

**Comment by heisenbuug** [comment] 2021-08-25 04:48
What are you using? It can be any type of 1-D array. As long as accessing of elements follow same syntax.

**Comment by DylanWangWQF** [comment] 2021-08-25 04:49
I'm using the matrix operations under `NTL` library since other procedures are written with `NTL`.  I have to be consistent

**Comment by heisenbuug** [comment] 2021-08-25 04:55
Templates give us the ability to handle multiple data types at the same time.
But all types should support the operations we perform on them.

Can you share the code and error? It might get a better understanding.

**Comment by DylanWangWQF** [comment] 2021-08-25 05:00
Sry for leading to misunderstanding, I didn't encounter any error.
What I'm doing is to replace the `arma` library in `Mlpack` with 3-rd party `NTL` library.
The previous question is because I didn't understand the `VecType& point`.

**Comment by heisenbuug** [comment] 2021-08-25 05:06
Oh, you can pass a whole col of `NTL matrix` to `Train` and I think it should work.

See [here](https://github.com/mlpack/mlpack/blob/7c99839e516536ed61b9218b5d4dcefa880e4c91/src/mlpack/methods/hoeffding_trees/hoeffding_tree_impl.hpp#L959).
We are passing `data.col(i)` which is basically the whole col of the `matrix data`, [here].(http://arma.sourceforge.net/docs.html#submat)

You need to check `NTL's` documentation to see how to access it.

**Comment by DylanWangWQF** [comment] 2021-08-25 05:13
Many thanks for your suggestions!
This is really helpful!
> A row can be accessed as M[i], indexing from 0, or as M(i), indexing from 1.
@DylanWangWQF see on this page. It's the same syntax. It should work already.

This is similar to `arma`. It saves me much time! Thanks!

**Comment by DylanWangWQF** [comment] 2021-08-25 09:16
@heisenbuug 
Sry for my noise, I have already modified the code. 
Does Mlpack provide the function for printing the tree?

**Comment by heisenbuug** [comment] 2021-08-25 10:24
I don't see any specific fucntion in [`hoeffding_tree.hpp`](https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/hoeffding_trees/hoeffding_tree.hpp) for printing so I think we don't have any. I will update if I find anything.

**Comment by DylanWangWQF** [comment] 2021-08-25 10:27
Yeah, I only found one function for recording the total number of nodes. `HoeffdingTree::NumDescendants()`
BTW, I modified the code with `NTL`, at least it runs successfully. I'm trying to print the tree or do something to check the tree.

**Comment by heisenbuug** [comment] 2021-08-25 10:34
Good to hear that it's working as intended.
Templates although increases the development time but it can do wonders, just as in your case.

I am not sure how you can take a look at the tree, you might be able to come up with a logic based on existing fucntions to parse the tree.

**Comment by DylanWangWQF** [comment] 2021-08-25 10:38
Yes, currently, it seems that no function helps us do it. 
Many thanks for your help!

**Comment by heisenbuug** [comment] 2021-08-25 10:40
Whenever solved don't hesitate in closing the issue.
Thank you.

**Closed** 2021-09-13 08:23 UTC
Labels: s: unanswered, s: unlabeled
