### ISSUE TITLE
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

### ISSUE THREAD

**Issue by Nimishkhurana** [mlpack/mlpack#1710] opened 2019-02-07 11:53 UTC
#### Issue description

```
>>>import pandas as pd
>>> import numpy as np
>>> import mlpack
>>> 
>>> df = pd.read_csv('housingdata.csv',header=None)
>>> 
>>> X = df.iloc[:,5]
>>> y = df.iloc[:,13]
>>> 
>>> output= mlpack.linear_regression(X,y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mlpack/linear_regression.pyx", line 119, in mlpack.linear_regression.linear_regression
  File "/home/nimish/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 1121, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
>>> X = pd.DataFrame(X)
>>> y = pd.DataFrame(y)
>>> output= mlpack.linear_regression(X,y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mlpack/linear_regression.pyx", line 119, in mlpack.linear_regression.linear_regression
  File "/home/nimish/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 1121, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

#### Your environment

 * version of mlpack:3.0.4
 * operating system:Ubuntu

I have build mlpack from source.

**Comment by bhavya01** [comment] 2019-02-07 16:07
Hi @Nimishkhurana 
It seems that there is an issue in the ordering of parameters to the function in the generated binding
I looked at the generated binding for linear regresssion in build/src/mlpack/bindings/python/mlpack/linear_regression.py and tried this
```
output = mlpack.linear_regression(training=X, training_output=y)
```
This solves the ValueError but is throwing a segmentation fault for me.

**Comment by Nimishkhurana** [comment] 2019-02-07 16:16
@bhavya01 I also tried the same you said and goit segmentation fault.
Also if I try to run this in jupyter-notebook then kernel keeps on dying again and again.

**Comment by bhavya01** [comment] 2019-02-07 17:12
I am quiet sure that this has to do with the type of the parameter training_response in the file src/mlpack/methods/linear_regression_main.cpp
The function to_matrix return a nested array whereas the pyx file tries to convert it into a row

**Comment by rcurtin** [comment] 2019-02-09 19:54
@Nimishkhurana thanks for the bug report.  We actually have two issues here:

**1. The Python bindings aren't giving good output when keyword parameters aren't used.**  Take a look at the signature of `linear_regression` in `linear_regression.pyx`:

```
def linear_regression(copy_all_inputs=False,
                      input_model=None,
                      lambda_=None,
                      test=None,
                      training=None,
                      training_responses=None,
                      verbose=False):
```

(Note that that file is autogenerated, so if you want to see this file, build mlpack Python bindings with `make python` then look under your build directory in `src/mlpack/bindings/python/mlpack/` for `linear_regression.pyx`.)

So if you call `linear_regression(X, y)`, then this is equivalent to writing `linear_regression(copy_all_inputs=X, input_model=y)`, which doesn't make sense and crashes.  So you should be able to run `linear_regression(training=X, training_responses=y)` and this should work (note that the fix from #1700 is required for a Pandas Series to work right, so you should be using the git master branch too).

The right way to fix this in the codebase is to generate checks for the type of each input parameter.  So, for `copy_all_inputs` the code to handle it in `linear_regression.pyx` is:

```
if copy_all_inputs:
    SetParam[bool](<const string> 'copy_all_inputs', copy_all_inputs)
    CLI.SetPassed(<const string> 'copy_all_inputs')
```

but what we really want is

```
if isinstance(copy_all_inputs, bool):
  if copy_all_inputs:
    SetParam[bool](<const string> 'copy_all_inputs', copy_all_inputs)
    CLI.SetPassed(<const string> 'copy_all_inputs')
else:
  raise TypeError("copy_all_inputs must have type 'bool'!")
```

Fixing this will require a bit of understanding of the automatic bindings system.  The file `src/mlpack/bindings/python/print_pyx.cpp` is the file that actually generates the pyx, and internally it will call the function `PrintInputProcessing()` in `src/mlpack/bindings/python/print_input_processing.hpp`.  We should just need to update the code in that file to make the type check, and then users will get much better output.

(Bonus: it might also be nice to detect when the user didn't pass any keyword arguments and have a warning.  But I think this may make the signature hard to read.)

**2. When a 1-d ndarray is expected but a 2-d ndarray is passed, it segfaults.**  Try the following code:

```
import mlpack
import pandas as pd
import numpy as np

d = pd.read_csv("/home/ryan/datasets/corel.csv")
X = (d.iloc[:, 1:5])
y = (d.iloc[:, 6])

output = mlpack.linear_regression(training=X, training_responses=y,
    verbose=True)
```

That fails with a segfault.  (If you don't have #1700 on your branch, you'll need to manually convert `X` and `y` to `ndarray` with `np.array(d.iloc[:, 1:5])` or similar.)  But, if we change `training_responses=y` to `training_responses=np.array(y).flatten()`, it succeeds!  The issue is that `y` has 2-dimensional shape `(N, 1)` but `np.array(y).flatten()` has 1-dimensional shape `(N,)`.  (N is the size of whatever CSV you use for this.  Anything will work for demonstration.)

I believe this is because the function `numpy_to_row_d()`, found in `src/mlpack/bindings/python/mlpack/arma_numpy.pyx` expects a `numpy.ndarray[numpy.double_t, ndim=1]`, but we are passing one with `ndim=2`.  So either we need another overload, or we need to make sure in the code that calls `numpy_to_row_d()` (or `numpy_to_col_d()` or `numpy_to_row_s()` or `numpy_to_col_s()`)---which is generated also in `print_input_processing.hpp`---first checks that the given numpy matrix is a vector, then calls `flatten()`.  So now we get generated code from `PrintInputProcessing()` for `training_responses` like

```
if training_responses is not None:
    training_responses_tuple = to_matrix(training_responses, dtype=np.double, copy=CLI.HasParam('copy_all_inputs'))
    training_responses_mat = arma_numpy.numpy_to_row_d(training_responses_tuple[0], training_responses_tuple[1])
    SetParam[arma.Row[double]](<const string> 'training_responses', dereference(training_responses_mat))
    CLI.SetPassed(<const string> 'training_responses')
    del training_responses_mat
```

but maybe what we need (in addition to type checking as mentioned in the first point) is something like

```
if training_responses is not None:
    training_responses_tuple = to_matrix(training_responses, dtype=np.double, copy=CLI.HasParam('copy_all_inputs'))
    if len(training_responses_tuple[0].shape) > 1:
      #
      # TODO: size checking here.  Ensure only one dimension of the shape is greater than 1,
      # and call ravel() or flatten() (whichever doesn't copy) to make it one-dimensional.
      #
    training_responses_mat = arma_numpy.numpy_to_row_d(training_responses_tuple[0], training_responses_tuple[1])
    SetParam[arma.Row[double]](<const string> 'training_responses', dereference(training_responses_mat))
    CLI.SetPassed(<const string> 'training_responses')
    del training_responses_mat
```

I've written so much detail here in the hopes that it helps someone who is interested in the automatic bindings system contribute and solve the bug.  If not I will solve it when I have time, but that may be a little while from now. :)  @mirraaj @Yashwants19 maybe you might be interested in these also?

**Comment by rcurtin** [comment] 2019-02-09 19:55
> The function to_matrix return a nested array whereas the pyx file tries to convert it into a row

@bhavya01 exactly, maybe the idea I wrote above (for the second point) can help fix this.  There could be other ideas too, I just proposed one. :+1:

**Comment by Yashwants19** [comment] 2019-02-10 02:43
Hi @rcurtin i want to work on this problem.

**Comment by Nimishkhurana** [comment] 2019-02-10 06:01
Hi @rcurtin I myself want to work on this issue

**Comment by Yashwants19** [comment] 2019-02-10 06:12
Hi @Nimishkhurana i m working on this issue #1711

**Comment by rcurtin** [comment] 2019-02-15 19:21
@Nimishkurana @Yashwants19 there are multiple things to solve in this issue.  From my perspective I'm interested in merging the first fully working solution, so you are both welcome to work on part of it.  But note that #1717 is already open which is already pretty close for the `copy_all_inputs` option type, so probably best not to open another PR for that specific part.  If you guys want to work out which parts of this you want to work on, please feel free.

**Comment by Nimishkhurana** [comment] 2019-02-15 20:40
Thanks @rcurtin. If #1717 is already opened . @Yashwants19 , let me work on second point  i.e. check the dimensions of input and make the target feature one dimensional if it is not so.

**Comment by rcurtin** [comment] 2019-05-17 01:27
I forgot to close this issue, but with #1717 and #1711 merged, I believe these problems to be solved.  Thanks again for reporting the issue. :+1:

**Closed by rcurtin** 2019-05-17 01:27 UTC
Labels: c: automatic bindings, good first issue, help wanted, t: bug report
