### ISSUE TITLE
Problem with LARS to satisfy optimality (KKT) conditions 

### ISSUE THREAD

**Issue by gscarella** [mlpack/mlpack#3442] opened 2023-03-09 10:49 UTC
Hello

#### Issue description

Problems with LARS to satisfy optimality (KKT) conditions 

In some examples, it seems to me that mlpack Lars solver doesn't find a correct solution.
Optimality conditions are not satisfied and there are differences in numerical precision and also sometimes in the Active Set when comparing with another solvers.

#### My environment

 * mlpack version: 4.0.1
 * operating system: Ubuntu 20
 * compiler: g++ 9.4.0
 * version of dependencies: armadillo  9.900.5, cereal 1.3.2, ensmallen 2.17.0
 * environment configured with mlpack conda environment 

#### Steps to reproduce

The attached code [testLars.cpp](https://github.com/mlpack/mlpack/files/10930568/testLars.cpp.txt) , once compiled and run, reproduces some examples using mlpack Lars solver and shows the obtained solutions and the ones obtained with another solver (R lars solver).
We see some differences between the solutions (not in the first test, but in the ones after): there are differences in numerical precision and also in the Active Set which could be sometimes problematic.
In the code, at the end of each example, there is also a call to an own function ckecking if a solution verifies KKT conditions.
Some solutions found by mlpack using Lars solver don't satisfy optimality (KKT) conditions.
_examples.bin_ file [examples.bin](https://github.com/mlpack/mlpack/files/10930552/examples.bin.txt) contains matrices of covariates X, matrices of responses y and R lars package solutions.
Matrices of covariates I use are always upper triangular matrices.

#### Expected behavior

For each example, solution found by mlpack using Lars solver should satisfy KKT conditions and be close to the one of R lars solver.

#### Actual behavior

In the list of tested examples, example/test 1 is ok but the other ones are not: they show differences with R lars solver solutions and they don't satisfy optimality (KKT) conditions.

Thanks for your help

**Comment by rcurtin** [comment] 2023-03-17 18:44
Thanks for the clear bug report. It may be a handful of days but I will try and figure out what is going on here. Note that while in theory LARS can give the exactly correct solution, implementation details could cause the KKT conditions to remain unsatisfied, or could make the optimizer get stuck somewhere. This could be true for the R implementation too.

Anyway, I haven't dug into the problem at all yet, so what I wrote above may not apply, but I at least wanted to point it out.

**Comment by rcurtin** [comment] 2023-04-26 21:06
Hey @gscarella, sorry that this took so long for me to return to.  I used your example and indeed it reproduces the problem.  While digging into what might be wrong, I noticed that the mlpack LARS implementation does not mean-center the responses (or fit an intercept!).  I am wondering if this might be the cause of the difference between the R and the mlpack solutions.

If I add the line

```
y -= arma::mean(y);
```

before calling `Train()` on the model, I find that mlpack passes the KKT conditions for all 10 tests.  (I did not verify However, the R fit does not (I did not look into why yet).  Can I ask what happens if you mean-center the responses for R?

Clearly at the very least the LARS class needs to be modified to fit an intercept also, but I am not yet sure if the problems go any deeper than that.

Thanks again for the clear reproducible example. :+1:

**Comment by gscarella** [comment] 2023-05-05 10:05
Hello @rcurtin,
Thanks for your reply
I confirm your test: centering the response, one gets the correct solution with the LARS solver in mlpack.
And it works with R lars package for both cases, with mean-centered and non mean-centered responses (solution changes when response is mean-centered)

Here is the new version of the test using mlpack [testLars_V2.cpp](https://github.com/mlpack/mlpack/files/11405116/testLars_V2.cpp.txt)  with [examples_V2.bin](https://github.com/mlpack/mlpack/files/11405117/examples_V2.bin.txt)

But my goal is to get a solution to the Lasso problem for any general response, mean-centered or not.
For a non mean-centered response, it's not easy for me (I'm not an expert) to transform the problem into a mean-centered one and to recover the solution to the initial problem.
What is a bit surprising for me is that LARS solver most of the time gives the correct solution  even with a non centered response (here it's the case in the first test and I had made other tests before)
Thanks again

**Comment by rcurtin** [comment] 2023-06-01 20:39
Based on our discussion, I added support for fitting an intercept and also for normalizing the data to LARS in #3493.  But it turned out this was not sufficient: there was indeed a bug in the LARS implementation itself.  I detailed it in #3493, and adapted your tests to the mlpack test suite.  What's a little amusing is that I once implemented LARS in Julia, came across this exact issue (two features need to be added at the same time/step size should be zero), then completely forgot about that until today.  Had I remembered I probably could have saved us both a lot of time... :smile: 

Anyway, I think this will fix the issue.  If you have any more diabolical test cases that break mlpack's implementations please do send them... it is great to work out issues like this!

**Comment by conradsnicta** [comment] 2023-06-10 16:14
Resolved in #3493

**Closed by conradsnicta** 2023-06-10 16:14 UTC
Labels: t: bug report

**Comment by gscarella** [comment] 2023-06-14 06:34
Thanks @rcurtin for your work!
I didn't have time to test the fix but I'll let you know if there's a problem.
