### ISSUE TITLE
Sample code on Hyperparameter tuning is not working.

### ISSUE THREAD

**Issue by aadi-raj** [mlpack/mlpack#3353] opened 2023-01-08 14:50 UTC
### What am I trying to accomplish?

On [link](https://www.mlpack.org/doc/mlpack-3.0.4/doxygen/hpt.html), the sample code given on hyperparameter tuning:

`// 100-point 5-dimensional random dataset.
arma::mat data = arma::randu(5, 100);
// Noisy responses retrieved by a random linear transformation of data.
arma::rowvec responses = arma::randu(5) * data + 0.1 * arma::randn(100);
// Using 80% of data for training and remaining 20% for assessing MSE.
double validationSize = 0.2;
HyperParameterTuner hpt(validationSize, data, responses);
// Finding a good value for lambda from the discrete set of values 0.0, 0.001,
// 0.01, 0.1, and 1.0.
arma::vec lambdas{0.0, 0.001, 0.01, 0.1, 1.0};
double bestLambda;
std::tie(bestLambda) = hpt.Optimize(lambdas);
`

### Expected output:
bestLambda is obtained out of given set of values.

### What is the output?

> terminate called after throwing an instance of 'std::logic_error'
  what():  matrix multiplication: incompatible matrix dimensions: 5x1 and 5x100
Aborted (core dumped)

Thanks in advance for responding.

**Comment by rcurtin** [comment] 2023-01-09 15:58
You're looking at an older version of that documentation (the link you gave is for mlpack 3.0.4).  Here's the updated version: https://github.com/mlpack/mlpack/blob/master/doc/user/hpt.md

Specifically, your line

```
arma::rowvec responses = arma::randu(5) * data + (0.1 * arma::randn(100));
```

should be changed to

```
arma::rowvec responses = arma::randu<arma::rowvec>(5) * data + (0.1 * arma::randn<arma::rowvec>(100));
```

Sorry for the inconvenience in the documentation!  If you used Google to find that documentation, Google has no idea about the different versions of mlpack and may link to some old version.  We're in the (slow) process of figuring out how to restructure our documentation so that doesn't happen.

**Comment by rcurtin** [comment] 2023-01-24 17:13
I think the issue is solved here, so I'll go ahead and close this issue---but if I missed something and if there is still something to do, we can reopen it. :+1:

**Closed by rcurtin** 2023-01-24 17:13 UTC
Labels: t: bug report, c: documentation
