### ISSUE TITLE
Segmentation Fault: 11 while training

### ISSUE THREAD

**Issue by sharmaster96** [mlpack/mlpack#980] opened 2017-04-07 22:12 UTC
Hello!

I'm trying to train a dataset using mlpack's collaborative filtering library, but I'm getting a segmentation fault whenever the program tries to generate recommendations. Here's the output I'm getting:

[INFO ] AMF converged to residue of 9.46205e-06 in 57 iterations.
[INFO ] Loading 'query.csv' as raw ASCII formatted data.  Size is 25976 x 1.
[INFO ] Generating recommendations for 25976 users in 'query.csv'.
Segmentation fault: 11

Reading through another bug thread linked here: https://github.com/mlpack/mlpack/issues/431
it seems the issue is with my version of Armadillo, but I've been unable to fix it so far. Any advice/recommendations on what might be causing the segfault?

Thank you!

**Comment by rcurtin** [comment] 2017-04-10 14:42
Hi there,

Can you post the command you used to get the problem, and the version of your OS and the version of mlpack?  Then I can try to reproduce it and figure out what the issue is.

Thanks!

**Comment by sharmaster96** [comment] 2017-04-18 04:36
Hey,

The command I'm running is the following:
mlpack_cf -q -m cf-model.xml -A -o recommendations.csv -v

My OS is OSX El Capitan Version 10.11.1, and my version of mlpack is 2.2.0.

mlpack simply doesn't seem to recognize the --all_user_recommendations flag for some reason, then segfaults immediately afterwards. I've tried just using an input query file instead, and this has the same issue.

Thanks!

**Comment by rcurtin** [comment] 2017-04-18 13:31
Are you sure that is the right command?  `-q` needs an argument.  If you are indeed using an input model with `-m cf-model.xml`, can you tell me how you created that model?  That way I can try and reproduce the error.

**Comment by sharmaster96** [comment] 2017-04-18 20:45
Sorry, typo on my end. Here's the actual command I'm running:
mlpack_cf -m cf-model.xml -o recommendations.csv -v -A

I generated the model by running the standard command from the tutorial:
mlpack_cf -t train.csv -M cf-model.xml -v

I'm not entirely sure what revision b104523 is, that was simply the output when I added the -V tag when I ran the collaborative filtering binary. Thanks!

**Comment by rcurtin** [comment] 2017-04-19 15:04
Three things to check:

 * Are you sure you haven't modified the mlpack code and committed to git?  The revision b104523 doesn't exist anywhere in the repository.  Maybe you cloned not from mlpack/mlpack but from someone's personal branch?

 * Is there another copy of mlpack present on your system?  i.e. did you do `apt-get install libmlpack-dev`, then also clone and build from source?  Sometimes this can cause problems.  If there is a stray `libmlpack.so` of the wrong version in `/usr/local/lib/` or `/usr/lib/` then it can be accidentally loaded instead of the correct `libmlpack.so` and cause problems.

 * In the first post, you were using a file `query.csv`, but you are saying that the problem occurs whether you use `-q query.csv` or `-A`?

Next, what is the format of your `train.csv` file?  Is it possible to share that file?  I am wondering if maybe the model-building process is filling `cf-model.xml` with NaNs or something like this.  If you can give the full output when you ran each command that would be helpful too.

**Comment by rcurtin** [comment] 2017-05-23 21:18
Closing for inactivity.  If you would still like to work out this issue, I am happy to help---just follow up and I'll reopen the ticket.

**Closed by rcurtin** 2017-05-23 21:18 UTC
