### ISSUE TITLE
bug in ccov() due to use of internal armadillo classes

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#1849] opened 2019-04-08 07:11 UTC
The `ccov()` function in `mlpack/src/mlpack/core/arma_extend/fn_ccov.hpp` uses internal armadillo classes: `Op` and `Glue`:
https://github.com/mlpack/mlpack/blob/3ad649c7f780abf87193859732f866f2119093ac/src/mlpack/core/arma_extend/fn_ccov.hpp#L8
https://github.com/mlpack/mlpack/blob/3ad649c7f780abf87193859732f866f2119093ac/src/mlpack/core/arma_extend/fn_ccov.hpp#L22

In armadillo 9.400 (under development) these classes are changed, resulting in the following errors when compiling mlpack:

    /usr/include/armadillo_bits/Op_bones.hpp:53:21: error: no class template named ‘traits’ in ‘class arma::op_ccov’

`op_ccov` is defined by mlpack in `src/mlpack/core/arma_extend/op_ccov_proto.hpp`.

I suggest rewriting both forms of `ccov()` so that the functions output a matrix instead of `Op` or `Glue`. When compiling with a C++11 compiler, Armadillo will automatically use the move constructor in the `Mat` class, so the performance impact will be minimal.

The internal `Op` and `Glue` classes are subject to change, as per the [API policy](http://arma.sourceforge.net/docs.html#api_additions).

**Comment by chandramoulirajagopalan** [comment] 2019-04-08 11:32
Can I work on this issue?

**Comment by conradsnicta** [comment] 2019-04-08 12:01
@chandramoulirajagopalan - I'd suggest that it's better to finish one PR properly (ie. your work on https://github.com/mlpack/mlpack/issues/1840), and then look at making another one. You seem to be working too fast, which can lead to easy mistakes.

**Comment by conradsnicta** [comment] 2019-04-08 14:49
@rcurtin I'm too busy make a proper PR, so here is the next best thing.
Attached is `ccov.txt` (because GitHub won't let me attach .hpp files): [ccov.txt](https://github.com/mlpack/mlpack/files/3054801/ccov.txt)
The code is an adapted form of `core/arma_extend/*ccov*.hpp` so that it doesn't use internal armadillo functionality.

The file should be renamed to `ccov.hpp` and placed into `src/mlpack/core/math/`. Then throughout the mlpack codebase, all uses of `arma::ccov(X)` should then be replaced with `mlpack::math::ccov(X)`.

Feel free to adapt, change, etc. License is 3-clause BSD license.

Alternatively, all occurrences of `arma::ccov(X)` could be simply replaced by `arma::cov(trans(X))`. I don't think the extra transpose will make much of a difference.

**Comment by jeffin143** [comment] 2019-04-08 16:45
@conradsnicta , I tried doing what you said, throws up an error

` No rule to make target '../src/mlpack/core/arma_extend/fn_ccov.hpp', needed by 'src/mlpack/cotire/mlpack_CXX_prefix.hxx.gch`

**Comment by jeffin143** [comment] 2019-04-08 16:49
> @conradsnicta , I tried doing what you said, throws up an error
> 
> ` No rule to make target '../src/mlpack/core/arma_extend/fn_ccov.hpp', needed by 'src/mlpack/cotire/mlpack_CXX_prefix.hxx.gch`

resolved

**Comment by rcurtin** [comment] 2019-04-12 03:43
@conradsnicta thanks for the report, sorry for the slow response on my end.  Originally when I wrote this (...eight years ago??) the goal was to eventually submit it as a patch to you to add.  I think that you didn't want to include it, which is fine, so we just piggybacked it here and then it got a bit forgotten about.

I think it's not necessary to hook it up to the whole delayed evaluation infrastructure, so the patch you wrote in #1856 works as a quick change for now.  However, since we're looking to release very soon, we actually don't need to patch the 3.0.x branch but we can patch master directly.

#1855, which effectively just moves it into mlpack-specific functionality, is fine with me, so I think that's the better way to go here.

> Alternatively, all occurrences of arma::ccov(X) could be simply replaced by arma::cov(trans(X)). I don't think the extra transpose will make much of a difference.

I see what you're saying, but the reason we originally avoided doing that was the extra RAM usage needed to do the transpose.  Asymptotically speaking, the operation `X*X^T` for `X` of size `d x n` takes `O(nd^2)` time whereas a transpose takes `O(nd)` time (and we'll be doing that twice).  Allocating the extra memory for that limits the maximum size that we can do this operation on, and `d` often may not be very large at all---it may be, e.g., around 10 for a linear regression task.  In this case the overhead may be non-negligible.

It seems like it would be possible for `arma::cov()` to detect when it's given a transposed matrix and act accordingly, but I don't think that support is actually there.  (And I also don't think it's worth the effort to make that happen just for this issue.)  If you did want to add the support, we can switch what we're doing on our end, but totally up to you.

**Comment by conradsnicta** [comment] 2019-04-12 06:08
If I recall correctly, I wasn't entirely convinced that incorporating a specialisation for `cov(trans(X))` was worth it, at least when looking from a speed point of view. Transpose is pretty quick, as it's essentially a glorified copy operation. The most time consuming operation inside the `cov()` function is the matrix multiplication, which should take far longer than applying the transpose on the input matrix.

However, I agree with the point that doing the transpose on the input matrix increases memory use, so we can certainly provide an optimisation for that.  There are clear use cases for doing `cov(trans(X))` in the mlpack code base.  You're welcome to submit a pull request, otherwise I'll try to implement it when I have free time.  Perhaps this would make `mlpack::math::ccov()` redundant ?

**Comment by conradsnicta** [comment] 2019-04-12 06:09
@rcurtin If I recall correctly, I wasn't entirely convinced that incorporating a specialisation for `cov(trans(X))` was worth it, at least when looking from a speed point of view. Transpose is pretty quick, as it's essentially a glorified copy operation. The most time consuming operation inside the `cov()` function is the matrix multiplication, which should take far longer than applying the transpose on the input matrix.

However, I agree with the point that doing the transpose on the input matrix increases memory use, so we can certainly provide an optimisation for that.  There are clear use cases for doing `cov(trans(X))` in the mlpack code base.  You're welcome to submit a pull request, otherwise I'll try to implement it when I have free time.  Perhaps this would make `mlpack::math::ccov()` redundant ?

**Comment by rcurtin** [comment] 2019-04-12 17:06
Right, transpose is quick, but for the use case I'm considering, the cost of `X * trans(X)` is going to be similar.

If you're willing to accept a patch for `cov(trans(X))` I think that would be great, and then on our end since we try to support older versions of Armadillo, we'll use `#if ARMA_VERSION < (what we need)`, then just hijack the `cov(trans(X))` call to call out to our internal `ccov()` function (that will use internal Armadillo functionality, but at least we know that the internal Armadillo code cannot change since we are only 'modifying' old code).  That way we can update our codebase to always call `cov(trans(X))` instead, and we can finally ditch our `ccov()` function when we increase our minimum version enough.

I don't think I'll have time soon to implement `cov(trans(X))` but I don't think we need to hurry---we have a workaround solution for now via #1855/#1856.

**Comment by rcurtin** [comment] 2019-04-23 17:30
Fixed via #1855.  A patch for `cov(trans(X))` may come eventually but I don't consider it too high priority right now.

**Closed by rcurtin** 2019-04-23 17:30 UTC
Labels: c: core, t: bug report
