### ISSUE TITLE
Errors while buidling mlpack-2.1.1

### ISSUE THREAD

**Issue by CorpaciLC** [mlpack/mlpack#852] opened 2017-01-17 23:38 UTC
Hello!
I received some errors when doing this tutorial: https://github.com/mlpack/mlpack
Whent running mlpack_test I get these:

Running 717 test cases...
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(37):          fatal error in "HammingLossBoundIris": Cannot load test dataset iris.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(77):          fatal error in "WeakLearnerErrorIris": Cannot load test dataset iris.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(125):          fatal error in "HammingLossBoundVertebralColumn": Cannot load test dataset vc2.         csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(163):          fatal error in "WeakLearnerErrorVertebralColumn": Cannot load test dataset vc2.         csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(210):          fatal error in "HammingLossBoundNonLinearSepData": Cannot load test dataset tra         in_nonlinsep.txt!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(248):          fatal error in "WeakLearnerErrorNonLinearSepData": Cannot load test dataset tra         in_nonlinsep.txt!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(295):          fatal error in "HammingLossIris_DS": Cannot load test dataset iris.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(334):          fatal error in "WeakLearnerErrorIris_DS": Cannot load test dataset iris.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(386):          fatal error in "HammingLossBoundVertebralColumn_DS": Cannot load test dataset v         c2.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(427):          fatal error in "WeakLearnerErrorVertebralColumn_DS": Cannot load test dataset v         c2.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(475):          fatal error in "HammingLossBoundNonLinearSepData_DS": Cannot load test dataset          train_nonlinsep.txt!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(516):          fatal error in "WeakLearnerErrorNonLinearSepData_DS": Cannot load test dataset          train_nonlinsep.txt!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(565):          fatal error in "ClassifyTest_VERTEBRALCOL": Cannot load test dataset vc2.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(616):          fatal error in "ClassifyTest_NONLINSEP": Cannot load test dataset train_nonlins         ep.txt!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(668):          fatal error in "ClassifyTest_IRIS": Cannot load test dataset iris_train.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/adaboost_test.cpp(715):          fatal error in "TrainTest": Cannot load test dataset iris_train.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/akfn_test.cpp(36): fata         l error in "ApproxVsExact1": Cannot load test dataset test_data_3_1000.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/akfn_test.cpp(89): fata         l error in "ApproxVsExact2": Cannot load test dataset test_data_3_1000.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/akfn_test.cpp(116): fat         al error in "SingleTreeVsExact": Cannot load test dataset test_data_3_1000.csv!
unknown location(0): fatal error in "DualCoverTreeTest": std::invalid_argument:          requested value of k (15) is greater than the number of points in the reference          set (0)
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/akfn_test.cpp(159): las         t checkpoint
unknown location(0): fatal error in "DualBallTreeTest": std::invalid_argument: r         equested value of k (15) is greater than the number of points in the reference s         et (0)
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/akfn_test.cpp(216): las         t checkpoint
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/aknn_test.cpp(39): fata         l error in "ApproxVsExact1": Cannot load test dataset test_data_3_1000.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/aknn_test.cpp(92): fata         l error in "ApproxVsExact2": Cannot load test dataset test_data_3_1000.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/aknn_test.cpp(119): fat         al error in "SingleTreeApproxVsExact": Cannot load test dataset test_data_3_1000         .csv!
unknown location(0): fatal error in "DualCoverTreeTest": std::invalid_argument:          requested value of k (15) is greater than the number of points in the reference          set (0)
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/aknn_test.cpp(162): las         t checkpoint
unknown location(0): fatal error in "DualBallTreeTest": std::invalid_argument: r         equested value of k (15) is greater than the number of points in the reference s         et (0)
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/aknn_test.cpp(216): las         t checkpoint

error: pinv(): svd failed
unknown location(0): fatal error in "CFGetRecommendationsAllUsersTest": std::run         time_error: pinv(): svd failed
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/binarize_test.cpp(68):          last checkpoint
unknown location(0): fatal error in "CFGetRecommendationsQueriedUserTest": std::         runtime_error: Timer::Start(): timer 'cf_factorization' has already been started
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/binarize_test.cpp(68):          last checkpoint
unknown location(0): fatal error in "RecommendationAccuracyTest": std::runtime_e         rror: Timer::Start(): timer 'cf_factorization' has already been started
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/binarize_test.cpp(68):          last checkpoint
unknown location(0): fatal error in "CFPredictTest": std::runtime_error: Timer::         Start(): timer 'cf_factorization' has already been started
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/binarize_test.cpp(68):          last checkpoint
unknown location(0): fatal error in "CFBatchPredictTest": std::runtime_error: Ti         mer::Start(): timer 'cf_factorization' has already been started
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/binarize_test.cpp(68):          last checkpoint
unknown location(0): fatal error in "TrainTest": std::runtime_error: Timer::Star         t(): timer 'cf_factorization' has already been started
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/binarize_test.cpp(68):          last checkpoint
unknown location(0): fatal error in "EmptyConstructorTrainTest": std::runtime_er         ror: Timer::Start(): timer 'cf_factorization' has already been started
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/binarize_test.cpp(68):          last checkpoint
unknown location(0): fatal error in "SerializationTest": std::runtime_error: Tim         er::Start(): timer 'cf_factorization' has already been started
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/binarize_test.cpp(68):          last checkpoint
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/emst_test.cpp(195): fat         al error in "DualTreeVsNaive": Cannot load test dataset test_data_3_1000.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/emst_test.cpp(231): fat         al error in "CoverTreeTest": Cannot load test dataset test_data_3_1000.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/emst_test.cpp(260): fat         al error in "BallTreeTest": Cannot load test dataset test_data_3_1000.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/kfn_test.cpp(342): fatal error in "DualTreeVsNaive1": Cannot load test dataset test_data_3_1000.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/kfn_test.cpp(376): fatal error in "DualTreeVsNaive2": Cannot load test dataset test_data_3_1000.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/kfn_test.cpp(410): fatal error in "SingleTreeVsNaive": Cannot load test dataset test_data_3_1000.csv!
unknown location(0): fatal error in "DualCoverTreeTest": std::invalid_argument: requested value of k (5) is greater than the number of points in the reference set (0)
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/kfn_test.cpp(462): last checkpoint
unknown location(0): fatal error in "DualBallTreeTest": std::invalid_argument: requested value of k (5) is greater than the number of points in the reference set (0)
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/kfn_test.cpp(534): last checkpoint
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/kmeans_test.cpp(666): fatal error in "DTNNCoverTreeTest": critical check assignments[i] == dtnnAssignments[i] failed [2 != 1]
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/knn_test.cpp(670): fatal error in "DualTreeVsNaive1": Cannot load test dataset test_data_3_1000.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/knn_test.cpp(704): fatal error in "DualTreeVsNaive2": Cannot load test dataset test_data_3_1000.csv!
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/knn_test.cpp(739): fatal error in "SingleTreeVsNaive": Cannot load test dataset test_data_3_1000.csv!
unknown location(0): fatal error in "DualCoverTreeTest": std::invalid_argument: requested value of k (5) is greater than the number of points in the reference set (0)
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/knn_test.cpp(791): last checkpoint
unknown location(0): fatal error in "DualBallTreeTest": std::invalid_argument: requested value of k (5) is greater than the number of points in the reference set (0)
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/knn_test.cpp(862): last checkpoint
[FATAL] Cannot open file 'rann_test_r_3_900.csv'.

unknown location(0): fatal error in "NaiveGuaranteeTest": std::runtime_error: fatal error; see Log::Fatal output
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/knn_test.cpp(1276): last checkpoint
[FATAL] Cannot open file 'rann_test_r_3_900.csv'.

unknown location(0): fatal error in "SingleTreeSearch": std::runtime_error: fatal error; see Log::Fatal output
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/knn_test.cpp(1276): last checkpoint
[FATAL] Cannot open file 'rann_test_r_3_900.csv'.

unknown location(0): fatal error in "DualTreeSearch": std::runtime_error: fatal error; see Log::Fatal output
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/knn_test.cpp(1276): last checkpoint
[FATAL] Cannot open file 'rann_test_r_3_900.csv'.

unknown location(0): fatal error in "SingleCoverTreeTest": std::runtime_error: fatal error; see Log::Fatal output
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/krann_search_test.cpp(271): last checkpoint
[FATAL] Cannot open file 'rann_test_r_3_900.csv'.

unknown location(0): fatal error in "DualCoverTreeTest": std::runtime_error: fatal error; see Log::Fatal output
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/krann_search_test.cpp(271): last checkpoint
[FATAL] Cannot open file 'rann_test_r_3_900.csv'.

unknown location(0): fatal error in "RAModelTest": std::runtime_error: fatal error; see Log::Fatal output
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/krann_search_test.cpp(616): last checkpoint
unknown location(0): fatal error in "TestWhitenUsingEig": memory access violation at address: 0x00000000: no mapping at fault address
/home/student/MLPACK-2.1.1/mlpack-2.1.1/src/mlpack/tests/lin_alg_test.cpp(78): last checkpoint

*** 55 failures detected in test suite "mlpackTest"

**Comment by rcurtin** [comment] 2017-01-17 23:45
Hi there,

Did you run the test in the same directory where you built the library?

**Comment by CorpaciLC** [comment] 2017-01-18 12:19
Yes, but I got some errors when building too.

**Comment by rcurtin** [comment] 2017-01-18 13:52
OK, unfortunately there isn't really enough information for me to provide any other pointers here. Can you tell me exactly what you did and wgat your setup is so I can try to reproduce the issue? Thanks.

**Comment by CorpaciLC** [comment] 2017-01-24 01:10
Hello! Sorry for responding so rare. I'm full of projects and exams these weeks.
I don't remember every error I got, so I tried to redo it all.
Fortunately, I read these lines on time::

"This document discusses how to build mlpack from source. However, mlpack is in the repositories of many Linux distributions and so it may be easier to use the package manager for your system. For example, on Ubuntu, you can install mlpack with the following command:

$ sudo apt-get install libmlpack-dev"

If I give this command, I won't get any errors, but when I tried some of the examples from here: http://www.mlpack.org/docs/mlpack-2.1.1/doxygen.php?doc=sample.html 

Those commands aren't recognised.

I don't know how to make something visible work.
Thank you!

**Comment by rcurtin** [comment] 2017-01-24 02:05
What do you mean?  Do you have a problem compiling the example programs?  If so be sure to link with `-lmlpack`.  If you can provide full output of what you've done and what's failed, I can probably help more.

**Comment by CorpaciLC** [comment] 2017-01-24 09:49
Actually I see that my system doesn't recognize the mlpack commands. 
After this command :
sudo apt-get install libmlpack-dev

 I get:
Reading package lists... Done
Building dependency tree
Reading state information... Done
libmlpack-dev is already the newest version (2.0.1-1).
0 upgraded, 0 newly installed, 0 to remove and 86 not upgraded.

Should I do more to make mlpack functional?

**Comment by CorpaciLC** [comment] 2017-01-24 11:04
I also installed mlpack-bin.

**Comment by CorpaciLC** [comment] 2017-01-24 11:42
Now I am quite unsure about how datasets work. Can you direct me to some link where I can find more details, please?

**Comment by zoq** [comment] 2017-01-24 13:06
The command-line program reference might be helpful: http://www.mlpack.org/docs/mlpack-2.1.1/man.html


> For example, the following will calculate the 5 nearest neighbors of eachpoint in ’input.csv’ and store the distances in ’distances.csv’ and the neighbors in the file ’neighbors.csv’:

```
mlpack_knn --k=5 --reference_file=input.csv --distances_file=distances.csv --neighbors_file=neighbors.csv
```


You could use the iris.csv dataset as input.csv to test the command: https://raw.githubusercontent.com/mlpack/mlpack/master/src/mlpack/tests/data/iris.csv

**Comment by CorpaciLC** [comment] 2017-01-24 13:35
mlpack_knn isn't recognised on my system. It must be installed individually?
This is the list I have in /usr/bin.

mlpack_adaboost
mlpack_allkfn
mlpack_allknn
mlpack_allkrann
mlpack_cf
mlpack_decision_stump
mlpack_det
mlpack_emst
mlpack_fastmks
mlpack_gmm_generate
mlpack_gmm_probability
mlpack_gmm_train
mlpack_hmm_generate
mlpack_hmm_loglik
mlpack_hmm_train
mlpack_hmm_viterbi
mlpack_hoeffding_tree
mlpack_kernel_pca
mlpack_kmeans
mlpack_lars
mlpack_linear_regression
mlpack_local_coordinate_coding
mlpack_logistic_regression
mlpack_lsh
mlpack_mean_shift
mlpack_nbc
mlpack_nca
mlpack_nmf
mlpack_pca
mlpack_perceptron
mlpack_radical
mlpack_range_search
mlpack_softmax_regression
 mlpack_sparse_coding

Have a nice day!

**Comment by rcurtin** [comment] 2017-01-24 14:18
Since mlpack installed on your system is 2.0.1, make sure you are using the documentation for that version:

http://www.mlpack.org/docs/mlpack-2.0.1/doxygen.php?doc=sample.html (i.e. 2.0.1 not 2.1.1)

In 2.1.1, `mlpack_allknn` was changed to `mlpack_knn`.  So you can use the `mlpack_allknn` program instead in 2.0.1.

**Comment by CorpaciLC** [comment] 2017-01-24 16:03
Ok! Thank you!

**Comment by rcurtin** [comment] 2017-01-24 18:12
Great, glad we could help out.  Should we close this issue then, if your problems are resolved?

**Comment by CorpaciLC** [comment] 2017-01-25 00:25
Yes! I will open another one if I have other questions.

**Comment by rcurtin** [comment] 2017-01-25 22:38
Sounds good.

**Closed by rcurtin** 2017-01-25 22:38 UTC
