### ISSUE TITLE
FastMKS (optdigits dataset) segmentation fault

### ISSUE THREAD

**Issue by zoq** [mlpack/mlpack#1767] opened 2019-03-08 15:28 UTC
#### Issue description

``mlpack_fastmks -r optdigits.csv -v  -k 10 -K hyptan`` returns with a segmentation fault.

#### Your environment

 * version of mlpack: git master and 3.0.4, maybe other version as well
 * operating system: FreeBSD, Linux (debian)
 * compiler: probably any gcc version or clang version
 * version of dependencies (Boost/Armadillo): doesn't matter

#### Steps to reproduce

Run ``mlpack_fastmks -r optdigits.csv -v  -k 10 -K hyptan``, you should see that it returns with a segmentation fault, [optdigits](mlpack.org/datasets/optdigits.tar.gz) dataset. The run will only fail if the ``hyptan`` kernel is used and if "-k" is set.

#### Expected behavior

The executable should not fail with a segmentation fault. It should give a similar result as if run with: ``mlpack_fastmks -r optdigits.csv -v  -k 10 -K gaussian``.

#### Actual behavior

Here's some example output:

```bash
[INFO ] Loading 'optdigits.csv' as CSV data.  Size is 65 x 5620.
[INFO ] Loaded reference data (65 x 5620).
[INFO ] 5619 distance computations during tree construction.
zsh: segmentation fault  bin/mlpack_fastmks -r optdigits.csv -v -K hyptan --kernels_file kernels.csv -
```

**Comment by Yashwants19** [comment] 2019-03-08 17:13
Hi @zoq when I was testing fastmks for cli bindings I couldn't pass ` kernel` as `hyptan`. As It leads to tests running forever. But as you see in PR #1765 when I pass `abs()` from `sqrt` in `src/mlpack/core/metrics/ip_metric_impl.hpp` It was start giving correct results.

**Comment by Yashwants19** [comment] 2019-03-09 05:54
Hi @zoq when we run `bin/mlpack_fastmks -r optdigits.csv -v -k 0 -K gaussian` its returns with a segmentation fault.
```
[INFO ] Loading 'optdigits.csv' as CSV data.  Size is 65 x 5620.
[INFO ] Loaded reference data (65 x 5620).
[INFO ] 15789390 distance computations during tree construction.
Segmentation fault (core dumped)
```

**Comment by Yashwants19** [comment] 2019-03-09 06:01
And  when we run `bin/mlpack_fastmks -r optdigits.csv -v -k 10 -K hyptan -S` with single-tree search it give correct result and same with ` --naive` it give correct result

**Comment by zoq** [comment] 2019-03-09 12:49
> Hi @zoq when we run bin/mlpack_fastmks -r optdigits.csv -v -k 0 -K gaussian its returns with a segmentation fault.

I see the same error, if I use ``k = 1`` it does work. Can you reproduce the error with the command I posted above?

**Comment by zoq** [comment] 2019-03-09 12:51
Also, do you test against the mater branch or already against the changes you did in #1765?

**Comment by Yashwants19** [comment] 2019-03-10 03:46
I have tested this with both the master and branch which I have made and got the same error as from master.

**Comment by zoq** [comment] 2019-03-10 19:45
Thanks for the information, I wonder if this is dataset specific.

**Comment by atulim** [comment] 2019-03-19 17:53
@zoq I don't think that it is dataset specific because I tested this module with different datasets.

**Comment by atulim** [comment] 2019-03-19 17:59
> > Hi @zoq when we run bin/mlpack_fastmks -r optdigits.csv -v -k 0 -K gaussian its returns with a segmentation fault.
> 
> I see the same error, if I use `k = 1` it does work. Can you reproduce the error with the command I posted above?

gaussian works correctly in every dataset and taking k as any value.
hyptan doesn't work correctly even taking k = 1

**Comment by zoq** [comment] 2019-03-20 21:22
Thanks for the additional insights, so if this isn't dataset specific, the issue might be in the kernel, I guess a first step could be to step through the code e.g. using gdb.

**Comment by rcurtin** [comment] 2019-04-27 03:45
Oops, this one should stay open.

**Comment by nttruong7** [comment] 2019-06-12 05:35
I run the command successfully
mlpack_fastmks -r optdigits_csv.csv -v -k 10 -K hyptan  --kernels_file kernels.csv
[INFO ] Loading 'optdigits_csv.csv' as CSV data.  Size is 65 x 5621.
[INFO ] Loaded reference data (65 x 5621).
[INFO ] 11239 distance computations during tree construction.
[INFO ] 1579077 base cases.
[INFO ] 1646725 scores.
[INFO ] Saving CSV data to 'kernels.csv'.

my system is Fedora 29

**Comment by rcurtin** [comment] 2019-07-06 17:17
I'm not able to run the command successfully; I suspect the datasets that are being used differ slightly.  I am using `optdigits.csv` from `http://www.mlpack.org/datasets/optdigits.tar.gz` and this produces the error in multiple different versions of mlpack that I checked.

**Comment by nttruong7** [comment] 2019-08-09 23:16
I locate the crash to the candidatesPoints.top() in FastMKSRules<KernelType, TreeType>::CalculateBound(TreeType& queryNode) in fastmks_rules_imp.hpp to be empty.  So candidates vector in FastMKSRules object contains empty CandidateList. Any comment on why?

**Comment by rcurtin** [comment] 2019-08-10 01:01
I think you are right, and I can figure out why if I can reproduce the issue, but I can't reproduce it.  Can you share the dataset you are using that causes the issue?  (and also which version of mlpack you are using; you can get it with `mlpack_fastmks --version`)

**Comment by nttruong7** [comment] 2019-08-10 08:27
I run the 3.1.1 mlpack
The dataset you given above http://www.mlpack.org/datasets/optdigits.tar.gz
The command I run is 
mlpack_fastmks -r optdigits.csv -v -k 0  -K gaussian
I think k 0 parameter seems not right , why would user want 0 kernel? should it be return error immediately?
command mlpack_fastmks -r optdigits.csv -v -k 10 -K hyptan also crash , but at different point

**Comment by rcurtin** [comment] 2019-08-22 13:52
@nttruong7 thanks for the info.  I opened #1986 with a fix for the issue. :+1:

It's worth pointing out that I think we could make the command work on the optdigits dataset if the scale parameter (`--scale`) is chosen to be sufficiently small (maybe 0.001 or much smaller?  I am not sure).  Even so, it did highlight an issue that warrants fixing.

**Comment by rcurtin** [comment] 2019-08-28 22:05
Since #1986 is merged, I think we can close this issue now. :+1:

**Closed by rcurtin** 2019-08-28 22:05 UTC
Labels: c: methods, t: bug report
