### ISSUE TITLE
preprocess_split error , using sample code

### ISSUE THREAD

**Issue by suxiaojack** [mlpack/mlpack#1722] opened 2019-02-18 05:19 UTC
When I try python code like wrote in page
http://mlpack.org/docs/mlpack-3.0.4/doxygen/python_quickstart.html

I save these code in test.py ,and download http://www.mlpack.org/datasets/covertype-small.csv.gz into same dir.
df = pd.read_csv('covertype-small.csv.gz')
but I got the error:
  **File "test.py", line 12, in <module>
    output = mlpack.preprocess_split(input=dataset,input_labels=labels,test_ratio=0.3)
  File "mlpack/preprocess_split.pyx", line 104, in mlpack.preprocess_split.preprocess_split
  File "mlpack/arma_numpy.pyx", line 63, in mlpack.arma_numpy.numpy_to_mat_s
ValueError: Buffer has wrong number of dimensions (expected 2, got 1)**

------------------------------------------
the labels processed fail.
------------------------------------------

print(labels)
0        7
1        2
2        2
3        1
4        1
5        2
6        1
7        2
8        3
9        6
10       2
11       3
12       2
13       1
14       2
15       1
16       1
17       2
18       2
19       2
20       2
21       2
22       1
23       2
24       1
25       2
26       2
27       2
28       5
29       2
        ..
99970    2
99971    1
99972    1
99973    3
99974    1
99975    1
99976    1
99977    1
99978    1
99979    2
99980    2
99981    2
99982    2
99983    1
99984    2
99985    1
99986    1
99987    2
99988    5
99989    2
99990    1
99991    1
99992    1
99993    2
99994    2
99995    1
99996    1
99997    1
99998    1
99999    1
Name: label, Length: 100000, dtype: int64
--------------------------------------------------------
`>>> import mlpack
`>>> X=[[1,2],[2,3]]
`>>> mlpack.preprocess_split(input=X,test_ratio=0.5,verbose=True)
`[INFO ] Training data contains 1 points.
`[INFO ] Test data contains 1 points.
`{'test': array([[1., 2.]]), 'test_labels': array([], shape=(0, 0), dtype=int64), 'training': array([[2., 3.]]), 'training_labels': array([], shape=(0, 0), dtype=int64)}
`>>> y=[4,5]
`>>> mlpack.preprocess_split(input=X,input_labels=y,test_ratio=0.5,verbose=True)
`Traceback (most recent call last):
 ` File "<stdin>", line 1, in <module>
  `File "mlpack/preprocess_split.pyx", line 104, in mlpack.preprocess_split.preprocess_split
  `File "mlpack/arma_numpy.pyx", line 63, in mlpack.arma_numpy.numpy_to_mat_s
`ValueError: Buffer has wrong number of dimensions (expected 2, got 1)
`>>> y=[[4],[5]]
`>>> mlpack.preprocess_split(input=X,input_labels=y,test_ratio=0.5,verbose=True)
`[INFO ] Training data contains 1 points.
`[INFO ] Test data contains 1 points.
`{'test': array([[2., 3.]]), 'test_labels': array([[5]]), 'training': array([[1., 2.]]), 'training_labels': array([[4]])}
`>>> `

**Comment by MuLx10** [comment] 2019-02-18 09:47
@suxiaojack  I guess the `labels` needs reshaping.
`labels = numpy.reshape(labels,(-1,1))`

**Comment by rcurtin** [comment] 2019-02-18 16:37
I think that this is a duplicate of #1710.  Once that is addressed you should be able to pass in a two-dimensional matrix to a one-dimensional parameter.  Until then, @MuLx10's solution should work. :+1:

**Comment by rcurtin** [comment] 2019-05-17 01:27
Since #1710 is solved, this should be solved also.  Thanks again for the report. :+1:

**Closed by rcurtin** 2019-05-17 01:27 UTC
Labels: c: automatic bindings, t: bug report
