### ISSUE TITLE
mlpack_adaboost error

### ISSUE THREAD

**Issue by cypro666** [mlpack/mlpack#821] opened 2016-11-30 10:48 UTC
./mlpack_adaboost -t train.csv -l labels.csv -M model.txt
./mlpack_adaboost -m model.txt -T train.csv -o result.csv

[FATAL] input stream error
terminate called after throwing an instance of 'std::runtime_error'
  what():  fatal error; see Log::Fatal output
Aborted (core dumped)

train.csv : 
2,3
2,3
2,4
1,0
2,3
6,6
7,8
2,3
2,3
2,4
1,0
2,3
6,6
7,8
2,3
2,3
2,4
1,0
2,3
6,6
7,8

lables.csv:
0
0
0
0
0
1
1
0
0
0
0
0
1
1
0
0
0
0
0
1
1

version:
mlpack 2.1.0
boost 1.58.0
blas openblas 2.18

**Comment by rcurtin** [comment] 2016-12-05 02:23
I can reproduce this with both 2.1.0 and git master.  But I found that if you use binary models (i.e. `-M model.bin` and `-m model.bin`) there is no problem and everything seems to work.  Text and XML models fail.  I'll try to look into this in the coming days.

**Comment by cypro666** [comment] 2016-12-05 03:18
Aha， bin format works well ，Thx！ 
Infact bin format makes more efficiency， but sometimes texts get better readability ：）

**Comment by rcurtin** [comment] 2016-12-06 15:15
So the issue here is twofold:

 * The training set you are using can be perfectly modeled by the weak learner in a single iteration of AdaBoost.  But the AdaBoost code does not handle this as well as it could.
 * There is some problem serializing `nan` values in text and binary format.

I have some ideas for how to fix it but at the moment I don't have the time.  If you train on a more difficult dataset, I think that you are not likely to see this problem.  Still, I will fix it when I have a chance! :)

**Comment by nitinkgp23** [comment] 2017-01-14 19:45
Hey Ryan, 

I am a newbie here, and I am in a position of just jumping in and contribute. I wanted to take up this issue, since most of the 'easy'  labelled isues have already been taken up or have been fixed. I will require help from you on how to go ahead with this issue.

**Comment by shikharbhardwaj** [comment] 2017-03-03 14:52
I'll try and isolate this issue if no one else is actively working on it right now.

**Comment by rcurtin** [comment] 2017-03-25 00:59
The Adaboost problem is fixed with #956 being merged (thanks @nish21!).  The nan serialization issue still remains.

**Comment by shikharbhardwaj** [comment] 2017-03-25 14:56
Thanks for the update @rcurtin.
I checked the reported error and cannot replicate it after #956 .

Also, `nan` values are being correctly serialized, as I tested [here](https://gist.github.com/shikharbhardwaj/17ff67075822906d9c8f1260981e60b6).

Is there anything else that needs to be tested?

**Comment by rcurtin** [comment] 2017-03-27 14:12
Ah, so there is a little catch... the test that you've written uses Armadillo's built-in loading/saving functionality.  But the serialization issue occurs when we are using boost::serialization, to serialize models.  Therefore you would need to use the other overload of `data::Load()`, which you could do like this:

```
data::Load("test.bin", "matrix", test);
```

And you could test that with `bin`, `xml`, and `txt` extensions.  From what I can tell with a very quick investigation, `bin` works, but `xml` and `txt` do not.  This may be a boost::serialization issue, but I am not sure.

**Comment by shikharbhardwaj** [comment] 2017-03-27 14:45
I retested and the issue is there.

Turns out `boost::serialization` does not support `nan` or `inf` in the text-based formats. Mailing list discussion : http://lists.boost.org/boost-users/2005/01/9360.php

There are a few workarounds mentioned in the post.

**Comment by rcurtin** [comment] 2017-03-27 14:48
Thanks for looking into that.  It seems that implementing any of these workarounds would take some large amount of effort, and on top of that, any NaNs appearing in mlpack models almost certainly mean something is very wrong.  I can't think of any situation where a NaN would be the correct value.  Thus, I think we can go ahead and close this since the original issue is now solved, and not worry about serializing NaNs correctly.

**Closed by rcurtin** 2017-03-27 14:48 UTC
Labels: D: moderate, P: major, T: defect
