### ISSUE TITLE
Doesn't find /usr/include/stb/stb_image.h

### ISSUE THREAD

**Issue by barak** [mlpack/mlpack#2103] opened 2019-12-03 17:07 UTC
## Issue description

The CMAKE configuration scripts don't notice `/usr/include/stb/stb_image.h` which is where the Debian `libstb-dev` package keeps it.

#### Your environment

 * version of mlpack: 3.2.2
 * operating system: Debian stable & sid

#### Steps to reproduce

Try to build with stb downloading disabled and `libstb-dev` installed and no previous version of `libmlpack-dev` installed (which had the file included due to having been not found and hence downloaded, which is a no-no but let's not get into that, and installed it in `/usr/include/stb_image.h`.)

#### Expected behavior

The build scripts should win at this little game of stb hide-and-seek.

#### Actual behavior

```
-- Could NOT find STB_IMAGE (missing: STB_IMAGE_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:379 (message):
  stb/stb_image.h is not installed.  Image utilities will not be available!
```

**Comment by rcurtin** [comment] 2019-12-03 17:17
Strange.  I know on Fedora we couldn't use the provided STB package because it didn't come with `stb_image_write.h` but on Debian (at least in sid), it does.  If `stb_image_write.h` isn't available in the particular version of `libstb-dev` you are using, that could be the reason.  However, I'm able to reproduce the issue on the sid system I am running, so I'll look into this later today.

By the way you can disable all external downloads during build via `-DDOWNLOAD_ENSMALLEN=OFF -DDOWNLOAD_STB_IMAGE=OFF`.  We're a little bit between a rock and a hard place with this one; packagers (rightfully) say "downloading things means non-reproducible builds" and users say "I don't know how to install these dependencies because they're not available in every package manager", so, we're trying to scratch both itches. :)

**Comment by barak** [comment] 2019-12-03 17:44
In my development repo I'm fixing it with `-DSTB_IMAGE_INCLUDE_DIR=/usr/include/stb` which works fine. So not a pain point for me. But I thought it might be for others.

And yeah, I'm also now using `-DDOWNLOAD_ENSMALLEN=OFF -DDOWNLOAD_STB_IMAGE=OFF` just in case. (The Debian powers-that-be really frown upon network access by packages being autobuilt, in fact the issue got this package removed. And Ubuntu uses technical means to prevent network access in their autobuild chroots.) Maybe it would be sensible to provide a single master switch `-DDOWNLOAD=OFF` that would shut off these as well as any other automatic downloads that might be added in the future?

**Comment by rcurtin** [comment] 2019-12-03 17:58
Sure, I can do that too, I'll wrap it into the PR fix.

Do you mean that the mlpack package just got dumped from bullseye because it tried to download something?  Seems odd to nuke the package instead of opening a bug and fixing it...

**Comment by rcurtin** [comment] 2019-12-03 18:03
Oh, I see, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942393 was just open for a while.  I guess it makes sense, although still I don't get why leaving 3.0.4 in bullseye wouldn't have worked.  Anyway, I'm always happy to help, but I'm not a Debian packager (and not sure I have time to become one), so I'm not sure of a way to keep us informed here of any issues downstream in Debian.

**Comment by rcurtin** [comment] 2019-12-04 05:38
I opened #2104, which should fix the issue. :+1:

**Comment by barak** [comment] 2019-12-04 13:24
> a way to keep us informed here of any issues downstream in Debian

That's my job!

**Comment by rcurtin** [comment] 2019-12-09 15:31
With #2104 merged, I think we can call this one done.  As always please report more if there are more issues. :)

**Closed by rcurtin** 2019-12-09 15:31 UTC
Labels: c: build system, t: bug report
