### ISSUE TITLE
Impossible to build mlpack_test

### ISSUE THREAD

**Issue by mercierc** [mlpack/mlpack#2027] opened 2019-09-20 13:54 UTC
Hello everyone,

 I just cloned the mlpack rep on my computer and I cannot build all the targets from  **make mlpack**, especially mlpack_test and some generate_pyx. (May be it is normal)

For example, here is the final error that I get during the failure of **make mlpack_test** :

```
src/mlpack/tests/CMakeFiles/mlpack_test.dir/build.make:277: recipe for target 'src/mlpack/tests/CMakeFiles/mlpack_test.dir/async_learning_test.cpp.o' failed

make[3]: *** [src/mlpack/tests/CMakeFiles/mlpack_test.dir/async_learning_test.cpp.o] Error 1
CMakeFiles/Makefile2:7610: recipe for target 'src/mlpack/tests/CMakeFiles/mlpack_test.dir/all' failed
make[2]: *** [src/mlpack/tests/CMakeFiles/mlpack_test.dir/all] Error 2
CMakeFiles/Makefile2:7622: recipe for target 'src/mlpack/tests/CMakeFiles/mlpack_test.dir/rule' failed
make[1]: *** [src/mlpack/tests/CMakeFiles/mlpack_test.dir/rule] Error 2
Makefile:2112: recipe for target 'mlpack_test' failed
make: *** [mlpack_test] Error 2
```

I did not modify the mlpack/CMakeLists.txt and the the BUID_TEST option is still set to ON.
If it can help, I don't have any problem from an installation of mlpack-3.1.1 that I made by following the webpage documentation.

I did not find any answer to this problem on the web. If someone know the solution, I would be glad to read it. 
Thank you.

**Comment by rcurtin** [comment] 2019-09-20 15:22
Hey @mercierc, I think I know what the issue is. What version of ensmallen do you have installed?

**Comment by mercierc** [comment] 2019-09-21 10:50
Hi  @rcurtin and thank you for aswering. I built mlpack from the git-hub rep on another computer and it works with ensmallen 2.10, downloaded during the execution of the cmake command. I will keep you informed about the version installed on the concerned computer as soon as I can acces it.

**Comment by rcurtin** [comment] 2019-09-21 15:39
Good to hear.  The concerned computer likely just needs the version of ensmallen 2.10.0 for the git master branch.  I opened #2027 to update the documentation and CMake configuration about the minimum version needs.

**Comment by mercierc** [comment] 2019-09-23 10:58
I started again with the modifications of @rcurtin and it works well.

**Comment by rcurtin** [comment] 2019-09-23 13:18
Great!  I'll go ahead and close this issue then. :+1:

**Closed by rcurtin** 2019-09-23 13:18 UTC
Labels: c: build system, t: bug report
