### ISSUE TITLE
6 failures are detected in the test module "mlpackTest"

### ISSUE THREAD

**Issue by dante2608** [mlpack/mlpack#1634] opened 2019-01-07 14:23 UTC
Dear dev team,

I ran the mlpack_Test and got 6 failures as the result. I known that we can safely ignore the one in GaussianMatrixSensingSDP but i am now sure about the others. 

Please have me to take a look at it,

Thanks,

Last login: Mon Jan  7 08:58:54 on console
Dats-MBP:~ dante_2608$ cd Downloads/
Dats-MBP:Downloads dante_2608$ cd mlpack-3.0.4
Dats-MBP:mlpack-3.0.4 dante_2608$ cd build/
Dats-MBP:build dante_2608$ cmake ../
-- cotire 1.7.10 loaded.
-- Armadillo libraries: /usr/local/lib/libarmadillo.dylib
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   program_options
--   unit_test_framework
--   serialization
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Regenerating arma_config.hpp.
CMake Warning at CMakeLists.txt:425 (message):
  txt2man not found; man pages will not be generated.

-- Found Python: /Library/Frameworks/Python.framework/Versions/2.7/bin/python
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dante_2608/Downloads/mlpack-3.0.4/build
Dats-MBP:build dante_2608$ bin/mlpack_test 
Running 1445 test cases...

warning: solve(): system seems singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 3.93002e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 3.93002e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 3.93002e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 3.93002e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 3.93002e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 3.93002e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 3.93002e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 3.93002e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 3.93002e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 3.93002e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05025e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 2.77556e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.96984e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 3.93002e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.23896e-17); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05025e-17); attempting approx solution
**/Users/dante_2608/Downloads/mlpack-3.0.4/src/mlpack/tests/lrsdp_test.cpp:270: fatal error: in "LRSDPTest/GaussianMatrixSensingSDP": difference{0.00055936} between measurement{0.00023854628409627696} and b(i){0.00023841292538047745} exceeds 0.05%**

warning: solve(): system seems singular (rcond: 1.09722e-17); attempting approx solution

error: eig_sym(): decomposition failed
unknown location:0: fatal error: in "SdpPrimalDualTest/SmallLovaszThetaSdp": std::runtime_error: eig_sym(): decomposition failed
/Users/dante_2608/Downloads/mlpack-3.0.4/src/mlpack/tests/sdp_primal_dual_test.cpp:278: last checkpoint: "SmallLovaszThetaSdp" test entry

warning: solve(): system seems singular (rcond: 1.61004e-18); attempting approx solution

warning: solve(): system seems singular (rcond: 1.61004e-18); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05576e-18); attempting approx solution

warning: solve(): system seems singular (rcond: 1.05576e-18); attempting approx solution

warning: solve(): system seems singular (rcond: 2.582e-18); attempting approx solution

warning: solve(): system seems singular (rcond: 2.582e-18); attempting approx solution

warning: solve(): system seems singular (rcond: 1.74999e-18); attempting approx solution

warning: solve(): system seems singular (rcond: 1.74999e-18); attempting approx solution

warning: solve(): system seems singular (rcond: 3.14713e-18); attempting approx solution

warning: solve(): system seems singular (rcond: 3.14713e-18); attempting approx solution

warning: solve(): system seems singular (rcond: 1.8632e-18); attempting approx solution

warning: solve(): system seems singular (rcond: 1.8632e-18); attempting approx solution
input stream error
**/Users/dante_2608/Downloads/mlpack-3.0.4/src/mlpack/tests/serialization.hpp:235: fatal error: in "SerializationTest/EmptyHoeffdingTreeTest": critical check success == true has failed [false != true]

error: each_row(): incompatible size; expected 1x1, got 1x10
unknown location:0: fatal error: in "SerializationTest/LayerNormSerializationTest": std::logic_error: each_row(): incompatible size; expected 1x1, got 1x10
/Users/dante_2608/Downloads/mlpack-3.0.4/src/mlpack/tests/serialization_test.cpp:1749: last checkpoint: "LayerNormSerializationTest" test entry
** On entry to DLASCL, parameter number  4 had an illegal value
** On entry to DLASCL, parameter number  5 had an illegal value
** On entry to DLASCL, parameter number  4 had an illegal value
** On entry to DLASCL, parameter number  5 had an illegal value
/Users/dante_2608/Downloads/mlpack-3.0.4/src/mlpack/tests/main_tests/preprocess_imputer_test.cpp:76: fatal error: in "PreprocessImputerMainTest/PreprocessImputerDimensionTest": critical check outputData.n_cols == inputSize has failed [0 != 67]
/Users/dante_2608/Downloads/mlpack-3.0.4/src/mlpack/tests/main_tests/preprocess_imputer_test.cpp:143: fatal error: in "PreprocessImputerMainTest/PreprocessImputerListwiseDimensionTest": critical check outputData.n_cols + countNaN == inputSize has failed [26 != 67]**

*** 6 failures are detected in the test module "mlpackTest"
Dats-MBP:build dante_2608$

**Comment by rcurtin** [comment] 2019-01-07 15:20
I think that I've adjusted the tolerance for the `GaussianMatrixSensingSDP` test, so in future releases that shouldn't be an issue.

The others are more concerning though.  I see two "types" of error:

1. Something to do with serialization.  This covers `SerializationTest/LayerNormSerializationTest`, `SerializationTest/EmptyHoeffdingTreeTest`, and possibly `PreprocessImputerMainTest/PreprocessImputerDimensionTest` and `PreprocessImputerMainTest/PreprocessImputerListwiseDimensionTest`.
2. A failed eigendecomposition for `SdpPrimalDualTest/SmallLovaszThetaSdp` test.

I can try and reproduce the second on my system (I think it is a random failure, but we can take steps to mitigate that), but are you willing to help debug the first a bit?  The key is here:

```
 input stream error
```

I've seen that a few times, all on OS X systems, all recently, and it's an error from boost::serialization.  I see you are using version 1.68 on OS X.  Could I ask you to try an older version of Boost and see if the error still occurs?  I am not sure if it is a regression in Boost or what.  The newest version I have in the package repositories is 1.67 (I am on Debian), so I'll try that and see what happens.  I know from the CI tool that 1.66 works (at least on Linux systems), so if you can test 1.66 that would be helpful.

**Comment by rcurtin** [comment] 2019-01-08 16:44
Ok, thanks for looking into that.  So we can rule out Boost version issues as the cause.  If you can try on a Linux system also that would be great.  I have been unable to reproduce the issue on the Linux systems I have, but I might borrow a Macbook tonight to see if I can reproduce it there.

**Comment by dante2608** [comment] 2019-01-11 00:42
HI Ryan,

I have a chance to run a quick test on my friend's computer and it passed successfully. But now when I tried to compiled a simple problem it gave me error. DO you have any idea, I though that include the -lboost_system would have fixed it but it didn't.

Thanks

tom@tom-Ubuntu:~/Downloads/mlpack-3.0.4/build$ g++ -std=c++11 -lboost_system -o test test.cpp -DDEBUG -g -rdynamic -lmlpack
/usr/bin/ld: /tmp/ccKGLhCc.o: undefined reference to symbol '_ZN5boost15program_options29options_description_easy_initclEPKcS3_'
//usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.58.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by zoq** [comment] 2019-01-11 00:46
```
undefined reference to symbol 'ZN5boost15program_options29options_description_easy_initclEPKcS3
```

linking against ``boost_program_options`` should solve the issue, so the build command should look something like:

```
g++ -std=c++11 -lboost_serialization -lboost_program_options -lboost_system -o test test.cpp -DDEBUG -g -rdynamic -lmlpack
```

**Comment by rcurtin** [comment] 2019-01-17 15:02
#1640 is merged, so I'll go ahead and close this now. :+1:

**Closed by rcurtin** 2019-01-17 15:02 UTC
