### ISSUE TITLE
LinearRegression not working on Arch linux 4.6.4.1

### ISSUE THREAD

**Issue by FlavouredGeorge** [mlpack/mlpack#725] opened 2016-07-17 21:22 UTC
Hello, I built mlpack as per instructions here on git-hub and I seem to be able to load files in an out just fine, however, when I tried writing a short and sweet "hello world" linear regression is started throwing SIGILL (Illegal instruction) at me during runtime.

I compile using "g++ -std=c++11 -lmlpack  -larmadillo main.cpp". I also tried running:

mlpack_linear_regression -t iris.csv -r iris_labels.txt -v

The files loaded sucesfully but I was greeted by the same error:

mlpack_linear_regression -t ~/D…” terminated by signal SIGILL (Illegal instruction).

Just to make sure I ran: 
export LD_LIBRARY_PATH=/usr/local/lib/ and mlpack_knn -w/e works just fine. I can also import any components of the library (including the one for lienar regression just fine).

Might this be a system specific bug ? Or something that I have deeply screwed up with my personal system configuration ? Or am I just missing something very obvious ?

**Comment by rcurtin** [comment] 2016-07-18 13:01
Can you tell me how you compiled Armadillo?  `ldd /path/to/libarmadillo.so` might be helpful in debugging what's happened here.  I think the issue is with Armadillo, not mlpack, but as we get more information we will find out. :)

**Comment by FlavouredGeorge** [comment] 2016-07-18 16:07
The output of the command is:

	linux-vdso.so.1 (0x00007fffffff5000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007fdd3ac9d000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007fdd3a463000)
	libarpack.so.2 => /usr/lib/libarpack.so.2 (0x00007fdd3a218000)
	libsuperlu.so.4 => /usr/lib/libsuperlu.so.4 (0x00007fdd39fa5000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fdd39c1e000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fdd3991a000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fdd39703000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fdd39362000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x000055c0dbfbb000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fdd39145000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007fdd38f16000)
	libgfortran.so.3 => /usr/lib/libgfortran.so.3 (0x00007fdd38be6000)
	libmpi_usempif08.so.11 => /usr/lib/openmpi/libmpi_usempif08.so.11 (0x00007fdd389b6000)
	libmpi_usempi_ignore_tkr.so.6 => /usr/lib/openmpi/libmpi_usempi_ignore_tkr.so.6 (0x00007fdd387af000)
	libmpi_mpifh.so.12 => /usr/lib/openmpi/libmpi_mpifh.so.12 (0x00007fdd38557000)
	libmpi.so.12 => /usr/lib/openmpi/libmpi.so.12 (0x00007fdd38273000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fdd3806e000)
	libquadmath.so.0 => /usr/lib/../lib/libquadmath.so.0 (0x00007fdd37e2f000)
	libopen-rte.so.12 => /usr/lib/openmpi/libopen-rte.so.12 (0x00007fdd37bb1000)
	libopen-pal.so.13 => /usr/lib/openmpi/libopen-pal.so.13 (0x00007fdd3790d000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007fdd37705000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007fdd37501000)
	libhwloc.so.5 => /usr/lib/libhwloc.so.5 (0x00007fdd372c6000)
	libnuma.so.1 => /usr/lib/libnuma.so.1 (0x00007fdd370b9000)
	libudev.so.1 => /usr/lib/libudev.so.1 (0x00007fdd37099000)
	libltdl.so.7 => /usr/lib/libltdl.so.7 (0x00007fdd36e8f000)
	libcap.so.2 => /usr/lib/libcap.so.2 (0x00007fdd36c8a000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007fdd36a73000)

But I can make no sense of it whatsoever. I've gotten armadillo directly from the arch linux repositories over at: https://aur.archlinux.org/packages/armadillo/?comments=all and installed it with pacman.

**Comment by rcurtin** [comment] 2016-07-18 17:01
Ok, thanks for the information.  Let's try something simple... can you compile the following program and execute it?

```
#include <armadillo>

using namespace arma;

int main()
{
  mat x = randu<mat>(50, 50);

  vec e = eig_sym(x);
  cout << "Eigenvalues:\n" << e.t();  
}
```

You might have to fix silly problems since I didn't actually compile and test that.  But you should be able to compile with `g++ -std=c++11 test.cpp -larmadillo`.  If that compiles and you run it, do you again encounter a SIGILL?

**Comment by FlavouredGeorge** [comment] 2016-07-18 17:11
Ok, so, it is indeed an issue related to me not installing armadillo properly, so sorry for bothering you with this :/

I got the following error:

In file included from /usr/include/armadillo:81:0,
                 from art.cpp:1:
/usr/include/armadillo_bits/include_atlas.hpp:28:47: fatal error: /usr/include/clapack.h: No such file or directory
       #include ARMA_INCFILE_WRAP(ARMA_CLAPACK)

Which prssumeably means I either fucked something up when installing armadillo lapack

**Comment by FlavouredGeorge** [comment] 2016-07-18 17:17
Ok, so. I installed atlas-lapack from the Arch repos and now both armatdillo and mlpack seem to work just fine... previously I seemed to have had some version of openblas (which atlas-lapack "removed" since they are "conflicting" with each other.... I don't understand how these libraries work)

Anyway, its working now, thank you a lot for helping me figure this out, sorry for wasting your time with an issue that wasn't at all mlpack related

**Comment by rcurtin** [comment] 2016-07-18 17:24
No worries, we are happy to help. :)

I think you said you installed Armadillo via pacman?  Is it possible that you had ATLAS installed at the time you installed Armadillo, but have since removed it?

You can modify your Armadillo configuration in `/usr/include/armadillo_bits/config.hpp` but to be honest it may be the best idea to just remove Armadillo entirely and reinstall (either via pacman or from source).

Armadillo's configuration in `config.hpp` defines which libraries Armadillo tries to use, so if the underlying system changes, then Armadillo needs to be reconfigured.  This may be a bigger issue with the Pacman package that may require some refactoring on the part of the package maintainers...

**Comment by rcurtin** [comment] 2016-07-18 17:25
Ah sorry, I did not see your latest comment.  Glad to hear you have it worked out.  You might consider filing a bug on the Armadillo package or something like this to address the issue that you've had here.  I'll go ahead and close this then.  If you have any further problems, feel free to ask for help. :)

**Closed by rcurtin** 2016-07-18 17:25 UTC
