### ISSUE TITLE
Mlpack4.2.1 for Windows is having issue in training RandomForest over ~7M samples with larger number of trees (ex: 600 trees)

### ISSUE THREAD

**Issue by SrikanthPusarla** [mlpack/mlpack#3595] opened 2024-01-05 09:06 UTC
#### Issue description
Mlpack4.2.1 for Windows is having issue in training RandomForest  over ~7M samples with larger number of trees (600 trees)

It was run successfully only with combination of ~7M samples,  300+ numerical features with ntrees=20 and depth=10. 
Thereafter it is throwing out runtime error “exited with code -1073740791” when ran with more ntrees.
Below is snapshot with ntrees = 50, depth=10 with 7388125 samples and 304 features. 
![image](https://github.com/mlpack/mlpack/assets/39696849/acde1d19-8e2c-43d8-b304-6891bc4948f4)

#### Your environment

 * version of mlpack: 4.2.1
 * operating system: Windows 10
 * compiler: 
 * version of dependencies (Boost/Armadillo): armadillo-12.6.6, cereal-1.3.2, ensmallen-2.21.0
 * any other environment information you think is relevant:

#### Steps to reproduce
Referred example program provided at mlpack-4.2.1\doc\examples\sample-ml-app\sample-ml-app\sample-ml-app.cpp file to train a Random Forest model, Passed data with ~7M records, 304 features, parameters are set to ntress = 50, depth  = 10.

#### Expected behavior
It should train a Random Forest model with the given input data and parameters successfully and create a mode file.

#### Actual behavior

throwing out runtime error “exited with code -1073740791”

**Comment by rcurtin** [comment] 2024-01-05 14:19
Is it possible you are running out of RAM?  I can try to reproduce locally (on Linux) if are able to share a link to the dataset.

**Comment by SrikanthPusarla** [comment] 2024-01-09 10:52
I did see the RAM usage reached max to 96% once training started 
![7m-50trees-taskmanager1-1](https://github.com/mlpack/mlpack/assets/39696849/901db4bc-4964-4184-a85d-5deaf4deab4f)
![7m-50trees-taskmanager1-2](https://github.com/mlpack/mlpack/assets/39696849/d2fc7832-5a80-47cd-841b-90ad4a5d2d74)

Regarding sharing data will get back.
Thanks

**Comment by shrit** [comment] 2024-01-09 11:25
it looks like you are running out of RAM for me, indeed it would be nice to share the data, so we can run it on a system with amount of higher RAM and see if we ca reproduce the issue

**Comment by rcurtin** [comment] 2024-01-09 22:33
If you're running out of RAM, you could try running with fewer cores.  By default OpenMP will use one core to train one tree in the forest, but if each tree is large this could cause an issue.  I'm not sure how you have mlpack configured, but another thing you could try as an experiment is just to see if disabling OpenMP entirely fixes the issue.

**Comment by SrikanthPusarla** [comment] 2024-01-10 14:45
can you help me where and how to disable OpenMP

**Comment by shubham1206agra** [comment] 2024-01-15 05:53
@SrikanthPusarla Just use OMP_NUM_THREADS to control number of threads created in OpenMP.

**Comment by SrikanthPusarla** [comment] 2024-01-24 04:52
Hi @rcurtin @shrit , the data with 7388125 samples and 304 features is of compressed size 1.7 GB. How can I share that huge file with you

**Comment by rcurtin** [comment] 2024-01-24 22:46
Dropbox perhaps?  Google drive?

**Comment by SrikanthPusarla** [comment] 2024-02-07 16:31
Hi @rcurtin , Please check the data I shared for reproduction, thanks.

**Comment by SrikanthPusarla** [comment] 2024-02-26 17:03
Hi @rcurtin , I tried your both suggestions i.e. set the no of threads to 1 and switched from arma::mat to arma::fmat for the data reading, It shown some improvement in my system. 
Earlier It was taking up to 20 trees only, now with changes it ran successfully with 100 trees.
But it failed again with 600 trees **(process 26792) exited with code -1073740791** after running for more than a day.

Thanks

**Comment by rcurtin** [comment] 2024-02-29 13:54
Hey there @SrikanthPusarla, I found that your data has a particularly strange characteristic that causes a crash in some trees.  I detailed the actual issue in #3644 and that PR also has a fix that will be a part of the next stable release of mlpack.
Once I patched that issue, I was able to successfully build the 600-tree random forest.  On my system this used up to 80GB of RAM with 2 threads.  (So, basically, at least in my case, you'd need ballpark 40GB per thread.)

When the model was saved as a `.bin` file, it took up 4.5GB on disk.  The program ran out of RAM while trying to save as `.xml` (but probably the size of that XML file was going to be massive, like hundreds of GB---the XML format is insanely inefficient, .bin is much better).  So you should probably also comment out the .xml save unless you are doing much smaller forests.

I don't have the test data, so in my local reproduction I commented out the validation/test/thresholding code; I don't think that should have any memory issues though.

For workarounds so that you can successfully run on your system, once you know that you have enough RAM, you can:

 * apply the patch directly from #3644
 * wait for #3644 to be merged and then use the git `master` branch instead of 3.4.0
 * try to keep the problem from ever happening by finding these values `2.4179659719026714` and `2.4179659719026718` in your data (see the explanation in #3644) and making them equal to each other, or figuring out what in the preprocessing is resulting in such close values, maybe it is a bug in the data generation code?
 * add random jitter to your data, which will fix the bug but may reduce the accuracy of the forest in the end: `trnDat += 1e-10 * arma::randu<arma::mat>(trnDat.n_rows, trnDat.n_cols);` right before training should work (you might need to change to `fmat` instead of `mat`, if that is the data type you are using)

Anyway, I hope at least one of those solutions works for you.  If you can try it out and report back, I'd appreciate it. :+1:

**Comment by SrikanthPusarla** [comment] 2024-03-07 09:24
Hi @rcurtin, thanks for all your effort in making it to run successfully and provide the solution with the memory requirements.

**Comment by rcurtin** [comment] 2024-03-07 14:34
No problem!  I just merged the bugfix, so I will go ahead and close this issue.  Please feel free to open new issues if you have any more problems in the future :+1:

**Closed by rcurtin** 2024-03-07 14:34 UTC
Labels: t: bug report
