### ISSUE TITLE
Armadillo warnings since using mlpack

### ISSUE THREAD

**Issue by SanPen** [mlpack/mlpack#3325] opened 2022-11-29 21:53 UTC
Hi, 

Since I included mlpack, I'm getting a ton of these:

```
.../mlpack-4.0.0/src/mlpack/methods/cf/normalization/item_mean_normalization.hpp: In member function ‘void mlpack::ItemMeanNormalization::Normalize(arma::sp_mat&)’:
.../mlpack-4.0.0/src/mlpack/methods/cf/normalization/item_mean_normalization.hpp:108:28: warning: implicitly-declared ‘constexpr arma::SpMat<double>::iterator& arma::SpMat<double>::iterator::operator=(const arma::SpMat<double>::iterator&)’ is deprecated [-Wdeprecated-copy]
  108 |     it = cleanedData.begin();
      |   
```

I replaced all the `#include <armadillo>` by ` #include <mlpack/core.h>` as instructed by other compiler warnings.

**Is there a way to get rid of these warnings?**

**Comment by shrit** [comment] 2022-11-29 22:01
what armadillo version are you using?

**Comment by SanPen** [comment] 2022-11-29 22:02
Sorry, I'm using 11.1.0

**Comment by shrit** [comment] 2022-11-29 22:04
@rcurtin did we handle this in the last merged commits?

**Comment by rcurtin** [comment] 2022-11-29 22:40
@SamPen can you provide a minimal example that shows the warning? Also, what compiler are you using, and what compilation options? I can't reproduce the warning after taking a couple guesses at how to reproduce it.

@shrit I didn't fix any warnings, but happy to fix this one if we can isolate it. Realistically it isn't a dangerous warning.

**Comment by conradsnicta** [comment] 2022-11-30 03:31
@rcurtin Looks like an arcane specification in the C++11 standard, where stuff that was previously allowed but discouraged (in C++98) is now more strongly discouraged via deprecation notices (in C++11).

If a class has a user-defined copy constructor (ie. `user_class::user_class(const user_class&)`), but it doesn't have a corresponding copy assignment operator (ie. `user_class::operator=(const user_class&)`), the compiler will automatically generate it.

The deprecation warning comes from the so-called [rule-of-three](https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)).  it states (in part) that whenever a class has a user-defined copy constructor, it should also have a corresponding user-defined copy assignment operator because the compiler generated version may not be correct.

Within Armadillo there is definition of `SpMat::iterator::iterator(const iterator& other)`, but there is no corresponding definition of `SpMat::iterator::operator=(const iterator& other)`.  The latter is automatically generated by the compiler when it encounters code such as `it = cleanedData.begin()` in mlpack.

One possible way is silence the warning is to declare `SpMat::operator=(const iterator& other) = default`, which tells the compiler that we are okay with the automatically generated function.

It's also possible that the compiler generated copy assignment operator is broken, and this deprecation warning is telling us to check whether it is actually functioning correctly.

**Comment by conradsnicta** [comment] 2022-12-01 00:59
@SanPen We will address the underlying cause in Armadillo, though it may take a while. To disable this warning in the meantime, remove `-Wextra` and `-Wdeprecated-copy` from your compiler flags.

**Comment by conradsnicta** [comment] 2022-12-01 01:39
Moved to https://gitlab.com/conradsnicta/armadillo-code/-/issues/228

**Closed by conradsnicta** 2022-12-01 01:39 UTC
Labels: update dependencies

**Comment by rcurtin** [comment] 2022-12-01 14:54
`-Wextra`, that's the flag I was forgetting!  Now I can reproduce it. :)  Thanks for looking into it @conradsnicta. :+1:
