### ISSUE TITLE
undefined reference to LinearRegression

### ISSUE THREAD

**Issue by freja2** [mlpack/mlpack#1601] opened 2018-12-16 10:17 UTC
Hi, I'm new to mlpack. I was using the Linear Regression on my train.csv file. 
Before that, went through [this](http://mccormickml.com/2017/02/01/getting-started-with-mlpack/) and had no problems running this till the end results.

Here is my code,
```
#include <mlpack/core.hpp>
#include <mlpack/methods/linear_regression/linear_regression.hpp>

using namespace mlpack;
using namespace mlpack::regression;

int main()
{
  arma::mat data;
  data::Load("train.csv", data, true);
  arma::rowvec response = data.row(data.n_rows - 1);
  data.shed_row(data.n_rows - 1);
  LinearRegression lr(data,response);
  return 0;
}
```

the train.csv had values like
```
2.2,39891.00
3.7,57189.00
4.5,61111.00
4.9,67938.00
6.0,93940.00
9.6,112635.00
```

and I was getting the following error
```
$ g++ lr.cpp -o lr -std=c++11 -larmadillo -lmlpack -lboost_serialization -fopenmp
/tmp/ccJzmVju.o: In function `main':
lr.cpp:(.text+0x491): undefined reference to `mlpack::regression::LinearRegression::LinearRegression(arma::Mat<double> const&, arma::Row<double> const&, double, bool)'
collect2: error: ld returned 1 exit status
```

am I missing something here? Any help will be appreciated, Thanks.

**Comment by zoq** [comment] 2018-12-16 18:18
What's the mlpack version?

**Comment by freja2** [comment] 2018-12-16 18:38
I'm using mlpack 3.0.4, I followed [this](http://www.mlpack.org/docs/mlpack-3.0.4/doxygen/build.html) while installing.

First I looked at that tutorial to test if I installed correctly and if I was able to use mlpack in my code or not. 
When I tried to make the linear regression object( following the documentation), it gave the error.

**Comment by rcurtin** [comment] 2018-12-17 13:59
So do you mean that you ran `apt-get install libmlpack-dev`, or do you mean that you downloaded mlpack and ran `cmake ..`, `make`, and `sudo make install`?

**Comment by freja2** [comment] 2018-12-17 14:32
Sorry if I sounded a bit confusing,

While installing, I used `apt-get install libmlpack-dev`, and also installed the dependencies in the same manner as stated on the `Building mlpack from Source`.

After this, I went through [this](http://mccormickml.com/2017/02/01/getting-started-with-mlpack/) as a first timer program. 
Ran it using 
```
$ g++ knn.cpp -o knn -std=c++11 -larmadillo -lmlpack -lboost_serialization -fopenmp
```
and got the shown result from that webpage.

However on making a LinearRegression model, I faced issues as stated above.

**Comment by rcurtin** [comment] 2018-12-17 14:52
Ok, I see.  What's the version of mlpack that got installed?  Try running `dpkg -l libmlpack-dev`.  I'm wondering if the version that you have has a different API for `LinearRegression` or something.  In addition, if you can give the output of `strings /path/to/libmlpack.so | c++filt | grep LinearRegression` where you replace `/path/to/` with wherever `libmlpack.so` got installed on the system, that could help too.

**Comment by freja2** [comment] 2018-12-17 15:08
```
~$ dpkg -l libmlpack-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                Version        Architecture   Description
+++-===================-==============-==============-===========================================
ii  libmlpack-dev:amd64 2.2.5-1build1  amd64          intuitive, fast, scalable C++ machine learn
```

```
~$ strings /usr/local/lib/libmlpack.so | c++filt | grep LinearRegression
mlpack::regression::LinearRegression::Predict(arma::Mat<double> const&, arma::Row<double>&) const
mlpack::regression::LinearRegression::LinearRegression(arma::Mat<double> const&, arma::Row<double> const&, arma::Row<double> const&, double, bool)
mlpack::regression::LinearRegression::LinearRegression(arma::Mat<double> const&, arma::Row<double> const&, double, bool)
mlpack::regression::LinearRegression::Train(arma::Mat<double> const&, arma::Row<double> const&, arma::Row<double> const&, bool)
mlpack::regression::LinearRegression::LinearRegression(arma::Mat<double> const&, arma::Row<double> const&, arma::Row<double> const&, double, bool)
mlpack::regression::LinearRegression::LinearRegression(arma::Mat<double> const&, arma::Row<double> const&, double, bool)
mlpack::regression::LinearRegression::Train(arma::Mat<double> const&, arma::Row<double> const&, bool)
mlpack::regression::LinearRegression::ComputeError(arma::Mat<double> const&, arma::Row<double> const&) const
mlpack::regression::LinearRegression::ComputeError(arma::Mat<double> const&, arma::Row<double> const&) const
mlpack::regression::LinearRegression::LinearRegression(arma::Mat<double> const&, arma::Row<double> const&, arma::Row<double> const&, double, bool)
mlpack::regression::LinearRegression::LinearRegression(arma::Mat<double> const&, arma::Row<double> const&, arma::Row<double> const&, double, bool)
mlpack::regression::LinearRegression::LinearRegression(arma::Mat<double> const&, arma::Row<double> const&, double, bool)
mlpack::regression::LinearRegression::Train(arma::Mat<double> const&, arma::Row<double> const&, bool)
mlpack::regression::LinearRegression::Predict(arma::Mat<double> const&, arma::Row<double>&) const
mlpack::regression::LinearRegression::LinearRegression(arma::Mat<double> const&, arma::Row<double> const&, double, bool)
mlpack::regression::LinearRegression::Train(arma::Mat<double> const&, arma::Row<double> const&, arma::Row<double> const&, bool)
```

**Comment by rcurtin** [comment] 2018-12-17 15:22
It looks like actually you have mlpack installed twice on your system.  The package `libmlpack` should be providing the library `/usr/lib/x86_64-linux-gnu/libmlpack.so` (assuming you are on a 64-bit x86 distribution), and this is the library that your `g++` command is trying to link against.  It so happens, based on your output of `dpkg -l libmlpack-dev`, that that is version 2 of the mlpack library, which has the function signature `LinearRegression(arma::Mat<double> const&, arma::Col<double>& const)`.  But this was deprecated and in mlpack 3, it is `arma::Row<double>& const` not `arma::Col<double>& const`.

So, I can see also that you have a file `/usr/local/lib/libmlpack.so`, which based on the output of `strings` is mlpack 3.  There are presumably also a bunch of header files you installed somewhere for mlpack 3, which is why compilation succeeds, but then at the linking stage it is trying to link to mlpack 2 so it fails.

I would recommend the following: remove mlpack as installed by apt with `apt-get remove libmlpack*`.  Since you already have mlpack 3 installed in `/usr/local/lib/` (and probably `/usr/local/include/`), just use this version in your command and explicitly specify the link and include directories for mlpack:

```
g++ lr.cpp -o lr -std=c++11 -I/usr/local/include/ -L/usr/local/lib/ -larmadillo -lmlpack -lboost_serialization -fopenmp
```

I think that will fix your problem.  Please let me know if I can explain anything in more detail. :)

**Comment by freja2** [comment] 2018-12-17 15:56
This has fixed the problem here and I don't see any issues with my code now.

Upon checking, there was another `libmlpack.so`  in `/usr/lib/x86_64-linux-gnu/`.

So to sum this up, I had 2 different versions of mlpack and the `g++` command was linking me to the version 2 of library, whereas my LinearRegression constructor definition was that of mlpack 3?

Nevertheless, 
thank you very much.
I think it was my fault somewhere while installing the libraries but it seems sorted now.

 :)

**Comment by rcurtin** [comment] 2018-12-17 15:57
Yep, your understanding is correct.  I am glad that we were able to figure out the issue. :)  I'll close this now, but if you have any problems in the future feel free to open another issue.

**Closed by rcurtin** 2018-12-17 15:57 UTC
