### ISSUE TITLE
Is there a different performance between python and cpp on regression?

### ISSUE THREAD

**Issue by xlindo** [mlpack/mlpack#2895] opened 2021-03-29 03:18 UTC
I am testing the performances of mlpack on a comparison among sklearn, mlpack-python, mlpack-cli, mlpack-cpp on regression algorithms.

I found there is less difference between sklearn and mlpack-python, but a worse performance for mlpack-cpp. The variances for the later two are larger, likely sklearn ~ mlpack-python < mlpack-cli << mlpack-cpp.

Is this normal?
Or I can post my codes if necessary.

**Comment by NippunSharma** [comment] 2021-03-29 05:10
@xlindo can you share the codes?

**Comment by xlindo** [comment] 2021-03-29 13:18
Unable to find remote helper for 'https'> @xlindo can you share the codes?

There is a part of the test.
[compare_to_mlpack_on_regression.ipynb](https://github.com/xlindo/show_you_the_code/blob/main/mlpack_comparison_lr/compare_to_mlpack_on_regression.ipynb)

Btw, are the implementations different between python and cpp?

**Comment by xlindo** [comment] 2021-03-29 13:18
> @xlindo can you share the codes?

There is a part of the test.
[compare_to_mlpack_on_regression.ipynb](https://github.com/xlindo/show_you_the_code/blob/main/mlpack_comparison_lr/compare_to_mlpack_on_regression.ipynb)

Btw, are the implementations different between python and cpp?

**Comment by xlindo** [comment] 2021-03-29 13:20
> @xlindo can you share the codes?

There is a part of the test.
[compare_to_mlpack_on_regression.ipynb](https://github.com/xlindo/show_you_the_code/blob/main/mlpack_comparison_lr/compare_to_mlpack_on_regression.ipynb)

Btw, are the implementations different between python and cpp?

**Comment by rcurtin** [comment] 2021-03-29 13:27
The command-line and Python implementations should be exactly the same... would you mind removing the `scale=False` from the Python implementation and seeing what happens?  There could be an input handling bug here.

**Comment by rcurtin** [comment] 2021-03-29 13:28
Also, you can see exactly how the Python and command-line bindings are using the `BayesianLinearRegression` class here: https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/bayesian_linear_regression/bayesian_linear_regression_main.cpp#L151

**Comment by xlindo** [comment] 2021-03-29 13:29
Unable to find remote helper for 'https'> @xlindo can you share the codes?

There is a part of the test.
[compare_to_mlpack_on_regression.ipynb](https://github.com/xlindo/show_you_the_code/blob/main/mlpack_comparison_lr/compare_to_mlpack_on_regression.ipynb)

Btw, are the implementations different between python and cpp?

**Comment by rcurtin** [comment] 2021-03-29 13:31
Yeah, I mean to remove the `scale=False` option entirely; i.e., change this:

```
out = bayesian_linear_regression(input=TrainX,
                                 responses=TrainY,
                                 center=True,
                                 scale=False)
```

to this:

```
out = bayesian_linear_regression(input=TrainX,
                                 responses=TrainY,
                                 center=True)
```

and see if that affects the results. :+1:

**Comment by xlindo** [comment] 2021-03-29 14:09
> Yeah, I mean to remove the `scale=False` option entirely; i.e., change this:
> 
> ```
> out = bayesian_linear_regression(input=TrainX,
>                                  responses=TrainY,
>                                  center=True,
>                                  scale=False)
> ```
> 
> to this:
> 
> ```
> out = bayesian_linear_regression(input=TrainX,
>                                  responses=TrainY,
>                                  center=True)
> ```
> 
> and see if that affects the results. 👍

Thanks for your reply.

I just run the original script on another platform, and everything goes right.
I thought there may be some errors in the outputs, cli or library, that I compiled. 

I will check this again tomorrow.

**Comment by rcurtin** [comment] 2021-03-29 14:23
That seems strange---keep us updated with what you find out!  We can definitely debug and fix any internal mlpack issue we find. :+1:

**Comment by xlindo** [comment] 2021-03-30 06:41
> That seems strange---keep us updated with what you find out! We can definitely debug and fix any internal mlpack issue we find. 👍

[compare_to_mlpack_on_regression.ipynb](https://github.com/xlindo/show_you_the_code/blob/main/mlpack_comparison_lr/compare_to_mlpack_on_regression.ipynb)

The script added the result of a simple cpp.
As you can see, there is no difference at Out[13]. I think this is because of the same libraries in use. Since all dependencies are from conda-forge/mlpack, no matter of py, cli or libmlpack, they are not prone to error compared to a manually compilation.

In contrast, when all things come to my manually compilation result, libopenblas, libarmadillo as well as libmlpack, a consistent result cannot be obtained among python, cli and cpp.

Can you tell me, where should I check first?

**Comment by xlindo** [comment] 2021-03-31 09:33
> That seems strange---keep us updated with what you find out! We can definitely debug and fix any internal mlpack issue we find. 👍

I recompiled OpenBLAS, and everything looks well now.
So, I would like to attribute the different calculation result to the inner problem of OpenBLAS.

**Comment by mercierc** [comment] 2021-04-09 19:09
If it can explain some differences, in sklearn the diagonalization of the covariance matrix is done by SVD while mlpack use an eigen decomposition.

**Comment by xlindo** [comment] 2021-04-11 05:35
> If it can explain some differences, in sklearn the diagonalization of the covariance matrix is done by SVD while mlpack use an eigen decomposition.

Thanks.
And I thought this may be caused by old assembler with lower precision (for OpenBLAS).

**Comment by rcurtin** [comment] 2021-04-16 00:45
@xlindo thanks for running the simulations again.  I agree that it looks like everything is working right now.  I think @mercierc is right that the differences can be explained by sklearn using a different strategy to diagonalize the covariance matrix.

Is there any further issue to solve here, or should we close it? :smile:

**Comment by xlindo** [comment] 2021-04-16 05:52
> @xlindo thanks for running the simulations again. I agree that it looks like everything is working right now. I think @mercierc is right that the differences can be explained by sklearn using a different strategy to diagonalize the covariance matrix.
> 
> Is there any further issue to solve here, or should we close it? 😄

Please close this.

**Closed** 2021-04-16 12:14 UTC
Labels: t: question
