### ISSUE TITLE
missing closing bracket ')'

### ISSUE THREAD

**Issue by Namrata96** [mlpack/mlpack#1318] opened 2018-03-17 11:54 UTC
Missing closing bracket in description of to_matrix_with_info function: https://github.com/mlpack/mlpack/blob/0e14562937fbbe3fba007d93e251d07496e7dced/src/mlpack/bindings/python/mlpack/matrix_utils.py#L61

**Comment by Namrata96** [comment] 2018-03-19 20:00
Closed #1318

**Comment by sourabhvarshney111** [comment] 2018-04-04 19:44
@Namrata96 @zoq @rcurtin Is this issue solved?

**Comment by sourabhvarshney111** [comment] 2018-05-09 06:44
@zoq @Namrata96 I think the issue is solved. Can we close this issue?

**Comment by zoq** [comment] 2018-05-09 13:47
Nice catch, let's close this one, thanks @Namrata96.

**Closed by zoq** 2018-05-09 13:47 UTC
