### ISSUE TITLE
Verify the use of input variable in Backward() routines.

### ISSUE THREAD

**Issue by ShikharJ** [mlpack/mlpack#2005] opened 2019-09-06 12:26 UTC
### Issue description

In a number of the Backward() routines implemented, contributors tend to mistake `input` variable passed as the original input `x` to the Forward() routine. However, it refers to the computed output `f(x)`. This leads to potentially buggy implementations, which need to be thoroughly scoured.

#### Steps to validate / fix

As a starting point, one should try computing the Backward() function mathematically, and verify that the use of the `input` variable in Backward().

**Comment by rcurtin** [comment] 2019-09-06 13:17
It might be worth updating documentation in various places too to point out that `input` isn't the original input `x` but instead `f(x)`, to help reduce mistakes. :)  (I am not sure the state of the documentation currently, I just thought I'd toss that out there as a suggestion.)

**Comment by ShikharJ** [comment] 2019-09-06 14:18
Yeah most certainly, this needs to be changed to prevent further bugs in implementation. Fortunately, not a lot of Backward() routines make use of the said variable.

**Comment by ayusdas2000** [comment] 2019-09-06 14:28
I would like to try this.

**Comment by ShikharJ** [comment] 2019-09-06 14:34
@ayusdas2000 Go for it. I'd specifically start with the `ann/` and the associated subfolders. Maybe start with SigmoidCrossEntropy loss function.

**Comment by ayusdas2000** [comment] 2019-09-06 14:41
After building mlpack on my os how should I proceed?

**Comment by rcurtin** [comment] 2019-09-06 14:46
@ayusdas2000 what have you tried?  If you take a look through the code, Shikhar's description of the issue should start to make sense.

**Comment by ayusdas2000** [comment] 2019-09-06 14:59
Got your point. Will again contact you if I encounter any doubt. Thank you

**Comment by rcurtin** [comment] 2019-09-06 15:01
There's often some context we can help share, but sharing the context is a lot easier once you've explored the code a bit. :)

**Comment by ayusdas2000** [comment] 2019-09-06 17:28
libboost command for installing cmake dependency is not working despite installing libboost. Because i am unable to install cmake therefore i am unable to build mlpack on my home system

**Comment by rcurtin** [comment] 2019-09-06 17:30
Can you open that in a separate issue?  It's a little off topic for this one. :+1:  (Sorry to be pedantic)

**Comment by ayusdas2000** [comment] 2019-09-06 17:52
could not find out. I will try the other first issues. Very sorry.

**Comment by vss96** [comment] 2019-10-25 18:16
@ShikharJ @rcurtin  is this fixed? I would like to have a jab at it if no one is working on it.

**Comment by RishabhGarg108** [comment] 2020-11-09 16:11
Hey @ShikharJ @rcurtin , is this fix still needed to be done?

**Comment by rcurtin** [comment] 2020-11-09 16:18
I'm not sure the status---I think that updating the documentation (see my comment [here](https://github.com/mlpack/mlpack/issues/2005#issuecomment-528850769)) would still be worthwhile, but I am not sure if any layers are wrong.  Really what is needed is an audit---so if you want to start by finding layers that use the `input` variable in the `Backward()` layer (like the issue describes), you can then take a look and see if it is being used in the correct way. :+1:

**Comment by RishabhGarg108** [comment] 2020-11-09 16:32
@rcurtin , I looked at the complete directory structure of `methods/ann` and I found two things. The `input` variable is used in a few "activation layers" and almost all the "loss functions". So, for layers, `input` variable makes sense because there the `input` variable is actually the output from let say any previous layer. So, that is actually the input to that layer, so that seems good. 

But, if we look at the "loss functions", then there the `input` variable actually refers to the output that we get after applying that loss function. So, essentially `input` variable there refers to the predictions on which we are applying the loss function. So, I think this is misleading and we need to do something about it.

What are your thoughts about it?

**Comment by rcurtin** [comment] 2020-11-09 16:35
Yes, to my understanding, that's precisely the issue. :+1:  If you want to change that name, that would be really great, but when you do it, be sure to make sure that the backward pass is being computed correctly too! :)

**Comment by RishabhGarg108** [comment] 2020-11-09 16:40
> Yes, to my understanding, that's precisely the issue.  If you want to change that name, that would be really great, but when you do it, be sure to make sure that the backward pass is being computed correctly too! :)

Yeah I would be happy to do that. But I need to clarify a couple of things. When you say that I have to ensure that when I change the name of variable, I consistently change it throughout the function or shall I have to mathematically check the correctness? And secondly, as you mentioned that we also need to change this in documentation, this is not clear to me as to where shall I change it. It would be great if you could elaborate it a little bit.
Thanks :)

**Comment by rcurtin** [comment] 2020-11-11 01:11
Yes to both things on the first question: we want to change the name of the variable, but we also want to audit the implementations to make sure that there are no errors caused by the incorrect name of the variable confusing someone and then they implemented the wrong thing.  I assume the function documentation itself should be updated if it refers to `input` (we should just change the names), but use your judgment and see what you think is best. :+1:

**Comment by RishabhGarg108** [comment] 2020-11-11 05:01
Thanks for clarification @rcurtin ! I'm on it now.

**Comment by RishabhGarg108** [comment] 2020-12-30 05:23
The issue has been tackled in #2714 and #2724 . Can we close this one now ?

**Comment by ShikharJ** [comment] 2021-01-01 05:11
@rcurtin I took a brief view over @RishabhGarg108's PRs, I believe they seem to fix this issue, and look good to me. I'll leave it to you to make the final call regarding closing this issue. Also, I must apologize, I'm unable to find much time these days to contribute.

**Comment by rcurtin** [comment] 2021-01-05 21:04
@ShikharJ thanks for taking a look! @RishabhGarg108 I agree---let's go ahead and close this issue then. Thanks for putting time into fixing the issues, and sorry that I wasn't able to be a part of the review process. :+1:

**Closed by rcurtin** 2021-01-05 21:04 UTC
Labels: c: testing, good first issue, s: keep open, t: bug report
