### ISSUE TITLE
  file INSTALL cannot find

### ISSUE THREAD

**Issue by zepen** [mlpack/mlpack#1023] opened 2017-06-09 12:34 UTC
CMake Error at src/mlpack/methods/neighbor_search/cmake_install.cmake:72 (FILE):
  file INSTALL cannot find
  "/home/niu/mlpack-2.2.2/src/mlpack/methods/neighbor_search/$<TARGET_FILE_DIR:mlpack_kfn>/mlpack_allkfn".
Call Stack (most recent call first):
  src/mlpack/methods/cmake_install.cmake:62 (INCLUDE)
  src/mlpack/cmake_install.cmake:74 (INCLUDE)
  cmake_install.cmake:49 (INCLUDE)
Why? help me, thinks!!!

**Comment by zepen** [comment] 2017-06-09 12:37
My system is centos 7.3.

**Comment by rcurtin** [comment] 2017-06-09 14:16
Can you tell me what version of CMake you are using, and can you also try with the newer mlpack 2.2.3?  http://www.mlpack.org/files/mlpack-2.2.3.tar.gz

**Comment by Muthiang** [comment] 2017-06-27 19:08
Same error and mlpack-2.2.3

**Comment by rcurtin** [comment] 2017-06-27 19:45
@Muthiang: What version of CMake are you using?  And what happens if you do `make` followed by `make install`?

**Comment by Muthiang** [comment] 2017-06-27 20:21
The following install failure error occurs:

CMake Error at src/mlpack/methods/neighbor_search/cmake_install.cmake:72 (FILE):
file INSTALL cannot find
"/home/niu/mlpack-2.2.3/src/mlpack/methods/neighbor_search/$<TARGET_FILE_DIR:mlpack_kfn>/mlpack_allkfn".
Call Stack (most recent call first):

**Comment by Muthiang** [comment] 2017-06-27 20:22
cmake version 2.8.12.2

**Comment by rcurtin** [comment] 2017-06-27 20:24
Are you able to try using CMake 3?  And can you verify that the error persists if you first do `make` then `make install` as two separate commands?

**Comment by Muthiang** [comment] 2017-06-27 20:25
ok, let me try it out and get back

**Comment by rcurtin** [comment] 2017-06-28 22:04
Hmm, interesting, glad that a new CMake solved the issue.  I will leave this issue open though, in case anyone who is looking for a way to contribute wants to figure this out.  I'm happy to merge a patch and release 2.2.4 with a fix, for anyone who is still using CMake 2.8.  Otherwise, the code causing the issue won't exist in mlpack 3.0.0, so this can be closed when that is released.

**Comment by Rajiv2605** [comment] 2017-07-04 06:35
I had this issue when I was using cmake version 2.8.12.2. I then updated it to 3.8.2. Even then, I was having this issue. I was using was C++98. When I updated it to C++ 11, it was resolved. Hence, the solution looks like using CMake version >=3 and g++ version >=5.

**Comment by starlord1311** [comment] 2018-02-12 21:58
can i take up this issue? @zepen

**Comment by zoq** [comment] 2018-02-13 10:10
@zepen Feel free to work on the issue, the first step is to reproduce the error, let us know if we should clarify anything.

**Comment by rcurtin** [comment] 2018-04-02 17:37
Since mlpack 3 is now released, I think it is ok to close this issue.  The code that was causing the problem is no longer in the repository.

**Closed by rcurtin** 2018-04-02 17:37 UTC
Labels: D: easy, P: minor, T: defect
