### ISSUE TITLE
install-problem:SpMat_meat.hpp:5794:7: error: ‘cache_mutex’ was not declared in this scope

### ISSUE THREAD

**Issue by cwlseu** [mlpack/mlpack#1171] opened 2017-12-15 11:38 UTC
when I install mlpack, i encounter the following problems:

In member function void arma::SpMat<eT>::sync_cache() const’:
SpMat_meat.hpp:5794:7: error: ‘cache_mutex’ was not declared in this scope
 cache_mutex.lock();

In member function void arma::SpMat<eT>::sync_csc() const’:
SpMat_meat.hpp:5794:7: error: ‘cache_mutex’ was not declared in this scope
       cache_mutex.lock();

**Comment by rcurtin** [comment] 2017-12-15 13:34
Hi,

This is far too little information to be able to help you solve the problem.  Can you tell us:

 * What command you run that produced the output.
 * The full compilation error.
 * What version of Armadillo you are using.
 * What version of mlpack you are using.
 * How you installed Armadillo.
 * What system you are running on.

**Comment by niceSimon7** [comment] 2017-12-29 03:01
I also encountered this problem:
Linux: CentOS7
GCC: 4.8.5
Armadillo: 8.300.2 (Compile and install)
Boost:1.66.0
mlpack: 2.2.4
cmake:3.10.1

The full compilation error:
[root@localhost mlpack-2.2.5]# mkdir build
[root@localhost mlpack-2.2.5]# cd build/
[root@localhost build]# cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Armadillo: /usr/lib64/libarmadillo.so (found suitable version "8.300.2", minimum required is "4.200.0") 
-- Armadillo libraries: /usr/lib64/libarmadillo.so
CMake Warning at /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:270 (find_package)


CMake Warning at /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:270 (find_package)


CMake Warning at /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:270 (find_package)


-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   program_options
--   unit_test_framework
--   serialization
-- Found OpenMP_C: -fopenmp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
-- Found Git: /bin/git (found version "1.8.3.1") 
-- gitversion.hpp is already up to date.
-- Regenerating arma_config.hpp.
CMake Warning (dev) at src/mlpack/methods/neighbor_search/CMakeLists.txt:37 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_knn".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/mlpack/methods/neighbor_search/CMakeLists.txt:45 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_kfn".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/mlpack/methods/rann/CMakeLists.txt:42 (get_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "mlpack_krann".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Warning at CMakeLists.txt:404 (message):
  txt2man not found; man pages will not be generated.


-- Found PkgConfig: /bin/pkg-config (found version "0.27.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/simon/文档/mlpack-2.2.5/build
[root@localhost build]# make
Scanning dependencies of target mlpack_gitversion
[  0%] Updating gitversion.hpp (if necessary)
-- Found Git: /bin/git (found version "1.8.3.1") 
-- gitversion.hpp is already up to date.
[  0%] Built target mlpack_gitversion
Scanning dependencies of target mlpack_arma_config
[  0%] Updating arma_config.hpp (if necessary)
-- Regenerating arma_config.hpp.
[  0%] Built target mlpack_arma_config
Scanning dependencies of target mlpack_headers
Moving header files to include/mlpack/
[  0%] Built target mlpack_headers
Scanning dependencies of target pkgconfig
[  1%] Generating mlpack.pc (pkg-config) file.
[  1%] Built target pkgconfig
Scanning dependencies of target mlpack
[  1%] Building CXX object src/mlpack/CMakeFiles/mlpack.dir/core/data/load_csv.cpp.o
In file included from /usr/include/armadillo:53:0,
                 from /home/simon/文档/mlpack-2.2.5/src/mlpack/../mlpack/core/arma_extend/arma_extend.hpp:52,
                 from /home/simon/文档/mlpack-2.2.5/src/mlpack/../mlpack/prereqs.hpp:79,
                 from /home/simon/文档/mlpack-2.2.5/src/mlpack/../mlpack/core.hpp:218,
                 from /home/simon/文档/mlpack-2.2.5/src/mlpack/core/data/load_csv.hpp:18,
                 from /home/simon/文档/mlpack-2.2.5/src/mlpack/core/data/load_csv.cpp:12:
/usr/include/armadillo_bits/compiler_setup.hpp:498:91: 附注：#pragma message：WARNING: use of OpenMP disabled due to compiler bug in gcc <= 5.3
       #pragma message ("WARNING: use of OpenMP disabled due to compiler bug in gcc <= 5.3")
                                                                                           ^
In file included from /usr/include/armadillo:589:0,
                 from /home/simon/文档/mlpack-2.2.5/src/mlpack/../mlpack/core/arma_extend/arma_extend.hpp:52,
                 from /home/simon/文档/mlpack-2.2.5/src/mlpack/../mlpack/prereqs.hpp:79,
                 from /home/simon/文档/mlpack-2.2.5/src/mlpack/../mlpack/core.hpp:218,
                 from /home/simon/文档/mlpack-2.2.5/src/mlpack/core/data/load_csv.hpp:18,
                 from /home/simon/文档/mlpack-2.2.5/src/mlpack/core/data/load_csv.cpp:12:
/usr/include/armadillo_bits/SpMat_meat.hpp: 在成员函数‘void arma::SpMat<eT>::sync_cache() const’中:
/usr/include/armadillo_bits/SpMat_meat.hpp:5740:7: 错误：‘cache_mutex’在此作用域中尚未声明
       cache_mutex.lock();
       ^
/usr/include/armadillo_bits/SpMat_meat.hpp: 在成员函数‘void arma::SpMat<eT>::sync_csc() const’中:
/usr/include/armadillo_bits/SpMat_meat.hpp:5794:7: 错误：‘cache_mutex’在此作用域中尚未声明
       cache_mutex.lock();
       ^
make[2]: *** [src/mlpack/CMakeFiles/mlpack.dir/core/data/load_csv.cpp.o] 错误 1
make[1]: *** [src/mlpack/CMakeFiles/mlpack.dir/all] 错误 2
make: *** [all] 错误 2
[root@localhost build]#

**Comment by niceSimon7** [comment] 2018-01-02 02:29
The old version(Armadillo: 8.300.0) do not have this problem!

**Comment by rcurtin** [comment] 2018-01-03 14:36
I dug into this one a bit and did reproduce it.  It's actually a typo in the Armadillo code, and will be fixed with the next release (8.300.3 I think).  If you'd rather get it fixed now, your options are to use the older version of Armadillo or apply the change in this patch:

https://github.com/conradsnicta/armadillo-code/commit/fd77c9078e074a14f4b963f759bde5208c7bf09c

I'll go ahead and close this issue (please feel free to open another one if you have any more problems).

**Closed by rcurtin** 2018-01-03 14:36 UTC
