### ISSUE TITLE
strange results with LinearRegression

### ISSUE THREAD

**Issue by JulienOMD** [mlpack/mlpack#2053] opened 2019-10-14 09:30 UTC
Hi,
I am using the LinearRegression class to find the coefficients of a polynomial approximation. I get strange results. Maybe I am not using the library properly. 
The sample responses (attached response.zip) should nicely follow a cubic polynom. I have tested it with an online tool and it returns the four coefficients:
-2.4199E+02,-2.3422E+00,-7.6584E-03,-1.0072E-05
Now with the mlpack command line, or class, it returns the following coefficients :
-1.1232E-02,8.5112E-01,5.8621E-03,8.3796E-06
I have also attached the training file (train.zip) which contains the values of x, x2, and x3 which give the responses in responses.zip, so you can reproduce with the command line tool.
What is strange is that, if I plot the predictions from the mlpack model, it gives a curve that has the same topology as the response, but with inverted inflection points.
Can anyone guide me on this ?

[train.zip](https://github.com/mlpack/mlpack/files/3723751/train.zip)
[responses.zip](https://github.com/mlpack/mlpack/files/3723752/responses.zip)

**Comment by rcurtin** [comment] 2019-10-19 11:52
Hi @JulienOMD, I took a look at your data and played with it.  It seems that the cause of the problem here is that the condition number of the covariance is quite high.  i.e., if I compute the condition number with `cond(train' * train)` I see that it is `1e12`.  This is because the range of values is quite large: the first feature takes values between -340 and -141, whereas the third feature takes values between -39304000 and -2803221.  The `mlpack_linear_regression` program uses the psuedoinverse of the covariance to compute a solution, and the psuedoinverse can have stability issues when the condition number is large.

So, my suggestion to get a good result here would be to first apply diagonal scaling (i.e. make the variance of each feature 1 and the mean 0); perhaps this can be done with `mlpack_preprocess_scale`.  Then, you can learn a model on those scaled features, and then unscale the learned model coefficients and you should be able to recover the coefficients that the online tool gave.

I hope that this is helpful---let me know if I can clarify anything. :+1:

**Comment by JulienOMD** [comment] 2019-10-20 02:16
Thanks a lot for your answer.
Actually, I managed to have acceptable results when I remove the sign of my samples, which is a simple offset in my practical case. So problem solved for me.

**Comment by rcurtin** [comment] 2019-10-20 05:31
Sounds good, glad to hear you were able to resolve it. I'll go ahead and close this issue then :+1:

**Closed by rcurtin** 2019-10-20 05:31 UTC
Labels: c: methods, t: question
