### ISSUE TITLE
`data::Split` should issue an error when the data and labels have different number of samples.

### ISSUE THREAD

**Issue by RishabhGarg108** [mlpack/mlpack#2991] opened 2021-06-21 13:07 UTC
Currently, when `data::Split` is called on a dataset in which data and labels have different sizes, then the result is undefined. Sometimes, it splits while sometimes it gives segmentation fault while sometimes it throws an out of bound error. Ideally, it should always throw an exception clearly saying that the sizes do not match.

I encountered this while writing a test where I accidentally forgot to remove the header from the responses file. I ran that test several times and sometimes it would give segmentation fault and sometimes it would run. I also made a small dataset to test this, but for that, it was throwing out of bounds error (probably thrown by armadillo when an invalid index was being accessed)

**Comment by zoq** [comment] 2021-06-22 01:47
Just to add some more information in this case:

https://github.com/mlpack/mlpack/blob/68ff28175d1103c092d4c3f0bc495c450ecd40d2/src/mlpack/core/data/split_data.hpp#L27 

does not check the input size, we should throw a runtime error similair to:

https://github.com/mlpack/mlpack/blob/68ff28175d1103c092d4c3f0bc495c450ecd40d2/src/mlpack/core/data/split_data.hpp#L148-L149

if the size is different.

**Comment by RishabhGarg108** [comment] 2021-06-22 05:26
Yeah, we already have `mlpack::utils::CheckSameSizes` that can perform this sanity check in `SplitHelper` as pointed by @zoq.

**Comment by prasad-dash** [comment] 2021-06-30 13:24
Has this issue been assigned to someone, if not can I work on it?

**Comment by RishabhGarg108** [comment] 2021-06-30 13:47
Hey @prasad-dash, it is not assigned to anyone. Feel free to work on this.

**Comment by NippunSharma** [comment] 2021-07-08 18:32
There are `CheckSameSizes` and `CheckSameDimensionality` utilities that got merged in #2370, maybe those can be helpful. Also there is #2820 that faces a similar issue, maybe it makes sense to tackle both of these in a single PR?

**Comment by RishabhGarg108** [comment] 2021-07-09 13:09
Yeah, the fix that is needed here is the same as required in #2820. But, that issue is specific only to bindings. While this is related to mlpack/core. Maybe it is good to keep them separate so that it doesn't create any confusion?

**Comment by jaskiratsingh2000** [comment] 2021-07-17 14:41
Hey @zoq I am quite beginner and super interested to contribute towards this repo and this issue seems to be good but I am not sure that how to start with it. Can you please exactly let me know that what and where are the changes required?
I would be super grateful to your response. Thanks

**Comment by zoq** [comment] 2021-07-17 23:46
A good first step is to write a test file to reproduce the issue. In this case you could adapt:

https://github.com/mlpack/mlpack/blob/42071e92be63221da73a620de5beac0a5c537a9c/src/mlpack/tests/split_data_test.cpp#L154-L176

the test case uses the correct input/labels dimension, so you have to modify the `input` or `labels` matrix to produce the error.

**Comment by jaskiratsingh2000** [comment] 2021-07-18 17:45
@zoq So I just have to copy the same in a new file and just changed the mat input arguments? Is this what you mean to say?

**Comment by zoq** [comment] 2021-07-19 01:27
What I was saying is, you have to write a new test, you can copy the one I referenced above, change the test case name. Build mlpack and run the test. Since you copied the test case it will run just fine, but to reproduce the issue, you can use

`const Row<size_t> labels = arma::linspace<Row<size_t>>(0, input.n_cols,  input.n_cols + 1); `

instead of

`const Row<size_t> labels = arma::linspace<Row<size_t>>(0, input.n_cols - 1,  input.n_cols); `

That should trigger a test failure.

**Comment by jaskiratsingh2000** [comment] 2021-07-19 05:50
@zoq So main working in this issue is that I have to take the above case as reference and paste just below it. and final outcome of this test case should be an error. Please correct me if I am assuming this wrong.

**Comment by Chandu-4444** [comment] 2021-08-19 15:18
Hey @RishabhGarg108. Can I work on this? I'm a beginner and was quite excited to look into this.

**Comment by zoq** [comment] 2021-08-19 16:32
I haven't seen a PR yet, so feel free to work on it.

**Comment by swaingotnochill** [comment] 2021-08-31 05:42
This is exactly what happened with me recently. Will try to resolve this ASAP.

**Closed** 2021-09-24 15:56 UTC
Labels: help wanted, good first issue, c: core, t: added feature
