### ISSUE TITLE
reinforcement learning build missing

### ISSUE THREAD

**Issue by bching28** [mlpack/mlpack#1150] opened 2017-11-10 20:38 UTC
Hi there,

I just managed to build mlpack and was looking for the reinforcement learning executable.  I noticed that there was no executable created for reinforcement learning.  Could you provide me with some insight here?

Thanks

**Comment by rcurtin** [comment] 2017-11-10 21:11
There's no standalone program for reinforcement learning.  What are you trying to do?  Maybe you can find some lower-level C++ classes that do what you are looking for in the library.

**Comment by bching28** [comment] 2017-11-10 21:50
I was trying to implement reinforcement learning (Q-Learning specifically) into a SAT solver (written in C++).  I wanted to see if implementing reinforcement learning in the restart policy could improve the performance of a SAT solver.

If there's no standalone program, then what does the reinforcement learning folder and the q-learning code do?  Like what is it used for?

**Comment by zoq** [comment] 2017-11-11 13:39
Providing an executable for the Reinforcement learning methods is difficult since the paradigm can be useful in a variety of tasks including game playing, modeling, robotics, etc. Each task is slightly different, however, it could be useful to provide an executable for some tasks like playing games.

Anyway, as @rcurtin already pointed out you have to use the C++ interface do what you are looking for. For some examples, you could look at the tests: https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/q_learning_test.cpp or https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/rl_components_test.cpp. Let us know if we can clarify anything further.

**Comment by bching28** [comment] 2017-11-11 20:27
Thanks for getting back to me on this.  So I am new to this type of research and development and have just started learning about reinforcement learning in the past couple months.  I have never taken open-source source code (a SAT solver) and a library (mlpack) and tried to integrate them together.  What are some good first steps for doing this?  Is there actually a particular C++ file for reinforcement learning in mlpack that I can simply "#include" in the SAT solver code and call the reinforcement learning algorithm?

And could you clarify what @rcurtin meant about lower level C++ classes? Like an example?

Thanks again!

**Comment by zoq** [comment] 2017-11-12 12:56
If you like to use the Q-Learning method basically it's sufficient to write an "Environment" that provides a Sample, IsTerminal and InitialSample function, for an example you can take a look at: https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/reinforcement_learning/environment/cart_pole.hpp which implements the Cart Pole task. Once you implemented the task you like to solve you can use the Q-Learning method as shown here: https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/q_learning_test.cpp#L61.

So something like:

```c++
SATUpdate
{
 public:
  SATUpdate(...) {}

  double Sample(const State& state,
                const Action& action,
                State& nextState) const
  {
    // Use the given state and action and return the reward and the next state.
  }

  State InitialSample() const
  {
    // The starting sample could be random.
  }

  bool IsTerminal(const State& state) const
  {
    // Check if the current state is a terminal state.
  }
}
```

If you like you can link me to the SAT solver you like to use and I can probably go into more details.

**Comment by bching28** [comment] 2017-11-12 19:49
I was planning on modifying the Glucose SAT solver (http://www.labri.fr/perso/lsimon/glucose/).  I am modifying **Glucose 3.0**.  I am still trying to identify the states I will be using for modifying the restart policy.  But thank you for the help so far.  I will take some time to look into the cartpole code you sent me.

**Comment by zoq** [comment] 2017-11-13 23:09
Thanks for the link, just glanced over the code and it looks really interesting, I'll take a closer look in the next days.

**Comment by bching28** [comment] 2017-11-14 08:48
Sure no problem. And thanks again for the help

**Comment by bching28** [comment] 2017-11-15 19:02
How do I get the cart_pole code with Q-Learning to run?  

Also, would you recommend installing mlpack using the source code from github or through the ubuntu package manager?  I don't believe the package manager includes the reinforcement learning folder.  If I install mlpack from the files from github, should I just copy the files into usr/local/ and just install there?

**Comment by zoq** [comment] 2017-11-15 20:20
You have to build from source to use the reinforcement methods (will be included in mlpack 3.0). You can follow the build steps as shown here: http://www.mlpack.org/docs/mlpack-2.2.5/doxygen/build.html#build and you can use ``make install`` if you like to install mlpack to ``/usr/include/mlpack/`` and ``/usr/lib/``, once it has built or ``/usr/local/``on mac OS.

About how to use ``cart_pole`` in combination with ``Q-Learning`` here is a simple example:

```c++
#include <mlpack/core.hpp>

#include <mlpack/methods/ann/ffn.hpp>
#include <mlpack/methods/ann/init_rules/gaussian_init.hpp>
#include <mlpack/methods/ann/layer/layer.hpp>
#include <mlpack/methods/reinforcement_learning/q_learning.hpp>
#include <mlpack/methods/reinforcement_learning/environment/cart_pole.hpp>
#include <mlpack/methods/reinforcement_learning/policy/greedy_policy.hpp>
#include <mlpack/core/optimizers/adam/adam_update.hpp>
#include <mlpack/methods/reinforcement_learning/training_config.hpp>

using namespace mlpack;
using namespace mlpack::ann;
using namespace mlpack::optimization;
using namespace mlpack::rl;

int main()
{
  // Set up the network.
  FFN<MeanSquaredError<>, GaussianInitialization> model(MeanSquaredError<>(),
      GaussianInitialization(0, 0.001));
  model.Add<Linear<>>(4, 128);
  model.Add<ReLULayer<>>();
  model.Add<Linear<>>(128, 128);
  model.Add<ReLULayer<>>();
  model.Add<Linear<>>(128, 2);

  // Set up the policy and replay method.
  GreedyPolicy<CartPole> policy(1.0, 1000, 0.1);
  RandomReplay<CartPole> replayMethod(10, 10000);

  TrainingConfig config;
  config.StepSize() = 0.01;
  config.Discount() = 0.9;
  config.TargetNetworkSyncInterval() = 100;
  config.ExplorationSteps() = 100;
  config.DoubleQLearning() = false;
  config.StepLimit() = 200;

  // Set up DQN agent.
  QLearning<CartPole, decltype(model), AdamUpdate, decltype(policy)>
      agent(std::move(config), std::move(model), std::move(policy),
      std::move(replayMethod));

  arma::running_stat<double> averageReturn;
  size_t episodes = 0;
  bool converged = true;
  while (true)
  {
    double episodeReturn = agent.Episode();
    averageReturn(episodeReturn);
    episodes += 1;

    // Just a simple threshold could be > 1000.
    if (episodes > 1000)
    {
      std::cout << "Cart Pole with DQN failed." << std::endl;
      converged = false;
      break;
    }

    /**
     * Reaching running average return 35 is enough to show it works.
     * For the speed of the test case, I didn't set high criterion.
     */
    std::cout << "Average return: " << averageReturn.mean()
        << " Episode return: " << episodeReturn << std::endl;
    if (averageReturn.mean() > 35)
    {
      agent.Deterministic() = true;
      arma::running_stat<double> testReturn;
      for (size_t i = 0; i < 10; ++i)
        testReturn(agent.Episode());

      std::cout << "Average return in deterministic test: "
          << testReturn.mean() << std::endl;
      break;
    }
  }

  return 0;
}
```

```
clang++ test.cpp /path/to/mlpack/lib/libmlpack.dylib -I/path/to/mlpack/include/ -larmadillo -std=c++11
```

**Comment by bching28** [comment] 2017-11-16 01:38
I cloned the git repository into this directory: ~/Documents/mlpack and followed the steps in the link (created a build folder, make, make install).  It seems that "make install" installed mlpack files in usr/local/include, usr/local/lib, and usr/local/bin.  I hope that is ok since I am running mlpack on Ubuntu 16.04.  

Now, am I correct in assuming that test.cpp is the above code you posted?  I copied and pasted the code into test.cpp, which I saved in ~/Documents/mlpack (please let me know if it should be saved elsewhere).  Then, I ran the following command: **clang++ test.cpp -I/usr/local/include/mlpack/ -larmadillo -std=c++11**.  I get a fatal error (screenshot attached).  I am not entirely sure where the libmlpack.dylib is located.  When I try searching for libmlpack, all I see are libmlpack.so, libmlpack.so.2, and libmlpack.so.2.0.  

Fatal Error:
<img width="731" alt="screen shot 2017-11-15 at 5 37 16 pm" src="https://user-images.githubusercontent.com/29585989/32869403-a750144c-ca2b-11e7-9f3c-93ef06a56625.png">

**Comment by zoq** [comment] 2017-11-16 01:44
Sorry ``libmlpack.dylib`` is mac OS specific, you can just link against ``libmlpack.so`` or just use:

```
clang++ test.cpp -lmlpack -larmadillo -std=c++11
```

since ``/usr/local/lib/`` and ``/usr/local/include`` should be in your linker path. Also you are right about ``test.cpp``. Let us know if that solves the issue.

**Comment by zoq** [comment] 2017-11-16 01:45
Btw. you can also use ``g++`` instead of ``clang++``.

**Comment by bching28** [comment] 2017-11-16 02:09
I tried "clang++ test.cpp -lmlpack -larmadillo -std=c++11" but I am still getting that same fatal error.  I also tried linking it manually with "clang++ test.cpp /usr/local/lib/libmlpack.so -I/usr/local/include/mlpack -larmadillo -std=c++11".  This also gives me the same fatal error.

Should I save the test.cpp in mlpack/src/mlpack/tests?

**Comment by bching28** [comment] 2017-11-16 02:10
Actually, hold off on that.  I tried g++ and it seems to not be a fatal error.  I am out of disk space.

**Comment by bching28** [comment] 2017-11-16 08:29
So I got the the command to work: **g++ test.cpp -lmlpack -larmadillo -std=c++11**.  All I noticed was that it created an output file called **a.out**.  Based on the code, shouldn't it have outputted something on the terminal (e.g. "Average return: ...")?  Nothing printed onto the terminal.  I attached a screenshot of my environment.

<img width="1380" alt="screen shot 2017-11-16 at 12 27 37 am" src="https://user-images.githubusercontent.com/29585989/32881135-0534963a-ca65-11e7-8c79-0ef9f76af525.png">

**Comment by rcurtin** [comment] 2017-11-16 14:20
@bching28: `a.out` is the compiled program produced by `g++`.  Now you have to run it:

```
$ ./a.out
```

and that should give the output you are looking for.

**Comment by bching28** [comment] 2017-11-16 15:59
Oh sorry. I forgot to mention, I did try running the **./a.out** and just took another look again at the error message I received last night.  It's having trouble loading shared libraries.  So I just tried ./a.out /usr/local/lib and ./a.out /usr/local/lib/libmlpack.so.2, but it doesn't seem to make a difference.

**Comment by bching28** [comment] 2017-11-16 16:01
Oh sorry. I forgot to mention, I did try running the **./a.out** and just took another look again at the error message I received last night.  It's having trouble loading shared libraries.  So I just tried **./a.out /usr/local/lib** and **./a.out /usr/local/lib/libmlpack.so.2**, but it doesn't seem to make a difference.

And sorry, pressed the "close and comment button" by accident...just woke up

<img width="895" alt="screen shot 2017-11-16 at 7 58 23 am" src="https://user-images.githubusercontent.com/29585989/32901221-2f5d99a4-caa4-11e7-8afa-fd4577cbd485.png">

**Comment by rcurtin** [comment] 2017-11-16 16:01
Right, you'll need to set `LD_LIBRARY_PATH` like in the readme.  Try this:

```
$ export LD_LIBRARY_PATH=/usr/local/lib/
$ ./a.out
```

and that should fix the problem and the program should run successfully.

**Comment by bching28** [comment] 2017-11-16 16:05
Perfect!  I got an output this time.  I will take a closer look at the code later today.  I had a couple questions about the Q-Learning code in the folder after I was taking a look last night, but I will post them once I gather my thoughts.

**Comment by bching28** [comment] 2017-11-16 19:02
I am trying to implement similar code to the cart_pole.hpp code that @zoq mentioned above.  So one of my confusions stems from the `double Sample()` function in **cart_pole.hpp**. 
 
<img width="514" alt="screen shot 2017-11-16 at 10 51 22 am" src="https://user-images.githubusercontent.com/29585989/32909802-5f45cf02-cabc-11e7-8b39-2adf9d703ee5.png">

My understanding of Q-Learning is that states are supposed to receive a state value (Q-value) based on the reward.  So where does the algorithm actually check for the best state value so that it converges to the optimal state/action?  Is this done in **q_learning_impl.hpp** with the **bestActions** variable?

And if the agent is supposed to eventually choose an optimal action given a particular state, then why is it that the next state is always determined by these formulas?:

<img width="487" alt="screen shot 2017-11-16 at 10 56 15 am" src="https://user-images.githubusercontent.com/29585989/32909945-d44bc5f4-cabc-11e7-9007-6c1fa9a3bef3.png">

**Comment by zoq** [comment] 2017-11-17 12:39
For Q-Learning you can ignore the second Sample function (``double Sample(const State& state, const Action& action) const``) which is just a wrapper for the Sample function which also takes the ``nextState`` as input. In some cases you just need the reward so, the state after performing the given action is irrelevant and for convenience, we provide a wrapper.

You are right about ``BestAction`` which selects the best action based on the given action value.

> And if the agent is supposed to eventually choose an optimal action given a particular state, then why is it that the next state is always determined by these formulas?:

The ``nextState`` is not necessarily the state that is chosen by the learner, it's the state of the environment after applying the given action. Which is necessary e.g. to check for termination and to update the current state. Here is a simple example:

```
       ---->2--->4
      |          ^
1 ----|          |
      |          |
       ---->3--->5
```

Suppose your initial state is 1 and the goal is to reach state 4, from state 1 there are two options; to go left to reach state 2 or to go right to reach state 3. So the call would look something like:

```
State nextState;
env.Sample(state(1), action(left), nextState)
```

where ``nextState``, contains the state after performing the action left (it's a reference (C++)), so afterwards ``nextState`` is 2, so we can check if ``nextState`` is equal to state 4 which would be the final step. We can do the same for the other action, which would set nextState to 3.

I hope this is helpful, let me know if I should clarify anything.

> Trying to figure out how everything is linked together. Which reinforcement learning files are involved when interfacing cart-pole and Q-Learning? Do you need all these files?: q_learning.hpp, q_learning_impl.hpp, q_learning_test.cpp, and cart_pole.hpp

You just need to include ``q_learning.hpp`` perhaps this is helpfull: http://www.mlpack.org/docs/mlpack-git/doxygen/classmlpack_1_1rl_1_1QLearning.html#details

**Comment by bching28** [comment] 2017-11-20 05:53
Your descriptions are very detailed and extremely helpful.  Thank you.  I am now in the process of integrating the two (Glucose and mlpack) together.  I am still trying to write a file similar to cart_pole.hpp, which would be SATrestart.hpp in my case.  I am saving SATrestart.hpp in the mlpack folder (correct me if I am wrong to have placed it here).  

My states would have to come from variables and calculations done in Glucose.  So for example, one of my states would be the decision level value returned by the decisionLevel() function in Glucose.  How do I reference a variable in SATrestart.hpp that is calculated in Glucose?  Do I need all the mlpack Q-Learning files (`q_learning.hpp`, `q_learning_impl.hpp`, `q_learning_test.cpp`, and `SATrestart.hpp`) all in the Glucose directory?  Or is it as simple as using #include in all the files?

To sum up my above paragraph, the biggest question mark I have stems from the actual integration of the two source codes (Glucose and mlpack).  My hope when first conceptualizing this project was to simply take the reinforcement learning algorithm (Q-Learning) and integrate it into the source code of Glucose (in Solver.cc for instance).  However, in your cart_pole example, the states are calculated in the cart_pole.hpp file.  My problem is that the states are not going to be calculated in cart_pole.hpp, or SATrestart.hpp in my case.  It is calculated by Glucose as it is trying to solve a CNF satisfiability problem.  So I am just having a hard time wrapping my head around the integration of it all.  

I know this might sound confusing when first reading it since everything I mentioned are the thoughts running in my head right now about my problem, so please let me know if I can clarify something.  I am open to any suggestions you may have.

**Comment by zoq** [comment] 2017-11-21 12:44
> My hope when first conceptualizing this project was to simply take the reinforcement learning algorithm (Q-Learning) and integrate it into the source code of Glucose (in Solver.cc for instance).

You can do that, in fact, you don't have to modify any mlpack files, you can just link against mlpack, include the necessary files inside ``Solver.cc`` and implement the wrapper.

To link glucose against mlpack you have to modify the Makefile (``mtl/template.mk``) here is what I did:

add ``/path/to/libmlpack.so -larmadillo`` to ``LFLAGS``:

```
LFLAGS    ?= -Wall -lpthread /path/to/libmlpack.so -larmadillo 
```

and add the mlpack include directory to ``CFLAGS``:

```
CFLAGS    += -I$(MROOT) -I/path/to/mlpack/include/ -D __STDC_LIMIT_MACROS -D __STDC_FORMAT_MACROS
```


afterwards we can just include the header files in Solver.cc:

```c++
#include <mlpack/methods/ann/ffn.hpp>
#include <mlpack/methods/ann/init_rules/gaussian_init.hpp>
#include <mlpack/methods/ann/layer/layer.hpp>
#include <mlpack/methods/reinforcement_learning/q_learning.hpp>
#include <mlpack/methods/reinforcement_learning/environment/cart_pole.hpp>
#include <mlpack/methods/reinforcement_learning/policy/greedy_policy.hpp>
#include <mlpack/core/optimizers/adam/adam_update.hpp>
#include <mlpack/methods/reinforcement_learning/training_config.hpp>

using namespace mlpack;
using namespace mlpack::ann;
using namespace mlpack::optimization;
using namespace mlpack::rl;
```

The next step would be to write a simple Environment that uses the ``decisionLevel`` function inside the ``Solver`` file, I can probably help you with that if you can provide some details about how you get the states etc.

I hope this is helpfull.

**Comment by bching28** [comment] 2017-11-23 23:31
Hi @zoq 

So there was a slight change of plans for my project.  I am now trying to modify MiniSAT (https://github.com/niklasso/minisat) instead of Glucose because the restart policy and code is much easier to understand in MiniSAT.  It should not make too much of a difference since Glucose is based off of MiniSAT.  Also, the actions of the reinforcement learning agent have changed.  I am no longer trying to decide between whether to restart or not.  The agent will now decide between restarting with 4 different restart policies.

So, I was trying to link MiniSAT against mlpack now.  But there isn't a Makefile like you mentioned in the comment above in the `mtl` directory (`mtl/template.mk`) in MiniSAT.  MiniSAT does have a `Makefile` in its main directory but I don't see any instance of CFLAGS or LFLAGS.  Could you help me take a look at that?

Essentially, this is the block of code that handles the restart policy in MiniSAT:
<img width="778" alt="screen shot 2017-11-23 at 3 09 32 pm" src="https://user-images.githubusercontent.com/29585989/33190339-7ca6540a-d060-11e7-9627-50c1629bb0aa.png">

This while loop can be found in the `lbool Solver::solve_()` function.  The agent will choose 1 of the 4 restart policies (luby, geometric, linear, or uniform) based on the current state of the environment.  

As of right now, I am considering 4 different variables/calculations for identifying the states.  They are defined in lines 754 - 758 in my code below:
<img width="628" alt="screen shot 2017-11-23 at 3 15 33 pm" src="https://user-images.githubusercontent.com/29585989/33190406-4706bae6-d061-11e7-9890-47a426764045.png">

I placed my calculations in the `else` statement in the `lbool Solver::search(int nof_conflicts)` function.  If you take a look at the `Solver.cc` file, then it should be around line 740-750.  I saved the state values in a global array called `states[]` so that I can access the states in the `lbool Solver::solve_()` function.  The reason I placed my states calculation here is because this `if statement` occurs right before MiniSAT restarts and returns `status = l_Undef` to the while loop in the first screenshot.  I will need some kind of initial state, so I was thinking of setting all my states to 0 in the beginning.

And based on everything you are telling me from the comment above and on the include files, is it safe to assume that `Solver.cc` is essentially my version of `q_learning_test.cpp`? 

Thanks again and Happy Thanksgiving!

**Comment by zoq** [comment] 2017-11-25 16:31
> So, I was trying to link MiniSAT against mlpack now. But there isn't a Makefile like you mentioned in the comment above in the mtl directory (mtl/template.mk) in MiniSAT. MiniSAT does have a Makefile in its main directory but I don't see any instance of CFLAGS or LFLAGS. Could you help me take a look at that?

I can't test it right now, but it looks like you could modify:

```
MINISAT_CXXFLAGS = -I. -D __STDC_LIMIT_MACROS -D __STDC_FORMAT_MACROS -Wall -Wno-parentheses -Wextra
MINISAT_LDFLAGS  = -Wall -lz
```

instead of ``LFLAGS`` and ``CFLAGS``, let me know if that works.


> And based on everything you are telling me from the comment above and on the include files, is it safe to assume that Solver.cc is essentially my version of q_learning_test.cpp?

Yes, ``Solver.cc`` would be the place.

**Comment by bching28** [comment] 2017-11-25 18:25
I modified the following:
`MINISAT_CXXFLAGS` to be
```
MINISAT_CXXFLAGS = -I. -I/usr/local/include/mlpack/ -D __STDC_LIMIT_MACROS -D __STDC_FORMAT_MACROS -Wall -Wno-parentheses -Wextra
```
and `MINISAT_LDFLAGS` to be
```
MINISAT_LDFLAGS  = -Wall -lz -lpthread /usr/local/lib/libmlpack.so -larmadillo
```

I then added the following `#include` and `namespaces` to `Solver.cc`:
``` c++
#include <mlpack/methods/ann/ffn.hpp>
#include <mlpack/methods/ann/init_rules/gaussian_init.hpp>
#include <mlpack/methods/ann/layer/layer.hpp>
#include <mlpack/methods/reinforcement_learning/q_learning.hpp>
#include <mlpack/methods/reinforcement_learning/environment/cart_pole.hpp>
#include <mlpack/methods/reinforcement_learning/policy/greedy_policy.hpp>
#include <mlpack/core/optimizers/adam/adam_update.hpp>
#include <mlpack/methods/reinforcement_learning/training_config.hpp>

using namespace mlpack;
using namespace mlpack::ann;
using namespace mlpack::optimization;
using namespace mlpack::rl;
```

The very first error I am getting is this:
<img width="735" alt="screen shot 2017-11-25 at 10 08 34 am" src="https://user-images.githubusercontent.com/29585989/33233318-417471ea-d1c9-11e7-8086-f35b09d9f844.png">

So it's complaining about needing support for the ISO C++ 2011 standard (-std=c++11).  And then it complains about a whole bunch of files in boost and mlpack.  The screenshot only shows a snippet because there were just too many errors to include in this post.  I have a hunch that these errors are mostly caused by the need for support for the ISO C++ 2011 standard.  When I was trying to include mlpack files earlier into `Solver.cc`, I got that same error about the ISO C++ 2011 standard.  Do I simply need to add `-std=c++11` somewhere in the Makefile?

**Comment by zoq** [comment] 2017-11-25 18:52
Yeah, adding ``-std=c++11`` to ``MINISAT_CXXFLAGS`` should solve the build issue.

**Comment by bching28** [comment] 2017-11-25 19:02
Cool, adding `-std=c++11` solved basically all the errors.  I am seeing one more though:
<img width="733" alt="screen shot 2017-11-25 at 10 59 10 am" src="https://user-images.githubusercontent.com/29585989/33233747-c405d256-d1cf-11e7-8ecf-e15a8d520f24.png">

Does this require me to add `#include <cmath>` to `Solver.cc` or something related to that?

**Comment by zoq** [comment] 2017-11-25 19:10
Including ``#include <mlpack/core.hpp>`` first; this should solve the issue, it will include ``#include <mlpack/core/math/shuffle_data.hpp>``.

**Comment by bching28** [comment] 2017-11-25 19:41
That solved the math error.  Thanks!  Now aside from the warnings from the last screenshot, I am getting this message that it failed after I type in `make` in the terminal:
<img width="734" alt="screen shot 2017-11-25 at 11 39 23 am" src="https://user-images.githubusercontent.com/29585989/33234085-82c51080-d1d5-11e7-9514-f3e3c66b9afa.png">

**Comment by bching28** [comment] 2017-11-27 07:39
Hi @zoq 

I just finished writing `SATrestart.hpp` that I will use in `Solver.cc` in the following line (similar to line 61 in `q_learning_test.cpp`):
```
QLearning<SATrestart, decltype(model), AdamUpdate, decltype(policy)>
      agent(std::move(config), std::move(model), std::move(policy),
          std::move(replayMethod));
```
Can you take a look and see if you notice anything that might cause errors?  I can't test it currently until we figure out how to fix that compile error.  Here is the code for `SATrestart.hpp`:
``` c++
/**
#ifndef SRC_MLPACK_METHODS_REINFORCEMENT_LEARNING_ENVIRONMENT_SATRESTART_HPP_
#define SRC_MLPACK_METHODS_REINFORCEMENT_LEARNING_ENVIRONMENT_SATRESTART_HPP_

#include <mlpack/prereqs.hpp>
#include <minisat/core/Solver.h>
#include <math.h>

#include "mtl/Sort.h"
#include "core/Solver.h"
#include "core/Constants.h"
#include "utils/System.h"

namespace mlpack {
namespace rl {

class SATrestart {
	public:
		class State {
			public:
		        State() : data(dimension) // construct a state instance
		        { /* Nothing to do here. */ }

		        State(const arma::colvec& data) : data(data)
		        { /* Nothing to do here */ }

		        //! Modify the internal representation of the state.
		        arma::colvec& Data() { return data; }

			//! Get the number of variables assigned
			int numVarsAssigned() const {
				return data[0];
			}
			//! Modify the current number of variables assigned value
			int& numVarsAssigned() {
				return data[0];
			}

			//! Get the decision level
			int decLevel() const {
				return data[1];
			}
			//! Modify the current decision level value
			int& decLevel() {
				return data[1];
			}

			//! Get the number of conflicts since the last restart
			int confictsRestart() const {
				return data[2];
			}
			//! Modify the current number of conflicts since the last restart value
			int& conflictsRestart() {
				return data[2];
			}

			//! Get the number of learnt clauses
			int numLearnt() const {
				return data[3];
			}
			//! Modify the current number of learnt clauses value
			int& numLearnt() {
				return data[3];
			}

		        //! Encode the state to a column vector.
		        const arma::colvec& Encode() const { return data; }

		       //! Dimension of the encoded state...how many states we have
		      static constexpr size_t dimension = 4;

			private:
		        //! Locally-stored (number of variables assigned, decision level,
			//  conflicts since the last restart, number of learnt clauses).
		        arma::colvec data;
		};

		enum Action {
			// restart policies
			LUBY,
			GEOMETRIC,
			LINEAR,
			UNIFORM,

			// Track the size of the action space.
			size
		};

		SATrestart()
		{ /*do nothing here?*/ }

		double Sample (const State& state,
					const Action& action,
					State& nextState) const
		{
			// Restart
			// actions should be done here
			switch(action) {
				case LUBY:
					double rest_base = luby(restart_inc, curr_restarts);
					break;
				case GEOMETRIC:
					double rest_base = pow(restart_inc, curr_restarts);
					break;
				case LINEAR:
					double rest_base = restart_inc * curr_restarts;
					break;
				case UNIFORM:
					double rest_base = pow(2, 8); // 2^8 = 256
					break;
			}

			status = search(rest_base * restart_first);
			if (!withinBudget()) break;
			curr_restarts++;

			// Next State Calculations
			nextState.numVarsAssigned() = states[0];
			nextState.decLevel() = states[1];
			nextState.confictsRestart() = states[2];
			nextState.numLearnt() = states[3];

			// Reward Calculation
			double temp = (decisions2 - decisions1) / num_learnt_clauses;
			double reward = 1 / temp;
			return reward;
		}

		State InitialSample() const
		{
			// The starting sample could be random
			return State(arma::colvec(4) - 0); // idk what this actually does
		}


		/**
		* Whether given state is a terminal state.
		* @param state The desired state.
		* @return true if state is a terminal state, otherwise false.
		*/

		bool IsTerminal(const State& state) const
		{
			// Check if the current state is a terminal state.
			if (status == l_Undef) { // l_Undef == not IsTerminal
				return false;
			}
			else // otherwise if l_True or l_False, then IsTerminal
				return true;
		}
};

} // namespace rl
} // namespace mlpack

#endif /* SRC_MLPACK_METHODS_REINFORCEMENT_LEARNING_ENVIRONMENT_SATRESTART_HPP_ */
```

A couple questions I have:
1. Is it ok that `SATrestart() { /*do nothing here?*/ }` is empty?  I don't have any variables that I use in my `Sample()` function like `cart_pole.hpp`.
2. I just want the initial state values to be 0.  Is my `initialSample()` function correct in initializing the values to 0?
3. Am I correct in assuming that the action (choosing a restart policy in my case) will be performed in the `Sample()` function?  Essentially, I took the contents of the `while loop` from `Solver::solve_()` and placed it into my `Sample()` function.

**Comment by zoq** [comment] 2017-11-27 12:30
About the build error, I guess if you remove the ``--static`` from the Makefile it should build just fine. I'll take a closer look at the code once I get a chance.

**Comment by bching28** [comment] 2017-11-27 20:04
I will test out removing `--static` and let you know the results of that.  And thank you.  Looking forward to hearing back from you about the code.

**Comment by rcurtin** [comment] 2017-11-27 20:12
Hi @bching28, just a comment, I think many of the questions you are asking could probably be answered by experimenting with the code and inspecting it closely, so I'd encourage you to do that also instead of waiting on answers from mlpack maintainers---it could be faster and more illuminating to do that.

**Comment by bching28** [comment] 2017-11-27 20:36
Hi @rcurtin, I agree.  I will definitely be testing the code and experimenting with mlpack.  I am just running tests on the original, unmodified MiniSAT at the moment to obtain data and it's taking longer than I expected.  But once I finish my tests, I will continue to experiment with the code.  Thanks!

**Comment by bching28** [comment] 2017-12-06 23:15
Hey guys, just wanted to let you know that I am making pretty good progress.  I have a quick question.  So I've noticed that when the number of steps reaches `config.ExplorationSteps()`, the program throws an error out:
<img width="713" alt="screen shot 2017-12-06 at 3 12 27 pm" src="https://user-images.githubusercontent.com/29585989/33690327-e7fe8722-da97-11e7-91d9-77c390b4fb8c.png">

So for example,` config.ExplorationSteps() = 100;` is the default.  Once the number of steps reaches 101, the above error occurs.  I tested this by increasing `config.ExplorationSteps` to `200`.  I have kind of wondered what `config.ExplorationSteps()` and `config.TargetNetworkSyncInterval() `actually does.  Could you guys explain?

**Comment by zoq** [comment] 2017-12-07 13:39
Can you provide a simple example to reproduce the error?

At the start of the training process the epsilon value is often initialized to a large probability, to encourage exploration since we don't know much about the environment. The value is then annealed down to a small constant, to cool down the exploration, since we could assume the agent learned most of what it needs about the environment. This behavour is controled by the ``ExplorationSteps`` parameter.

The ``TargetNetworkSyncInterval``parameter controls the update process of the target network with the one you train.

**Comment by bching28** [comment] 2017-12-07 16:52
Sure, so I am having my SAT solver's main function set up the QLearning and initialize the agent.  The current setting for `ExplorationSteps` is `100` at the moment.  I have a `for loop` that basically solves the same SAT problem over and over again, but I use the same agent I initialized earlier.  In my case, each restart that the SAT solver performs corresponds to a `step`.  In the first for loop iteration, there might be 10 restarts.  Then, in the second loop iteration, or second instance of the SAT solver solving the problem, there would be 8 restarts.  Then 5, 11, and 8 restarts and so on and so forth.  By the time the cumulative number of restarts for all the for loop iterations reaches the size of `ExplorationSteps`, which is `100` in this case, I get the error that I screenshotted in my previous comment.  Please let me know if I can clarify something else.

So base on your description above, does it mean that if I increase `ExplorationSteps` to let's say `1000`, I am still exploring for the first 1000 steps that the agent performs?  When does annealing occur?  I am asking because right now, I don't really notice a performance improvement in my SAT solver.  The results look sort of scattered, and I am wondering if it is still doing exploration to find a better policy.

**Comment by zoq** [comment] 2017-12-08 14:23
Thanks for the explanation, do you mind to provide a minimal code sample that I can use to reproduce the issue, perhaps a modification of the existing test is enough?

Annealing kicks in once the current step is > as the given ExplorationSteps: https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/reinforcement_learning/q_learning_impl.hpp#L203

**Comment by rcurtin** [comment] 2018-01-24 23:51
Closing for inactivity---please feel free to reopen if needed.

**Closed by rcurtin** 2018-01-24 23:51 UTC
