### ISSUE TITLE
Limiting tree depth of random_forest 

### ISSUE THREAD

**Issue by yanivbi** [mlpack/mlpack#1910] opened 2019-05-30 05:57 UTC
Is there a way to limit the maximum depth of each tree in random_forest?
This is a prevalent option for configuring random forests.

**Comment by rcurtin** [comment] 2019-06-01 13:48
Hi @yanivbi, I've said to others in the past that `minimum_leaf_size` is similar way to achieve the same goal, but at this point I've said that too many times and I think it is time to add the support.  So, at the moment, there's not a way to limit the maximum depth.

If you are (or anyone else reading this issue is) interested in contributing one, basically what would need to happen is that the constructors for the `DecisionTree` class would need an extra final parameter `maximum_depth`.  Then, if `maximum_depth == 1`, the node should not be allowed to split during training; otherwise, when it splits during training, the children should be trained with maximum depth set to `maximum_depth - 1`.

In any case, if you don't have the time, that's okay, I will get to it eventually (but I am not sure exactly when that will be).

**Comment by Rajlaxmi** [comment] 2019-06-01 16:32
Hi,
I would like to pick this up.

**Comment by zoq** [comment] 2019-06-04 19:48
@Rajlaxmi looks like @Yashwants19 already opened a PR, but please feel free to comment on the PR.

**Comment by rcurtin** [comment] 2019-06-21 01:05
Since #1916 is merged, the issue is fixed.  The `maximum_depth` parameter will be available starting with the next release of mlpack, but if you want "early access" you can always build from the git master branch and it'll be available. :+1: I'll close the issue, but if you have any problems in the future please don't hesitate to open other issues.

**Closed by rcurtin** 2019-06-21 01:05 UTC
Labels: c: automatic bindings, c: methods, good first issue, help wanted, s: keep open, t: feature request
