### ISSUE TITLE
[Julia] Segfault + abort in hoeffding_tree call

### ISSUE THREAD

**Issue by quinnj** [mlpack/mlpack#3300] opened 2022-11-01 06:06 UTC
#### Issue description

Segfault + abort when calling `hoeffding_tree` from Julia mlpack.jl bindings.

#### Your environment

 * version of mlpack: Julia v4.0.0
 * operating system: MacOS M1
 * compiler: whatever BinaryBuilder/Yggdrasil is using?
 * version of dependencies (Boost/Armadillo): armadillo_jll v11.2.1+0, boost_jll v1.79.0+0
 * any other environment information you think is relevant:

#### Steps to reproduce

See the linked file here:
* [mlpack_crash.jl.gz](https://github.com/mlpack/mlpack/files/9907325/mlpack_crash.jl.gz)

Results in:

```
[INFO ] 0 mappings in dimension 0.
[INFO ] 10 mappings in dimension 1.
[INFO ] 0 mappings in dimension 2.
[INFO ] 0 mappings in dimension 3.
[INFO ] 0 mappings in dimension 4.
[INFO ] 0 mappings in dimension 5.
[INFO ] 2 mappings in dimension 6.
[INFO ] 4 mappings in dimension 7.
[INFO ] 6 mappings in dimension 8.
[INFO ] 8 mappings in dimension 9.

signal (11): Segmentation fault: 11
in expression starting at /Users/quinnj/.julia/dev/mlpack_crash.jl:7
tiny_free_list_remove_ptr at /usr/lib/system/libsystem_malloc.dylib (unknown line)
Allocations: 2907 (Pool: 2897; Big: 10); GC: 0
julia(49134,0x102830580) malloc: *** error for object 0x2: pointer being freed was not allocated
julia(49134,0x102830580) malloc: *** set a breakpoint in malloc_error_break to debug

signal (6): Abort trap: 6
in expression starting at /Users/quinnj/.julia/dev/mlpack_crash.jl:7
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 2907 (Pool: 2897; Big: 10); GC: 0
[1]    49134 abort      /Users/quinnj/juliam1/bin/julia /Users/quinnj/.julia/dev/mlpack_crash.jl
```

**Comment by rcurtin** [comment] 2022-11-01 15:41
I think I succeeded in reproducing this, although the manifestation of the problem is a little different on my Linux system:

```
julia> include("mlpack_crash.jl")
[INFO ] 0 mappings in dimension 0.
[INFO ] 10 mappings in dimension 1.
[INFO ] 0 mappings in dimension 2.
[INFO ] 0 mappings in dimension 3.
[INFO ] 0 mappings in dimension 4.
[INFO ] 0 mappings in dimension 5.
[INFO ] 2 mappings in dimension 6.
[INFO ] 4 mappings in dimension 7.
[INFO ] 6 mappings in dimension 8.
[INFO ] 8 mappings in dimension 9.
corrupted double-linked list
```

I'll start digging over the next couple days.  Thanks for the report!

**Comment by rcurtin** [comment] 2022-11-03 20:10
@quinnj the fix is in three parts:

 - #3304: we need to catch all exception types in the Julia bindings.  (This is just a simple 'oops'... one-line fix.)
 - #3305: correct one-indexed Julia data mapping to zero-indexed C++ data.  (This one was a bit more involved.)
 - In Yggdrasil, for the next release, I'll need to make sure the `-DARMA_NO_DEBUG` option is *not* set; if that is set, no bounds checks happen, and you get a segfault/stacktrace instead of an exception when something like what happened here is wrong.

There are a couple of bugfixes floating around that have yet to be merged, but once all that's done, we can do a 4.0.1 release and then I think that should solve the issue.  (And if we're lucky, there won't be a "next" issue that you immediately encounter :smile:)  ETA is probably a couple weeks tops, just enough time to review and collect all the little patches and merge them.

**Comment by quinnj** [comment] 2022-11-03 20:13
Sounds good, thanks!

**Comment by conradsnicta** [comment] 2022-11-04 00:55
> In Yggdrasil, for the next release, I'll need to make sure the `-DARMA_NO_DEBUG` option is _not_ set; if that is set, no bounds checks happen, and you get a segfault/stacktrace instead of an exception when something like what happened here is wrong.

Having debugging enabled is a good idea in almost all cases.

In performance critical parts that directly access matrix elements (as opposed to entire columns or rows), it's possible to selectively skip the bounds checks by using the `X.at(row,col)` operator instead of the `X(row,col)` operator.  Similar reasoning applies to `X(i)` vs `X.at(i)`.  This is a more nuanced approach than having `ARMA_NO_DEBUG` defined, which disables almost all run-time checks. More details: https://arma.sourceforge.net/docs.html#element_access

This selective skipping of bounds checks for element access can provide some speedup (~20%), but obviously the code must be first thoroughly debugged to make sure all element access is within bounds.  It's generally useful when the dimensions of the matrix are explicitly known and directly read as part of the loop structure, so the likelihood of bugs in that case is low.  For example: `for(uword i=0; i < X.n_elem; ++i)  { X.at(i) = ...; }`

**Comment by conradsnicta** [comment] 2022-11-21 04:39
@rcurtin In the vast majority of cases, I don't think there would be much speed difference (if any) when compiling without `ARMA_NO_DEBUG` (ie. having the bounds checks and other checks enabled).

mlpack spends much of its execution time in vector or matrix operations (matrix mul, SVD, etc), and most of those end up being farmed out to BLAS and LAPACK via Armadillo.  The remainder is stuff like submatrix access, which Armadillo handles efficiently already.  The overhead of the checks in these cases is negligible, and the checks really do help with tracking down problems at runtime.

**Comment by conradsnicta** [comment] 2022-12-23 08:40
#3322 has been merged; not sure if the remaining TODO item from https://github.com/mlpack/mlpack/issues/3300#issuecomment-1302612245 still applies:

> * In Yggdrasil, for the next release, I'll need to make sure the `-DARMA_NO_DEBUG` option is _not_ set; if that is set, no bounds checks happen, and you get a segfault/stacktrace instead of an exception when something like what happened here is wrong.

**Comment by rcurtin** [comment] 2022-12-23 14:49
Right, I'll handle that when I update the Julia package to 4.0.1.  So I think we can go ahead and close this. :+1:  (I'll post another comment here for @quinnj when that's done.  Within a week probably?)

**Comment by rcurtin** [comment] 2022-12-30 15:16
The Julia package will be updated to 4.0.1 probably by tomorrow: https://github.com/JuliaRegistries/General/pull/74809
So, I'll go ahead and close this.  Thanks again---and feel free to open more issues if there are more problems. :+1:

**Closed by rcurtin** 2022-12-30 15:16 UTC
Labels: t: bug report, c: automatic bindings
