### ISSUE TITLE
A possible bug in neighborhood-based CF implementation

### ISSUE THREAD

**Issue by Wenhao-H** [mlpack/mlpack#1243] opened 2018-02-13 17:08 UTC
Hi,

I noticed that in cf.cpp, when calculating the nearest neighbors of a certain user _users(i)_, the user _users(i)_ itself is returned as one of the nearest neighbors:

https://github.com/mlpack/mlpack/blob/5662319dc25d78107e470f4695678956c3f98a95/src/mlpack/methods/cf/cf.cpp#L82-L99

I suppose _users(i)_ should be excluded from the list of nearest neighbors in a neighborhood-based CF.  The code should be easy to fix. But as this implementation seems to be a combination of neighborhood-based method and latent factor based method, i'm not sure whether it's a bug here. If it's a bug I will work on it.

**Comment by Wenhao-H** [comment] 2018-02-14 05:38
I modified the code to print all pairs of neighbors:

    for (size_t j = 0; j < neighborhood.n_rows; ++j) {
      averages += w * h.col(neighborhood(j, i));
      std::cout << "(" << users(i) << "," << neighborhood(j ,i) << ")" << std::endl;
    }

and run a simple program:

```
include <mlpack/methods/cf/cf.hpp>

using namespace mlpack::cf;
using namespace mlpack::amf;
using namespace mlpack;

int main() {
  arma::mat dataset;
  data::Load("./data/GroupLensSmall.csv", dataset);
  CF cf(dataset, amf::NMFALSFactorizer(), 3);
  arma::Mat<size_t> recommendations;
  cf.GetRecommendations(5, recommendations);
  return 0;
}
```

And the printed result shows that each user is selected as the nearest neighbor of itself:
```
(0,0)
(0,58)
(0,6)
(1,1)
(1,73)
(1,191)
(2,2)
(2,3)
(2,126)
(3,3)
(3,2)
(3,126)
(4,4)
(4,76)
(4,24)
(5,5)
(5,9)
(5,84)
```

**Comment by rcurtin** [comment] 2018-02-14 14:47
Thanks for confirming that this is an issue, I appreciate that.  At this point if you want to fix it we can definitely merge a PR for that.  I would say the easiest way to fix this might be to search for `numUsersForSimilarity + 1`, then simply ignore the first row of results.  Modifying `NeighborSearch` for that would be, I think, a little too difficult and the runtime gain would likely be negligible at best.  But maybe you have another solution in mind, so don't feel restricted to what I said. :)

**Comment by Wenhao-H** [comment] 2018-02-14 15:00
I agree with your solution. That's what I had in mind too. I will fix it and make a PR:)

**Comment by rcurtin** [comment] 2018-02-16 14:14
From the discussion in #1251---it turns out, this is actually not a bug but intentional.  So I will close this.

**Closed by rcurtin** 2018-02-16 14:14 UTC
Labels: T: defect
