### ISSUE TITLE
conda environment - R bindings - can't find R modules

### ISSUE THREAD

**Issue by zoq** [mlpack/mlpack#2738] opened 2020-11-25 22:48 UTC
This issue has to do with mlpack's R bindings in a conda environment. Ideally, if you're interested in solving this, you should be familiar with how these bindings are used, and have some knowledge of the automatic bindings system that generates these Python bindings, especially the cmake part.

#### Issue description

When I try to build mlpack's R bindings it fails because it can't find the necessary dependencies: RcppArmadillo, RcppEnsmallen, BH and roxygen2. So I guess

* https://github.com/mlpack/mlpack/blob/f6a84dc2400f66a7e9969833bf01d4617e6d6b24/src/mlpack/bindings/R/CMakeLists.txt
* https://github.com/mlpack/mlpack/blob/f6a84dc2400f66a7e9969833bf01d4617e6d6b24/CMake/FindRModule.cmake 

needs some help to find the correct modules.

#### Steps to reproduce

1. Install anaconda environment.
2. Install build dependencies.

```
conda install -c conda-forge -c r r-base=4.03 r-rcpp r-rcpparmadillo libblas liblapack r-rcppensmallen r-bh r-roxygen2 cmake git cotire boost armadillo ensmallen openblas cereal
```

on my system this provides the following output:

```
Downloading and Extracting Packages
xorg-libice-1.0.10   | 57 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
xorg-libxrender-0.9. | 31 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
r-pkgbuild-1.1.0     | 156 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-rstudioapi-0.13    | 281 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-xfun-0.19          | 293 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
libxml2-2.9.10       | 1.3 MB    | ################################################################################################################################################################################################################################################################################### | 100% 
libuuid-2.32.1       | 26 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
r-mime-0.9           | 51 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
r-processx-3.4.4     | 295 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-rcppensmallen-0.2. | 248 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
libwebp-base-1.1.0   | 864 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-rlang-0.4.8        | 1.0 MB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-fansi-0.4.1        | 195 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-magrittr-2.0.1     | 212 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
gsl-2.6              | 3.1 MB    | ################################################################################################################################################################################################################################################################################### | 100% 
harfbuzz-2.7.2       | 1.8 MB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-purrr-0.3.4        | 410 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-rprojroot-2.0.2    | 110 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-xml2-1.3.2         | 247 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-highr-0.8          | 58 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
r-withr-2.3.0        | 216 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-bh-1.72.0_3        | 10.4 MB   | ################################################################################################################################################################################################################################################################################### | 100% 
xorg-xproto-7.0.31   | 72 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
fontconfig-2.13.1    | 324 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
xorg-libxext-1.3.4   | 51 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
r-callr-3.5.1        | 388 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-markdown-1.1       | 143 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
xorg-libsm-1.2.3     | 25 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
r-r6-2.5.0           | 89 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
r-rcpp-1.0.5         | 2.0 MB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-glue-1.4.2         | 142 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
cairo-1.16.0         | 1.5 MB    | ################################################################################################################################################################################################################################################################################### | 100% 
libtiff-4.1.0        | 618 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
xorg-xextproto-7.3.0 | 27 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
r-base-4.0.3         | 23.7 MB   | ################################################################################################################################################################################################################################################################################### | 100% 
r-commonmark-1.7     | 152 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-crayon-1.3.4       | 747 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
xorg-libx11-1.6.12   | 917 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-desc-1.2.0         | 291 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-evaluate-0.14      | 81 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
libarchive-3.4.3     | 1.6 MB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-backports-1.2.0    | 99 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
r-roxygen2-7.1.1     | 657 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-yaml-2.2.1         | 117 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-prettyunits-1.1.1  | 40 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
r-knitr-1.30         | 1.3 MB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-pkgload-1.1.0      | 167 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-assertthat-0.2.1   | 70 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
r-brew-1.0_6         | 93 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
r-stringi-1.5.3      | 800 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
pcre2-10.35          | 683 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
xorg-renderproto-0.1 | 8 KB      | ################################################################################################################################################################################################################################################################################### | 100% 
r-ps-1.4.0           | 266 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
sed-4.8              | 264 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-stringr-1.4.0      | 209 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-cli-2.2.0          | 443 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-digest-0.6.27      | 213 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
r-rcpparmadillo-0.10 | 1.2 MB    | ################################################################################################################################################################################################################################################################################### | 100% 
pango-1.42.4         | 533 KB    | ################################################################################################################################################################################################################################################################################### | 100% 
xorg-kbproto-1.0.7   | 26 KB     | ################################################################################################################################################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

From the output we can see that the correct packages are installed.

3. Build mlpack

```
git clone https://github.com/mlpack/mlpack.git
cd mlpack
mkdir build
cd build
cmake -DBUILD_JULIA_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_R_BINDINGS=ON ..
```

on my system this provides the following output:

```
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /root/miniconda3/bin/x86_64-conda_cos6-linux-gnu-cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /root/miniconda3/bin/x86_64-conda_cos6-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.7.10 loaded.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Armadillo: /root/miniconda3/lib/libarmadillo.so (found suitable version "9.900.4", minimum required is "8.400.0") 
-- Found StbImage: /usr/include/stb/  
-- Found Ensmallen: /root/miniconda3/include (found suitable version "2.15.1", minimum required is "2.10.0") 
-- Found cereal: /root/miniconda3/include (found suitable version "1.3.0", minimum required is "1.1.2") 
-- Found Boost: /root/miniconda3/include (found suitable version "1.70.0", minimum required is "1.58")  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found Git: /root/miniconda3/bin/git (found version "2.29.2") 
-- gitversion.hpp is already up to date.
CMake Warning at CMakeLists.txt:587 (message):
  txt2man not found; man pages will not be generated.


-- Not building Julia bindings.
-- Not building Markdown bindings.
-- Not building Python bindings.
-- Not building Go bindings.
-- Found R: /root/miniconda3/bin/R (found suitable version "4.0.3", minimum required is "4.0") 
-- Found R_roxygen2: /root/miniconda3/lib/R/library/roxygen2  
CMake Warning at CMake/FindRModule.cmake:47 (message):
  Unsuitable version of R module Rcpp (0.12.12 or greater required).
Call Stack (most recent call first):
  src/mlpack/bindings/R/CMakeLists.txt:37 (find_r_module)


-- Could NOT find R_Rcpp (missing: R_RCPP) 
CMake Warning at CMake/FindRModule.cmake:47 (message):
  Unsuitable version of R module RcppArmadillo (0.8.400.0 or greater
  required).
Call Stack (most recent call first):
  src/mlpack/bindings/R/CMakeLists.txt:41 (find_r_module)


-- Could NOT find R_RcppArmadillo (missing: R_RCPPARMADILLO) 
CMake Warning at CMake/FindRModule.cmake:47 (message):
  Unsuitable version of R module RcppEnsmallen (0.2.10.0 or greater
  required).
Call Stack (most recent call first):
  src/mlpack/bindings/R/CMakeLists.txt:45 (find_r_module)


-- Could NOT find R_RcppEnsmallen (missing: R_RCPPENSMALLEN) 
CMake Warning at CMake/FindRModule.cmake:47 (message):
  Unsuitable version of R module BH (1.58 or greater required).
Call Stack (most recent call first):
  src/mlpack/bindings/R/CMakeLists.txt:49 (find_r_module)


-- Could NOT find R_BH (missing: R_BH) 
-- Could NOT find R_testthat (missing: R_TESTTHAT) 
CMake Error at src/mlpack/bindings/R/CMakeLists.txt:64 (message):
  Could not Build R Bindings, Following modules are not available:

      - Rcpp
      - RcppArmadillo
      - RcppEnsmallen
      - BH
      - testthat


-- Configuring incomplete, errors occurred!
See also "/mlpack/build/CMakeFiles/CMakeOutput.log".
See also "/mlpack/build/CMakeFiles/CMakeError.log".
```

We can see that cmake isn't able to find the R-modules.

#### Expected behavior

cmake is able to find the installed R modules, and is able to build the R bindings.

#### Actual behavior

cmake isn't able to find the installed R modules and fails to generate a makefile.

I include @Yashwants19 here, as he built the R bindings and might be able to provide some additional pieces of information.

**Comment by Yashwants19** [comment] 2020-11-26 07:20
I am not sure, why `FindRModule.cmake` is not working in your system.
Locally I am not able to reproduce the same error. Here is the output:
```
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/asus/miniconda3/envs/r-bindings/bin/x86_64-conda_cos6-linux-gnu-cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/asus/miniconda3/envs/r-bindings/bin/x86_64-conda_cos6-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.7.10 loaded.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Armadillo: /home/asus/miniconda3/envs/r-bindings/lib/libarmadillo.so (found suitable version "9.900.4", minimum required is "8.400.0") 
-- Found StbImage: /usr/local/include/stb/  
-- Found Ensmallen: /home/asus/miniconda3/envs/r-bindings/include (found suitable version "2.15.1", minimum required is "2.10.0") 
-- Found cereal: /home/asus/miniconda3/envs/r-bindings/include (found suitable version "1.3.0", minimum required is "1.1.2") 
-- Found Boost: /home/asus/miniconda3/envs/r-bindings/include (found suitable version "1.74.0", minimum required is "1.58")  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found Git: /home/asus/miniconda3/envs/r-bindings/bin/git (found version "2.29.2") 
-- gitversion.hpp is already up to date.
-- Not building Julia bindings.
-- Not building Markdown bindings.
-- Not building Python bindings.
-- Not building Go bindings.
-- Found R: /home/asus/miniconda3/envs/r-bindings/bin/R (found suitable version "4.0.3", minimum required is "4.0") 
-- Found R_roxygen2: /home/asus/miniconda3/envs/r-bindings/lib/R/library/roxygen2  
-- Found R_Rcpp: /home/asus/miniconda3/envs/r-bindings/lib/R/library/Rcpp (found suitable version "1.0.5", minimum required is "0.12.12")  
-- Found R_RcppArmadillo: /home/asus/miniconda3/envs/r-bindings/lib/R/library/RcppArmadillo (found suitable version "0.10.1.2.0", minimum required is "0.8.400.0")  
-- Found R_RcppEnsmallen: /home/asus/miniconda3/envs/r-bindings/lib/R/library/RcppEnsmallen (found suitable version "0.2.15.0.1", minimum required is "0.2.10.0")  
-- Found R_BH: /home/asus/miniconda3/envs/r-bindings/lib/R/library/BH (found suitable version "1.72.0.3", minimum required is "1.58")  
-- Found R_testthat: /home/asus/miniconda3/envs/r-bindings/lib/R/library/testthat  
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- CXX target mlpack cotired.
-- CXX target mlpack_test cotired.
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.13") found components: doxygen missing components: dot
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/asus/conda/mlpack/build
(r-bindings)
```

In our CMake script `Rscript` is responsible for finding these module, may be in your env `Rscript` is not working properly.
Can you please try to run `Rscript -e "find.package('Rcpp')"` and `R -e "find.package('Rcpp')"` in your conda env and see the resulting output.

**Comment by zoq** [comment] 2020-11-26 14:13
Output of `Rscript -e "find.package('Rcpp')`:

```
1] "/root/miniconda3/lib/R/library/Rcpp"
```
Output of `R -e "find.package('Rcpp')"`

```
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> find.package('Rcpp')
[1] "/root/miniconda3/lib/R/library/Rcpp"
> 
> 
```

Output of `Rscript -e "packageVersion('Rcpp')"`:

```
[1] '1.0.5'
```

Output of `R -e "packageVersion('Rcpp')"`:

```
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> packageVersion('Rcpp')
[1] '1.0.5'
> 
> 
```

Btw. I'm building in a fresh docker container.

**Comment by Yashwants19** [comment] 2020-11-26 15:06
I guess the problem is here:
https://github.com/mlpack/mlpack/blob/f6a84dc2400f66a7e9969833bf01d4617e6d6b24/CMake/FindRModule.cmake#L28-L30
I think so by altering the regex, we can solve this.
I wrote this by keeping this(`[1] ‘1.0.5’`) into mind, but after looking at your output(`[1] '1.0.5'`) it seems that we expect different format also i.e (not `‘ ’` only this but also `' '` this).

**Comment by coatless** [comment] 2020-12-08 22:32
@zoq I think with it being on CRAN, the `conda` bindings can be setup a bit more easily. I'll take a look into it this upcoming weekend.

**Comment by zoq** [comment] 2020-12-18 17:57
Ohh, yeah, totally.

**Comment by coatless** [comment] 2020-12-19 21:45
@zoq should appear on `conda-forge` shortly. Added a recipe for `r-mlpack` in conda-forge/staged-recipes#13523.

**Comment by zoq** [comment] 2020-12-19 21:46
> @zoq should appear on `conda-forge` shortly. Added a recipe for `r-mlpack` in [conda-forge/staged-recipes#13523](https://github.com/conda-forge/staged-recipes/pull/13523).

You are awesome.

**Comment by coatless** [comment] 2021-01-02 18:50
@zoq now on `conda-forge`

https://anaconda.org/conda-forge/r-mlpack

This can be closed out.

**Comment by rcurtin** [comment] 2021-01-05 20:53
Awesome, I'll go ahead and close the issue. 🚀

**Closed by rcurtin** 2021-01-05 20:53 UTC
Labels: c: automatic bindings, c: build system, help wanted, t: bug report
