### ISSUE TITLE
Compiling Error Related with HDF5

### ISSUE THREAD

**Issue by hl-xue** [mlpack/mlpack#2180] opened 2020-02-06 13:36 UTC
Hello, 

When I compile my program with "g++ -fopenmp -lmlpack -larmadillo", I met a warning and several errors (I listed here the top 4):
```
/usr/bin/ld: warning: libhdf5_serial.so.100, needed by /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libarmadillo.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libarmadillo.so: undefined reference to `H5Tcreate@HDF5_SERIAL_1.8.7'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libarmadillo.so: undefined reference to `H5Tinsert@HDF5_SERIAL_1.8.7'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libarmadillo.so: undefined reference to `H5T_NATIVE_INT_g@HDF5_SERIAL_1.8.7'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libarmadillo.so: undefined reference to `H5Sget_simple_extent_ndims@HDF5_SERIAL_1.8.7'
```
I have already installed HDF5 on my computer with `sudo apt-get install libhdf5-serial-dev`. Do you have any idea why do these occur please ?

Thanks a lot !

**Comment by kartikdutt18** [comment] 2020-02-06 13:49
Hi @hl-xue, Did you recompile armadillo after install HDF5 ? 
If not, could you try that. This is in reference to this [conversation](https://github.com/mlpack/mlpack/issues/1127#issuecomment-333116801)
Another reason might be multiple versions of HDF5 installed.
I am not sure if this was of any help, However a member of this organization will provide better insight.

**Comment by hl-xue** [comment] 2020-02-06 14:08
Yes ! Thanks a lot !

**Comment by zoq** [comment] 2020-02-06 18:37
@hl-xue looks like the problem is solved, so I will close this one, feel free to reopen the issue if there is anything else we should clarify.

**Closed by zoq** 2020-02-06 18:37 UTC
Labels: s: answered, t: question
