### ISSUE TITLE
Structure of probabilities and predictions matrices after Classify() on RandomForest.

### ISSUE THREAD

**Issue by jknightmmcs** [mlpack/mlpack#2538] opened 2020-07-24 08:11 UTC
Hello, people!

Not sure if this is an issue, but I need to understand what's happening here.

Here is a :[sample app](https://mlpack.org/doc/mlpack-3.1.0/doxygen/sample_ml_app.html). I built it, no problems found. 

After investigating the code structure, I have found a sort of inconsistency:
Prediction result is taken as:

`u64 result = predictions.at(0);`

When I tried to look at the probabilities, I have found out that both predictions and probabilities matrices contain information for every feature from a given sample: let's say that we've got 10 features in a sample, then predictions.n_elem == 10, and probabilities.n_elem == 20.

I'm sort of confused. What I expected to see in probabilities is a row of float values of size of numClasses(). Is what we get from predictions.at(0) an actual class prediction? Or some intermediate value? What is the structure of probabilities and predictions matrices, and how should they be interpreted after Classify() call? How to get actual probabilities for each class?

Is there a place to read about such things? [Documentation](https://mlpack.org/doc/mlpack-git/doxygen/classmlpack_1_1tree_1_1RandomForest.html#abddb69ee5b97027cd4eebd398bf39ac6) doesn't seem to help.

Is this scheme the same for other classifiers in the library? Let's say AdaBoost, or others like that.

**Comment by rcurtin** [comment] 2020-07-24 21:48
Hey @jknightmmcs, glad you were able to get things running without issues.

I'm not sure I understand the question entirely though.  If you have a `RandomForest` object and you call the overload of `Classify()` that you linked to (which takes a single point `const VecType& point`, and sets a predicted class `size_t& prediction` and class probabilities `arma::vec& probabilities`), this would result in `prediction` holding the ID of the most likely class, and `probabilities` would be a vector of length equal to the number of classes, and each element would be some measure of probability (note: not necessarily statistically valid!) associated with the prediction.

If you instead call the `Classify()` overload that takes many points ([this one](https://mlpack.org/doc/mlpack-git/doxygen/classmlpack_1_1tree_1_1RandomForest.html#a255d0a8b26a14cfd6a1f745568b83017)), then it should work the way you described.  Remember that mlpack (/armadillo) represents data in column-major form, so the input `MatType& data` should have, e.g., 10 columns (10 points) and d dimensions.  Then, after `Classify()` is called, `predictions.n_elem` should be 10 just like you wrote, and `probabilities.n_elem` would be 20 if there were only two classes.  Specifically, `probabilities` would have 10 columns (just like `data`) and 2 rows (one holding the "probability" of each class for a given point).

That's the scheme for all the classifiers in the library.

There is a [short tutorial](https://mlpack.org/doc/mlpack-git/doxygen/matrices.html) discussing the scheme of representing points as column-major in mlpack.  Maybe that is helpful?

Anyway, I'm not completely sure if I've accurately answered your question.  If I didn't just let me know.  If you can provide reproducible code samples, that makes it easier to answer the right question too. :)

**Comment by jknightmmcs** [comment] 2020-07-25 08:20
I'm sorry, but this doesn't really answer my question :)

Here is a sample code, a bit modified sample app that I linked in the first post:
```

#include "mlpack/core.hpp"
#include "mlpack/methods/random_forest/random_forest.hpp"
#include "mlpack/methods/decision_tree/random_dimension_select.hpp"
#include "mlpack/core/cv/k_fold_cv.hpp"
#include "mlpack/core/cv/metrics/accuracy.hpp"
#include "mlpack/core/cv/metrics/precision.hpp"
#include "mlpack/core/cv/metrics/recall.hpp"
#include "mlpack/core/data/load_csv.hpp"

using namespace arma;
using namespace mlpack;
using namespace mlpack::tree;
using namespace mlpack::cv;

#include <iostream>
#include <sstream>

/*
   This sample app covers a brief end-to-end ML workflow
   as you would do in a real-life application. Including:
   - Loading and preparing a dataset
   - Training (Random Forest as example)
   - Computing the training accuracy
   - Cross-Validation using K-Fold
   - Metrics gathering (accuracy, precision, recall, F1)
   - Saving the trained model
   - Loading the model
   - Classifying a new sample

   Assumptions:
   - No labels normalization required
 */
int main()
{
    cout << "[SAMPLE:BEGIN]";

    // (1) Load the dataset
    cout << "\nLoading dataset...";

    mat dataset;

    // CSV is loaded transposed (columns are samples, rows are dimensions)
    bool loaded = mlpack::data::Load("out_100_500_1.csv", dataset);
    // bool loaded = mlpack::data::Load("out_1500_2000_1.csv", dataset);

    if (!loaded)
        return -1;

    // Remove TrackID row
    dataset.shed_row(0);

    Row<size_t> labels;

    // Extract the labels from the last dimension of the training set
    labels = conv_to<Row<size_t>>::from(dataset.row(dataset.n_rows - 1));

    // Remove the labels from the training set
    dataset.shed_row(dataset.n_rows - 1);

    // (2) Training
    cout << "\nTraining...";
    const size_t numClasses      = 2;
    const size_t minimumLeafSize = 20;
    const size_t numTrees        = 10;

    RandomForest<GiniGain, RandomDimensionSelect> rf;

    rf = RandomForest<GiniGain, RandomDimensionSelect>(dataset, labels,
                                                       numClasses, numTrees, minimumLeafSize);

    Row<size_t> predictions;
    rf.Classify(dataset, predictions);

    const size_t correct = arma::accu(predictions == labels);

    cout << "\nTraining Accuracy: " << (double(correct) / double(labels.n_elem));

    // (3) Cross-Validation
    cout << "\nCross-Validating...";
    const size_t k = 10;

    KFoldCV<RandomForest<GiniGain, RandomDimensionSelect>, Accuracy> cv(k, dataset, labels, numClasses);

    double cvAcc = cv.Evaluate(numTrees, minimumLeafSize);
    cout << "\nKFoldCV Accuracy: " << cvAcc;

    double cvPrecision = Precision<Binary>::Evaluate(rf, dataset, labels);
    cout << "\nPrecision: " << cvPrecision;

    double cvRecall = Recall<Binary>::Evaluate(rf, dataset, labels);
    cout << "\nRecall: " << cvRecall;

    // (4) Save the model
    cout << "\nSaving model...";
    mlpack::data::Save("mymodel.xml", "model", rf, false);

    // (5) Load the model
    cout << "\nLoading model...";
    mlpack::data::Load("mymodel.xml", "model", rf);

    // (6) Classify a new sample
    cout << "\nClassifying a new sample...";
    // Should classify as "1"
    mat sample("2 12 2 13 1 2 2 1 3 24 3 1 1 1 1 1 0 1 0 1 0 0 0");

    mat probabilities;

    rf.Classify(sample, predictions, probabilities);

    u64 result = predictions.at(0);

    cout << "\nClassification result: " << result << " , Probabilities: " <<
        probabilities.at(0) << "/" << probabilities.at(1) << endl;

    std::ostringstream stream;

    for (int elem = 0; elem < probabilities.n_elem; elem++)
        stream << probabilities.at(elem) << " ";

    // 0.270892 0.729108 0.270892 0.729108 0.270892 0.729108 0.270892 0.729108 0.270892 0.729108 0.270892 0.729108 0.258243 0.741757
    // 0.376801 0.623199 0.195838 0.804162 0.311864 0.688136 0.165739 0.834261 0.365556 0.634444 0.440944 0.559056 0.733321 0.266679
    // 0.242307 0.757693 0.560706 0.439294 0.314666 0.685334 0.502731 0.497269 0.572397 0.427603 0.345155 0.654845 0.352298 0.647702
    // 0.362298 0.637702 0.362298 0.637702

    stream << std::endl;

    for (int elem = 0; elem < predictions.n_elem; elem++)
        stream << predictions.at(elem) << " ";

    cout << stream.str();

    // 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1

    cout << "\n[SAMPLE:END]\n";
    return 0;
}
```

You can see that we have exactly 46 floating-point probability numbers, along with 23 prediction numbers in output of the program.
In the file `german.csv` there is exactly 23 feature columns, and one label column at the end.
From what I understand, what we're looking at is a binary classifier.

When we put a single sample into it (this is what happens here with Classify() call), we should have something like that:
predictions = [1x1] matrix, probabilities = [2x1] matrix, we have [23x1], [23x2] instead.

What is it that we're getting here?

**Comment by jknightmmcs** [comment] 2020-07-25 08:38
Digging into Classify() overloads, it seems that I have located the issue. 
It seems that sample ML app uses incorrect overload, it should use (mat, size_t, arma::vec) instead. This works as expected:

```
    size_t prediction;
    arma::vec probability;

    rf.Classify(sample, prediction, probability);

    u64 result = prediction;
```

Fix it, bug in the first app you ever run with a library is pretty bad for newcomers.

**Comment by rcurtin** [comment] 2020-07-26 15:32
The problem is this line:

```
    mat sample("2 12 2 13 1 2 2 1 3 24 3 1 1 1 1 1 0 1 0 1 0 0 0");
```

This actually creates a matrix of size 1 row by 23 columns---which, because mlpack is column-major, is *23* points of one dimension each, not *one* point of 23 dimensions (which is what's intended).  The code would work if this creates a matrix with *one* column and 23 dimensions.

I've opened a PR to handle the issue in #2541.  You could adapt your example according to the diff there and it should work in the way you expect.  The workaround you suggested should work too.  Thanks for pointing out the issue.

For what it's worth, we are in the (slow) process of overhauling our documentation.  The example that you came to, right now, is not necessarily the first example that anyone else will come to.  Our website is not clear about it (yet---remember, this is all a work in progress...) but perhaps you will find this repository useful: https://www.github.com/mlpack/examples/.  (For what it's worth: even that repository is a work in progress. :))

**Comment by rcurtin** [comment] 2020-07-27 14:02
With #2541 merged, I'll go ahead and close this because I believe the issue is fixed.  Thanks for the report. :+1:

**Closed by rcurtin** 2020-07-27 14:02 UTC
Labels: t: question

**Comment by xiandong79** [comment] 2020-11-24 15:07
The long explanation is less powerful than an example. 

and the correct way to test one point is:

```
mat sample("2; 12; 2; 13; 1; 2; 2; 1; 3; 24; 3; 1; 1; 1; 1; 1; 0; 1; 0; 1; 0; 0; 0");
```

**Comment by rcurtin** [comment] 2020-11-24 15:28
Also, you could do this too:

```
mat sample("2 12 2 13 1 2 2 1 3 24 3 1 1 1 1 1 0 1 0 1 0 0 0");
sample = sample.t();
```

(Technically your approach is better as it does not need to compute the transpose.)
