### ISSUE TITLE
Remove code redundancy in ns_model_impl.hpp

### ISSUE THREAD

**Issue by sumedhghaisas** [mlpack/mlpack#674] opened 2016-06-03 20:27 UTC
There are many similar code constructs found in this file
For example...
```
if (kdTreeNS)
    delete kdTreeNS;
  if (coverTreeNS)
    delete coverTreeNS;
  if (rTreeNS)
    delete rTreeNS;
  if (rStarTreeNS)
    delete rStarTreeNS;
  if (ballTreeNS)
    delete ballTreeNS;
  if (xTreeNS)
    delete xTreeNS;
```
is similar to ...

```
if (kdTreeNS)
    return kdTreeNS->ReferenceSet();
  else if (coverTreeNS)
    return coverTreeNS->ReferenceSet();
  else if (rTreeNS)
    return rTreeNS->ReferenceSet();
  else if (rStarTreeNS)
    return rStarTreeNS->ReferenceSet();
  else if (ballTreeNS)
    return ballTreeNS->ReferenceSet();
  else if (xTreeNS)
    return xTreeNS->ReferenceSet();
```

I think it would be better to implement this using inheritance as we are doing the exact same thing that a compiler does but just with if-else clauses. (strictly having faith in people who optimizes compilers.). We can create an interface which is inherited by NSType templatized class and implement a getAppropriateTreePointer() which an interface pointer. (we should find better names).

**Comment by rcurtin** [comment] 2016-06-06 17:12
I agree, those functions are quite ugly, and I thought so when I wrote them too.

For a long time I thought, it is good to avoid inheritance entirely because in some places it can cause a noticeable slowdown (like when a virtual function is used very many times); and even though in many cases inheritance could be a good solution, I thought that if we started allowing inheritance, it would be too easy to miss a case in a PR where someone used inheritance when they shouldn't have.

But I think that there are many places where inheritance can be useful, and I guess, maybe it is necessary to allow it in some situations.  We must be careful though, if we are going to use polymorphism, to avoid going too crazy with it and making everything inherit from other things and making most functions virtual (i.e. we should not make it too much like Java :)).  I think it would be cooler if you could use something like CRTP and do static polymorphism here to accomplish the same goal, but I don't know how possible that is, I haven't thought about it much.

**Comment by stereomatchingkiss** [comment] 2016-06-06 18:36
I think the problem is the api do not allowed the users to specify the type at compile, either

1 : make TreeType as template parameter
2 : use boost variant if you want to avoid code bloat(is this the reason you do not specify TreeTypes as template param?)

Example : 

`NSModel(TreeTypes treeType = TreeTypes::KD_TREE, bool randomBasis = false);`

Make TreeTypes as

`boost::variant<TreeType::KDTree, TreeType::StandardCoverTree, /*and so on*/>`

TreeType::KDTree and other types could be empty class

```
class KDTree
{
};
```

**Comment by stereomatchingkiss** [comment] 2016-06-07 15:49
I think it is possible if you do not wish to change the public api, you can construct the boost::variant based on the enum. This way, there is only one place need to use the if else, other operations can rely on the visitor.

**Comment by rcurtin** [comment] 2016-06-07 17:42
I looked through `boost::variant`, but I dunno if the visitor policy would help since we would still have to write an `operator()` for each possible `TreeType`.  Maybe I have misunderstood?  I like the idea of `boost::variant` though. :)

**Comment by MarcosPividori** [comment] 2016-06-13 14:51
Hi!
I have been considering different approaches to this problem.
We want a data type to represent a generic neighbor search class, no matter which tree type is considered. However, we want to distinguish between KDTree/BallTree and the rest of tree types, because we want to set the leaf size in the former and the NeighborSearch Class doesn't provide a general option for that. This is the reason of the difference in the code, between KDTrees/BallTrees and the rest of the tree types.
So, as you suggested, I considered three possible approaches:

- Add TreeType as a template parameter and use SFINAE to decide if the tree should be built with specific leafSize or not. It involved a lot of lines of code...

- Create a generic NeighborSearchGen class, and make NeighborSearch class inherit from it. Then, I implemented a NeighborSearchLeaf class that encapsulates an instance of NeighborSearch class, and adds the functionality to deal with different leaf sizes. It is implemented in: https://github.com/MarcosPividori/mlpack/tree/improve-nsmodel

- Finally I considered boost variant:
  ```
    boost::variant<NSType<SortPolicy, tree::KDTree>*,
                   NSType<SortPolicy, tree::StandardCoverTree>*,
                   NSType<SortPolicy, tree::RTree>*,
                   NSType<SortPolicy, tree::RStarTree>*,
                   NSType<SortPolicy, tree::BallTree>*,
                   NSType<SortPolicy, tree::XTree>*> nSearch;
  ```
  I use template specialization in the visitors to decide if the leafSize should be considered or not.
 This is by far the simplest option, which include the least changes in actual code. Also, it only uses inheritance when defining the visitors, so I think it won't be confusing. It is implemented in: https://github.com/MarcosPividori/mlpack/tree/variants-for-ns-model

What do you think? I made a pull request in : https://github.com/mlpack/mlpack/pull/693

**Comment by MarcosPividori** [comment] 2016-06-23 02:17
Closed by https://github.com/mlpack/mlpack/pull/693

**Closed by MarcosPividori** 2016-06-23 02:17 UTC
Labels: D: easy, P: minor, T: enhancement
