### ISSUE TITLE
inconsistency with number of neighbors found between trees

### ISSUE THREAD

**Issue by elDan101** [mlpack/mlpack#1732] opened 2019-02-22 10:24 UTC
I am benchmarking some of the trees provided by mlpack. Results for a range search on a small test dataset:

```
# nnz = number of non-zero values = nearest neighbors found in total.  
mlpack/kdtree: nnz=8932 
mlpack/balltree: nnz=8410
mlpack/vptree: nnz=8834 
mlpack/rptree: nnz=8932 
mlpack/covertree: nnz=8193
mlpack/rstartree: nnz=8932 
mlpack/hilbertrtree: nnz=8932 
scipy/pdist nnz=8932
```
The reference dataset equals the query dataset.  Below are code snippet that I used to compute the different trees according to flag `tree_type`. This method is in a loop and all trees get the same data. `PointCloud` is a `struct` with a pointer to the data and dimension and number of points. 

```c++
template<typename MetricType, typename StatisticType, typename MatType> using CoverTreeT = mlpack::tree::CoverTree<MetricType, StatisticType, MatType, mlpack::tree::FirstPointIsRoot>;

size_t radiusSearchMlpack(PointCloud pts, const double radius, double *time_required, const size_t tree_type){

    const double sqradius = radius * radius;

    arma::mat referenceData(pts.pts, pts.dimpoint, pts.nrpoints, true, true);
    size_t nnz;

    // Helpful: https://mlpack.org/docs/mlpack-3.0.4/doxygen/trees.html
    switch (tree_type){  // matching of ids is in Cython wrapper class
        case 0:
            nnz = SearchWithMLTree<SquaredEuclideanDistance, KDTree>(referenceData, sqradius, time_required);
            break;
        case 1:
            nnz = SearchWithMLTree<SquaredEuclideanDistance, BallTree>(referenceData, sqradius, time_required);
            break;
        case 2:
            nnz = SearchWithMLTree<SquaredEuclideanDistance, VPTree>(referenceData, sqradius, time_required);
            break;
        case 3:
            nnz = SearchWithMLTree<SquaredEuclideanDistance, RPTree >(referenceData, sqradius, time_required);
            break;
        case 4:
            nnz = SearchWithMLTree<SquaredEuclideanDistance, CoverTreeT>(referenceData, sqradius, time_required);
            break;
        case 5:
            nnz = SearchWithMLTree<EuclideanDistance, RStarTree >(referenceData, radius, time_required);
            break;
        case 6:
            nnz = SearchWithMLTree<EuclideanDistance, HilbertRTree >(referenceData, radius, time_required);
            break;
        default:
            throw std::invalid_argument( "tree type id not understood" );
    }

    return nnz;
}
```

Method to execute the `RangeSearch` and measure time:

```c++
template <typename MetricType, template<typename TreeMetricType=SquaredEuclideanDistance, typename TreeStatType=EmptyStatistic, typename TreeMatType=arma::mat> class TreeType>
        size_t SearchWithMLTree(arma::mat referenceData, const double radius, double *time_required){

    RangeSearch<MetricType, arma::mat, TreeType> rs(referenceData);

    std::vector<std::vector<size_t> > resultingNeighbors;
    std::vector<std::vector<double> > resultingDistances;

    clock_t start = clock();
    mlpack::math::Range r(0, radius);
    //RangeSearch<> a(referenceData);
    rs.Search(r, resultingNeighbors, resultingDistances);  // reference and query set are the same
    time_required[0] = (clock() - start) / (1.0*CLOCKS_PER_SEC);

    size_t nnz =0;

    for(size_t i = 0; i < resultingDistances.size(); ++i){
        std::vector<double> resdists = resultingDistances.at(i);
        for(size_t j = 0; j < resdists.size(); ++j){
            if(resdists.at(j) != 0)
                nnz++;
        }
    }

    return nnz; 

}
```

Code that was used to check against scipy brute force: 

```
pdist_scipy = pdist(data)
pdist_scipy = squareform(pdist_scipy)
pdist_scipy[pdist_scipy > radius] = 0
nnz = pdist_scipy != 0).sum()  # gives 8932
```

So I am convinced that 8932 is the correct number of neighbours. However, I am wondering why balltree, vptree and covertree are different? 

I am happy to prepare a minimal code and data to reproduce this, if this hints a bug -- but first wanted to check if there is a short explanation. 

Thanks a lot!

**Comment by rcurtin** [comment] 2019-02-22 14:58
Hi @elDan101, I'm not sure I understand what it is that you're even doing here, so I don't know what 'nnz' is.  The trees are all fairly well tested, but the structure of the ball tree, vp-tree, and cover tree are significantly different than the kd-tree and R tree variants, so this may be the cause of what is different.  If you can explain in more detail what the numbers represent and how you built the trees (and other related information) I might be able to provide a better answer. :+1:

**Comment by elDan101** [comment] 2019-02-22 15:32
Hi @rcurtin thank you for your response. I updated the initial post and inserted some code snippets, which together with the description hopefully better describe what I am doing.

**Comment by elDan101** [comment] 2019-02-22 15:38
A small side note, where I count the `nnz`: I suspected first that checking for inequality with a double may be the cause `if(resdists.at(j) != 0)` (in the code), but when I remove this condition I still get a different number of values for the mentioned trees.

**Comment by rcurtin** [comment] 2019-02-25 20:59
I tried with a subset of the `corel` dataset that I have sitting around and am not able to reproduce the issues you've had.  Can you make the sample data available perhaps?  I tried the following using the `mlpack_range_search` program:

```
$ bin/mlpack_range_search -r corel-5k.csv -v -L 0.0 -U 1.0 -t cover -n n-cover.csv -d d-cover.csv && bin/mlpack_range_search -r corel-5k.csv -v -L 0.0 -U 1.0 -t kd -n n-kd.csv -d d-kd.csv && bin/mlpack_range_search -r corel-5k.csv -v -L 0.0 -U 1.0 -t vp -n n-vp.csv -d d.vp.csv && bin/mlpack_range_search -r corel-5k.csv -v -L 0.0 -U 1.0 -t ball -n n-ball.csv -d d-ball.csv
$ cat n-vp.csv | awk -F',' '{ print NF }' > n-vp-count.csv
$ cat n-cover.csv | awk -F',' '{ print NF }' > n-cover-count.csv
$ cat n-kd.csv | awk -F',' '{ print NF }' > n-kd-count.csv
$ cat n-ball.csv | awk -F',' '{ print NF }' > n-ball-count.csv
$ diff n-vp-count.csv n-kd-count.csv 
$ diff n-ball-count.csv n-ball-count.csv 
$ diff n-cover-count.csv n-kd-count.csv 
$ diff n-ball-count.csv n-kd-count.csv 
```

However, none of the files `n-vp-count.csv`, `n-ball-count.csv`, `n-cover-count.csv` and `n-kd-count.csv` are different, meaning that for each query point, the same number of reference points are found.

I suspect that the issue here is that you're using `SquaredEuclideanDistance` for your distance metric for some of these trees.  The squared Euclidean distance is not a metric and therefore may cause problems when pruning based on that metric.  Try using just `EuclideanDistance` and see what happens.

**Comment by elDan101** [comment] 2019-02-25 21:41
Hi @rcurtin , thank you and you are right, changing to EuclideanDistance makes all trees agree (I should have tried this earlier...). You are also right, that SquaredEuclideanDistance is not a metric, but it should still work to determine whether another point is inside a radius - but I have to admit that I not know how the trees work internally and what effect it has.  

[data.zip](https://github.com/mlpack/mlpack/files/2902641/data.zip)

Here are some generated sample data (first row and column are index/header). When I use the SquaredEuclideanDistance on this data I get:

```
mlpack/kdtree: nnz=202800 
mlpack/balltree: nnz=196350 
mlpack/vptree: nnz=196146
mlpack/rptree: nnz=202800 
mlpack/covertree: nnz=181132
mlpack/rstartree: nnz=202800 
mlpack/hilbertrtree: nnz=202800
```

When changing all to EuclideanDistance:

```
mlpack/kdtree: nnz=202800 
mlpack/balltree: nnz=202800
mlpack/vptree: nnz=202800 
mlpack/rptree: nnz=202800 
mlpack/covertree: nnz=202800
mlpack/rstartree: nnz=202800 
mlpack/hilbertrtree: nnz=202800
```

I am using the last stable release (3.0.4.)

**Comment by rcurtin** [comment] 2019-02-25 21:50
Great, glad to hear that helped.  To give you more of an idea, there are lots of ways that you can use trees for pruning for range search... the "textbook" way with kd-trees usually works on squared distances, because it depends only on a relaxed form of the triangle inequality.  But the other trees have much more complex build rules.  For instance, the vp-tree splits points into "near" and "far", i.e., the points with distance from the center less than `d` go into the 'near' child and the rest go into the 'far' child (I'm omitting details about how we find `d`).  That requires all properties of a metric for tree-building, so if we don't have a true metric then the results can be wrong. :+1:

I'll go ahead and close this issue then since it is solved---I don't think there's any need to look into the actual data (thanks for taking the time to post it though).  Please do feel free to open more issues in the future if you have them. :)

**Closed by rcurtin** 2019-02-25 21:50 UTC
Labels: c: methods, t: question
